### ISSUE TITLE
How to override

### ISSUE THREAD

**Issue by lutcmoi** [ContainX/openstack4j#1000]
Hi,

I am just wondering how to override an API.
I need to use the os-hypervisor API but the existing one in the current version doesn't have all methods.

Is there a simple way to do something like :
`OSClientV3 os = ...`
`os.compute().hypervisors().myNewMethod()`

Where `os.compute().hypervisors()` returns my custom hypervisor class overriding the default one ?

Thank you.

**Comment by auhlig** [comment]
Please ask usage questions in our google group or on stackoverflow.
