### ISSUE TITLE
unable to retrieve users and projects with v3 api

### ISSUE THREAD

**Issue by valyamotta** [ContainX/openstack4j#1003]
Need help in resolving this issue.

I have a java program to list users and projects from a newton devstack installation.
it has two projects admin,demo
admin project has a user admin  

But when i run **it does not list any project or users.**
It however **does list servers,images** etc. 
For users and projects it gives  **{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}**

Java code:
----------------------------------------------------------------------------------------

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
 
 
import org.openstack4j.api.OSClient.OSClientV3;
import org.openstack4j.model.identity.v3.Tenant;
import org.openstack4j.model.identity.v3.User;
import org.openstack4j.model.identity.v3.Project;
import org.openstack4j.openstack.OSFactory;
import org.openstack4j.model.common.Identifier;
import org.openstack4j.api.Builders;
import org.openstack4j.model.image.Image;
import org.openstack4j.api.types.Facing;
import org.openstack4j.model.compute.Server;

public class monkey {

    public static void main(String[] args) {
        Identifier domainid = Identifier.byName("Default");
		Identifier projectid = Identifier.byName("admin");
        /* init os object with username, password, tenantname */
		
       
		OSClientV3 os = OSFactory.builderV3()
                    .endpoint("http://192.168.10.10/identity/v3")
                    .credentials("admin", "nomoresecret",domainid)
					.scopeToDomain(domainid)
					.scopeToProject(projectid, domainid)
                    .authenticate();
 
        OSFactory.enableHttpLoggingFilter(true);
        // Find all Users
        os.useRegion("RegionOne");
 

        List<? extends User> users = os.identity().users().list();
		System.out.println(users);			

        List<? extends Project> prjs = os.identity().projects().list();
		System.out.println(prjs);		
	

}

---------------------------------------------------------------------------------------------------
 Output : Same is with openstack4j-3.0.3. I could get logging working only in 3.0.0
---------------------------------------------------------------------------------------------------
javac -cp .;openstack4j-3.0.0-withdeps.jar monkey.java

java -cp .;openstack4j-3.0.0-withdeps.jar monkey
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 28, 2017 4:33:47 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET http://192.168.10.10/identity/users
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: 3b33fd9a2f724a0fb09d59ab182539e6

Apr 28, 2017 4:33:47 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 404
1 < Connection: Keep-Alive
1 < Content-Length: 93
1 < Content-Type: application/json
1 < Date: Fri, 28 Apr 2017 15:44:05 GMT
1 < Keep-Alive: timeout=5, max=99
1 < Server: Apache/2.4.7 (Ubuntu)
1 < Vary: X-Auth-Token
**{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}**

[]
Apr 28, 2017 4:33:47 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET http://192.168.10.10/identity/projects
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: 3b33fd9a2f724a0fb09d59ab182539e6

Apr 28, 2017 4:33:47 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 404
1 < Connection: Keep-Alive
1 < Content-Length: 93
1 < Content-Type: application/json
1 < Date: Fri, 28 Apr 2017 15:44:05 GMT
1 < Keep-Alive: timeout=5, max=98
1 < Server: Apache/2.4.7 (Ubuntu)
1 < Vary: X-Auth-Token
**{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}**}

[]

**Comment by vinodborole** [comment]
Refer #694

**Comment by valyamotta** [comment]
Hi Vinod, 
Thanks for responding.  changing enpoint url to include /v3 in keystone db  was the answer
