### ISSUE TITLE
Thirdparty dep versions and updates

### ISSUE THREAD

**Issue by yllucsmit** [ContainX/openstack4j#1004]
Been using openstack4j for about a year now and over that time we've noticed that some thirdparty deps aren't updated from release to release.  For example Guava (v17.0) and RestEasy (v2.3.7) are both trailing the latest available (and conflicting with other deps in our code).  Is there a reason some deps aren't updated to the latest? 

As an openstack4j user we're happy to clone the repo and contribute patches if that helps to update to the latest versions of these deps, unless there's a requirement to stay on the older versions.

Thanks in advance!

**Comment by auhlig** [comment]
Hi @yllucsmit, 
Thanks for filing an issue for that. There's no reason to live with outdated dependencies, so I would be happy if you could come up with a PR to update them.
Feel free to reach out in case you need help.

**Comment by yllucsmit** [comment]
I see that 3.0.5 has Guava 20.0 included - thank you for that and my apologies for not being able to get around to creating a patch for you.
