### ISSUE TITLE
deserialize error when get hypervisor's info .

### ISSUE THREAD

**Issue by dreadbird** [ContainX/openstack4j#1012]
When I use the api" org.openstack4j.openstack.compute.internal.ext.HypervisorServiceImpl.list(HypervisorServiceImpl.java:23)"
to get the hypervisors,throw a exception:
`Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: {"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"], "vendor": ["GenuineIntel"], "nodes": 1, "topology": {"cores": 12, "threads": 24}}; line: 1, column: 2] (through reference chain: org.openstack4j.openstack.compute.domain.ext.HypervisorCPUInfo["model"])
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: {"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"], "vendor": ["GenuineIntel"], "nodes": 1, "topology": {"cores": 12, "threads": 24}}; line: 1, column: 2]`

because the model and vendor of the "cpu_info" is a Object instead of a String.
In the openstack rest api,it return as flow:

`
"cpu_info": "{"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"], "vendor": ["GenuineIntel"], "nodes": 1, "topology": {"cores": 12, "threads": 24}}",
`
the hypervisor type is :
`"hypervisor_type": "VServer"`

there is a note in the openstack api description:
`
Since version 2.28 cpu_info field is returned as a dictionary instead of string.
`

**Comment by auhlig** [comment]
Thanks for investigating @dreadbird. Since you already found the solution would you like to submit a fix?

**Comment by dreadbird** [comment]
Okay, my colleage will fix it and submit.

**Comment by zizhongwei** [comment]
I  will fix it.

**Comment by auhlig** [comment]
Fixed by @zizhongwe via #1028 .Can we close this issue?
