### ISSUE TITLE
why return <? extends T> type in many func

### ISSUE THREAD

**Issue by JackSunshine** [ContainX/openstack4j#1013]
Hi all
I want to ask why the return value type is <? extends T> in many func, Is it on purpose? what‘s the use? it's hard to use. 
for example, in SecurityGroup,
List<? extends SecurityGroupRule> getRules();
i can not call List.add to add one rule to the list when i got the rulelist by calling getRules. 
casue we cannot add element to extend list.

btw, many model neutron classes don't override equal method, i'd like to submit a PR :)

thanks

**Comment by auhlig** [comment]
Can we close this in favor of #1023 @JackSunshine ?

**Comment by JackSunshine** [comment]
move this discuss to https://github.com/ContainX/openstack4j/issues/1023
