### ISSUE TITLE
No error while creating Alarms,but the alarm is not successfully created on the openstack server

### ISSUE THREAD

**Issue by prashr186** [ContainX/openstack4j#1014]
Hi ,
I have created an alarm using openstack4j as follows:
   Alarm alarm2 = os
            .telemetry()
            .alarms()
            .create(alarm);
        System.out.println("Alarm details:"+alarm.getAlarmId());
        System.out.println("alarms:"+os.telemetry().alarms().list());

But after alarm is created the  AlarmId is null and  is also  not found in the list of alarms.
There are no errors during the creation of alarms also.

After further analysis ,found that the url request to create the alarm from openstack4j is http://172.16.1.100:8777/v2/alarms instead of http://172.16.1.100:8042/v2/alarms.

Alarm service is running on 8042 and not on 8777.

Thanks,
prashr186

**Comment by auhlig** [comment]
Per API definition it's port 8777 for ceilometer. If you configured something else you might want to adjust that or override the respective definition in OS4j.
Please close if your not reporting an issue and ask usage questions in our Google group or on stackoverflow.

**Comment by prashr186** [comment]
i checked the port value in the /etc/ceilometer/ceilometer.conf file and  it reads 8777.But still i am facing the same issue
```
snippet of ceilometer.conf file
workers=20
host=0.0.0.0
port=8777
[collector]
```

**Comment by auhlig** [comment]
Check the configuration of the service endpoint in keystone.
Please ask usage questions in the forum.
