### ISSUE TITLE
UntrustedSSL SSLVerificationDisabled may cause NullPointerException

### ISSUE THREAD

**Issue by tangxiaodon89** [ContainX/openstack4j#1025]
when i user config.withSSLVerificationDisabled property to connector https openstack NullPointerException occurred.

I found that it cause by UntrustedSSL return null X509Certificates.

    private UntrustedSSL() {
        try
        {
            TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
                public X509Certificate[] getAcceptedIssuers() {
                    return null;//this return null case NullPointerException
                }
                public void checkClientTrusted(X509Certificate[] certs, String authType) {}
                public void checkServerTrusted(X509Certificate[] certs, String authType) {}
            } };

**Comment by auhlig** [comment]
PR merged. Closing issue. Please reopen if necessary.
