### ISSUE TITLE
Can  openstack4j  create an instance from /os-volumes_boot insterface ?

### ISSUE THREAD

**Issue by fenggeyeyin** [ContainX/openstack4j#1037]
if you need create an instance from  a  volume  , not an image ,  you must use os-volumes_boot insterface,  do  openstack4j support this ?

**Comment by auhlig** [comment]
Isn't this done using ` blockDeviceMapping`
https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/compute/domain/NovaServerCreate.java#L61

**Comment by auhlig** [comment]
Please ask further usage questions in the google group or on stackoverflow.
