### ISSUE TITLE
ContainX slack

### ISSUE THREAD

**Issue by pdube** [ContainX/openstack4j#1054]
Hello,

On the README page, it shows a slack for ContainX, but I can't connect to it. Is there a way for me to join?

Thanks :)

**Comment by pdube** [comment]
If not, what is the best way to communicate? On the Google Group?

**Comment by auhlig** [comment]
I admit I'm not using the slack group, do you @vinodborole? But the google group is a good place.

**Comment by vinodborole** [comment]
Yeah me too :)

**Comment by pdube** [comment]
Thanks :)
