### ISSUE TITLE
NullPointer exception when use only token authentication

### ISSUE THREAD

**Issue by vkochan** [ContainX/openstack4j#1065]
Hi All,

I got NullPointer exception when used token authentication w/o specifying the scope like:

OSClientV3 os = OSFactory.builderV3()
                  .endpoint("http://127.0.0.1:5000/v3")
                  .token("{token}"
                  .authenticate();

Looks like exception occurs in 206 line within OSAuthenticator.java,
may it be caused because domain was not specified ?

Thanks,

**Comment by auhlig** [comment]
I didn't find a test for this. Might be valid. I'll take look
