### ISSUE TITLE
Updating Firewall error  v2

### ISSUE THREAD

**Issue by scsunchen** [ContainX/openstack4j#1068]
>  <dependency>
		  <groupId>org.pacesys.openstack4j.connectors</groupId>
		  <artifactId>openstack4j-httpclient</artifactId>
		  <version>3.0.4</version>
		

> </dependency>

**Unrecognized attribute(s) 'policy', status=400, status-code=BAD_REQUEST**

> 16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "{[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "firewall" : {[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "shared" : false,[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "policy" : "036ab1f1-271e-4db1-8d04-e4ed226924c8",[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "admin_state_up" : false,[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "firewall_policy_id" : "036ab1f1-271e-4db1-8d04-e4ed226924c8"[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  }[\r][\n]"
16:05:16.505 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "}"

Cannot update

**Comment by scsunchen** [comment]
NeutronFirewallUpdate is not a  @JsonIgnore ?
      @JsonIgnore
	@Override
	public String getPolicy() {
		return policyId;
	}

**Comment by auhlig** [comment]
Could be a bug. Would you like to contribute and submit a fix @scsunchen ?

**Comment by auhlig** [comment]
#1074 was merged. Closing issue. Please reopen if necessary.
