### ISSUE TITLE
Upgrade of Apache httpClient for SSL certificate verification and Corresponding change in ApacheHttpClientExecutor

### ISSUE THREAD

**Issue by kushalagrawal1** [ContainX/openstack4j#1070]
Hi,

We are using openstack4j-3.0.4. We were facing several issues with it because our OpenStack environment is **ipv6 +https**.  Below are the issue while using os4j:

1. Caused by: javax.net.ssl.SSLException: Certificate for <[2001:470:68e0:1151::100]> doesn't match any of the subject alternative names: [2001:470:68e0:1151::100, instack.localdomain, vip.localdomain]
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:177)
        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:62)

2.  while using resteasy-connecter We were not able to use  **withHostnameVerifier** or **withSSLVerificationDisabled** because these config are getting neglected while HttpClient is getting created in **ApacheHttpClientExecutor**

> It is required to upgrade Apache httpclient version to 4.5.3 to avoid SSLCertificate issue in IPv6. We have already changed the code accordingly to solve these 2 issues.

With your permission we would like to contribute the code so that other people can also make use of it without redundent effort.

**Comment by auhlig** [comment]
Yes please! Updates for these dependencies are very welcome.
Don't hesitate to reach out in case you need help.

**Comment by kushalagrawal1** [comment]
Hi,
I have created a pull request for the same. Can you please have a look. let me know If any enhancement is required.

https://github.com/ContainX/openstack4j/pull/1072

**Comment by kushalagrawal1** [comment]
Closing issue as the code has been updated to incorporate the changes.
