### ISSUE TITLE
OpenStack4j on Devstack

### ISSUE THREAD

**Issue by orkungedik** [ContainX/openstack4j#1089]
Hi,

Is there any support OpenStack4j on DevStack for testing purposes? I am not able to login and execute a function on DevStack by OpenStack4j functions.

Best regards,

Orkun Gedik

**Comment by auhlig** [comment]
I was using devstack without issues. 
Can you share more details on the error(s) you get?

**Comment by orkungedik** [comment]
Hi auhlig,

I installed latest DevStack on Ubuntu on 16.04 LTS. I am able to login and create virtual server on dashboard appication. But when I execute the code below, the System is generating HTTP 401 error. I am sure that the user and password combination is correct;

```
OSClientV2 x = OSFactory.builderV2().endpoint("http://10.0.0.1/identitiy").credentials("admin","mypassword").authenticate();

List serverList = (List) x.compute().images().list();
System.out.println(serverList);
```

Do you have any suggestion?

Thank you for your helps,

Orkun Gedik

**Comment by auhlig** [comment]
The Identity v3 case in the 1st code snippet does 2 things: Unscoped authentication and retrieving the list of compute images. While you're unscoped, the token returned by the authentication has no service catalog.
So, is the initial authentication successful?  You might want scoped authentication to a domain or project to obtain a service catalog. See [documentation](https://github.com/containx/openstack4j#authenticating). Then this might work. (Given you're user has permissions in that scope)

**Comment by orkungedik** [comment]
Hi Ahulig,

Thank you for your support. When I add tenantName into the login, code worked successfully :)

Second part is, any way to use keystone V3 on DevStack and call methods on OpenStack4j library? Do you have any doc to install V3 on DevStack?

Thank you again :)

Orkun Gedik

**Comment by auhlig** [comment]
Hi @orkungedik,
OpenStack4j offers Identity V3. Actually I tested it with Devstack, back then. But I don't have docs anymore. It's worth to post this in our google group. Maybe someone can help.

**Comment by auhlig** [comment]
No issue here. Closing.
