### ISSUE TITLE
NullPointerException due to HttpExecutorServiceImpl.execute returning null

### ISSUE THREAD

**Issue by pjdarton** [ContainX/openstack4j#1094]
While testing the Jenkins openstack-cloud plugin, which uses openstack4 version 3.0.4j, I encountered a
```
java.lang.NullPointerException
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:156)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:70)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:165)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:128)
	at jenkins.plugins.openstack.compute.internal.Openstack.<init>
```

On investigation I found that this was caused by [`HttpExecutorServiceImpl`'s `execute` method](https://github.com/ContainX/openstack4j/blob/master/connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpExecutorServiceImpl.java#L28) catching Exception, calling `printStackTrace()` and then returning null (which the caller didn't check for) instead of throwing the Exception.
Further inspection revealed that the execute method is not documented as returning null, and there are multiple callers of this method which all assume that this method cannot return null.
One of these has to change - either we stop it from swallowing the exception and then returning null, or we cope with it returning null (personally, I think the first option is better).

 - To stop it from returning null,  [`execute`](https://github.com/ContainX/openstack4j/blob/3.0.4/connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpExecutorServiceImpl.java#L28) must be modified so that it throws an exception if it encounters one, e.g.
```java
    @Override
    public <R> HttpResponse execute(HttpRequest<R> request) {
        try {
            return invoke(request);
        }
        catch (ResponseException re) {
            throw re;
        }
        catch (RuntimeException e) {
            throw e;
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

 - To cope with it returning null, we#d have to
   - Update the [API](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/core/transport/HttpExecutorService.java#L11) to document that this method can return null
   - Prevent NPE in [SenlinWebHookServiceImpl.action](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/openstack/senlin/internal/SenlinWebHookServiceImpl.java#L26)
   - Prevent NPE in  [OSAuthenticator.authenticateV2](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java#L123)
   - Prevent NPE in  [OSAuthenticator.authenticateV3](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java#L156)
   - Prevent NPE in  [BaseOpenStackService.Invocation.execute](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java#L213)
   - Prevent NPE in  [BaseOpenStackService.Invocation.executeWithResponse](https://github.com/ContainX/openstack4j/blob/3.0.4/core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java#L228)

With the existing code, simply printing the stack trace of the original exception to stderr does not allow the calling code to display the underlying exception (which, in my case, I believe is related to https://github.com/square/okhttp/issues/2427) back to the user (the user only sees the NullPointerException), which complicates the debugging process.

Note: While this bug was seen using Openstack4J version 3.0.4, the issue is still present in the current version (although the line numbers differ in some places).

**Comment by vinodborole** [comment]
@pjdarton  thanks for pointing out the issue, it would help if you can contribute a fix for this.

**Comment by pjdarton** [comment]
Done.  See PR #1095.

**Comment by vinodborole** [comment]
LGTM @auhlig what do you think?

**Comment by pjdarton** [comment]
PR #1095 has been merged.  We can close this now.
