### ISSUE TITLE
Implement Networking SFC API

### ISSUE THREAD

**Issue by arvindn05** [ContainX/openstack4j#1097]
The networking SFC api's are available and are stable since openstack mitaka.

If these can be exposed via openstack4j that would be good.
 
https://docs.openstack.org/networking-sfc/latest/contributor/api.html#rest-api

**Comment by auhlig** [comment]
Apologies for the delay. Yes please. Would you like to take this @arvindn05?
Feel free to reach out in case you need help.

**Comment by arvindn05** [comment]
@dmitryintel will be helping with implementing this. He has raised #1141 to implement the functionality. Hopefully it will be accepted by the community.

**Comment by dmitryintel** [comment]
@auhlig,  I propose to add ```SFCService``` (naming?) under ```api/networking/ext```. This service will be on the same level of service objects as ```NetworkingService```. That means ```SFCService``` shall:

- Return ```FlowClassifierService``` from ```flowclassifiers()``` call.
- Similarly with ```PortGroupService```, ```PortPairService```, ```PortGroupChainService```.
- Thes above four services will be lower-level CRUD services, much like  ```NetworkService```.
- All four lower-leverl services will be implement ```Buildable``` and the builders will be provided in the  Impl.
-  ```OS.sfc()``` call shall return an implementation of  ```SFCService```
