### ISSUE TITLE
openstack4j glance upload slowly

### ISSUE THREAD

**Issue by zhaijp** [ContainX/openstack4j#1102]
Help,Help,Help
It took me a few minutes to upload the cirros 17m, and it was on the LAN.

**Comment by zhaijp** [comment]
There is someone can help me?
Image image = os.imagesV2().create(
				Builders.imageV2()
					.name("Cirros 0.3.0 x64yyy")
					.containerFormat(ContainerFormat.BARE)
					.visibility(Image.ImageVisibility.PUBLIC)
					.diskFormat(DiskFormat.QCOW2)
					.minDisk(0L)
					.minRam(0L)
					.build()
			);

Long t1 = System.currentTimeMillis();
		ActionResponse upload = os.imagesV2().upload(
			image.getId(),
			payload,
			image);
		Long t2 = System.currentTimeMillis();
		
		System.out.println("time:"+(t2 - t1));


The console output:time:34890

**Comment by auhlig** [comment]
I guess you're not reporting a bug, aren't you @zhaijp? Please reach out to the user group. 
If there's something off that needs fixing, please reopen this issue and ping me.
