### ISSUE TITLE
Telemetery gnocchi alarm create

### ISSUE THREAD

**Issue by zhangjianweibj** [ContainX/openstack4j#1103]
from openstack Mitaka,Telemetry project is divided into four parts:Ceilometer、 Aodh、Gnocchi and Panko.using gnocchi as storage,alarm created by aodh is different from previous way.like "aodh alarm create \
  --name cpu_hi \
  --type gnocchi_resources_threshold \
  --description 'instance running hot' \
  --metric cpu_util \
  --threshold 70.0 \
  --comparison-operator gt \
  --aggregation-method mean \
  --granularity 600 \
  --evaluation-periods 3 \
  --alarm-action 'log://' \
  --resource-id INSTANCE_ID \
  --resource-type instance"

however,openstack4j not support this way still.

**Comment by vinodborole** [comment]
@zhangjianweibj feel free to contribute

**Comment by auhlig** [comment]
Yes please @zhangjianweibj. Don't stop pinging us if you need help :)
