### ISSUE TITLE
SSL connect to VMware Openstack platform

### ISSUE THREAD

**Issue by orkungedik** [ContainX/openstack4j#1104]
Hi,

I am trying to connect to Openstack platform by using code below;

```
Config config = Config.DEFAULT.withSSLVerificationDisabled();

_openstackclientv3 = OSFactory.builderV3()
			                       .endpoint(getEndPoint())
			                       .credentials(getUsername(),getPassword()).withConfig(config)
			                       .scopeToDomain(Identifier.byId(getDomain()))
			                       .authenticate();
```

As a response I get an error, below;

> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

Site is "https://10.0.0.2:5000/v3"

What may cause the problem?

Thank you for your support,

Orkun Gedik

**Comment by auhlig** [comment]
Confusing. Why are you using the V3 client with a V2 endpoint?

**Comment by orkungedik** [comment]
Fixed the URL

**Comment by auhlig** [comment]
I assumed that this is working. Based on the information you've given so far, it's hard to tell if this is a bug in OpenStack4j or something on your end. Try different connectors and see if this fixes the issue.

**Comment by orkungedik** [comment]
I replaced HTTP with HTTPS connection. I am able to connect to Openstack now. I'll go into detail in future for HTTPS connection and open a new issue if it is a bug.

Thank you for your support,

Orkun Gedik
