### ISSUE TITLE
Does openstack4j supports Cinder v2 and v3?

### ISSUE THREAD

**Issue by surajmaher** [ContainX/openstack4j#1109]
- Does openstack4j supports Cinder v2 and v3?
- Is there any link/document which gives supported versions list for each OpenStack service?

**Comment by auhlig** [comment]
Hey @surajmaher,
See http://www.openstack4j.com/learn .
This should work. Please report or better submit a PR if that's not the case. 
We're only distinguishing by version if the new one differs fundamentally or introduces breaking changes. (e.g. identity v2/v3)

**Comment by surajmaher** [comment]
Ok, Thnx.

**Comment by wangyuLoveinbj** [comment]
Hi,Currently I can't get the volume data through openstack4j. The current volume api version is v3

**Comment by tangguochang** [comment]
seems openstack4j get service endpoint by service name, if blockstorage service is named as cinder, it works fine.  otherwise（ie cinderv2 ） it won't work
