### ISSUE TITLE
custom endpoint resolver

### ISSUE THREAD

**Issue by lekasaras** [ContainX/openstack4j#1116]
Hi everyone, Since i'm new to the openstack4j, I don't have the idea on the usage of Custom Enpointurl resolver.

Since i'm having different endpoint url for neutron, its executes the following url as request.

https://keystone-uk1-ecl.api.ntt.com/v2.0 -> /networks

but my actual endpoint url is,

https://network-uk1-ecl.api.ntt.com/v2.0 

How do i use this endpoint instead of the above one???

**Comment by auhlig** [comment]
See the FAQ section here http://www.openstack4j.com/learn/getting-started .
Also please use the google group for usage questions
