### ISSUE TITLE
Neutron Port creation does not support device_owner and device_id port properties

### ISSUE THREAD

**Issue by evgenyfedoruk** [ContainX/openstack4j#1117]
When Building the port with a Port builder, it's possible to set the device owner and device id values via 
PortBuilder deviceOwner(String deviceOwner); method.

But, org.openstack4j.openstack.networking.domain.NeutronPortCreate class which builds the port create request body does not have those properies.

So port is created without the device owner and device id values.

**Comment by auhlig** [comment]
Merged. Closing.
