### ISSUE TITLE
Resteasy connector ignores SSLContext

### ISSUE THREAD

**Issue by ThomasBri** [ContainX/openstack4j#1161]
The Resteasy connector does not check whether the HttpRequest's Config object has an SSLContext.
Other connectors perform this check e.g. the [httpclient connector](https://github.com/ContainX/openstack4j/blob/8fb99200d16a64888060c8c308be04a2b602115e/connectors/httpclient/src/main/java/org/openstack4j/connectors/httpclient/HttpClientFactory.java#L76).

Therefore something like this
```
Config config = Config.newConfig();
config.withSSLContext(sslContext);
OSClient os = OSFactory.builderV3().withConfig(config)
```
does not work as expected.

**Comment by vinodborole** [comment]
@ThomasBri  thanks for the fix
