### ISSUE TITLE
cached auth tokenV3 in redis,but load from cache occoured error when deserialize

### ISSUE THREAD

**Issue by tutudelaoba** [ContainX/openstack4j#1204]
Because I don't want to go to keystone authentication every time, I cache each user's authentication token in redis, so I can use the token to generate OSClient, but I get an error when I get the deserialize from the cache:

my code demo :
`        Token token = OSFactory.builderV3()
                .endpoint(keystone_auth_url)
                .credentials(userName, password, Identifier.byName(domainName))
                .scopeToProject(Identifier.byId(projectId))
                .perspective(Facing.PUBLIC)
                .authenticate().getToken();

        try {
            String tokenCacheKey = Base64Helper.encode(buildTokenCacheKey(userName, projectId, domainName), "UTF-8");
            redisService.set(tokenCacheKey, token);
//            Token t = (Token) redisService.get(tokenCacheKey);
            Token t1 = JSON.parseObject(String.valueOf(redisService.get(tokenCacheKey)), KeystoneToken.class);
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }`

error info:

"Could not read JSON: Can not deserialize instance of org.openstack4j.openstack.identity.v3.domain.KeystoneAuth$AuthIdentity out of START_ARRAY token\n at [Source: [B@1dfd2151; line: 1, column: 15529] (through reference chain: org.openstack4j.openstack.identity.v3.domain.KeystoneToken[\"credentials\"]->org.openstack4j.openstack.identity.v3.domain.KeystoneAuth[\"identity\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.openstack4j.openstack.identity.v3.domain.KeystoneAuth$AuthIdentity out of START_ARRAY token\n at [Source: [B@1dfd2151; line: 1, column: 15529] (through reference chain: org.openstack4j.openstack.identity.v3.domain.KeystoneToken[\"credentials\"]->org.openstack4j.openstack.identity.v3.domain.KeystoneAuth[\"identity\"])"

some su

**Comment by scsunchen** [comment]
你用法错误， 你可以把 v3 token 对象进行 jdk 序列化 存入 redis 。不要存成json 格式就行了。加载的时候使用 OSFactory.clientFromToken(Token token) 进行使用就行了。一般云平台时间有效期是24小时。你可以少存5分钟或者10分钟什么的

**Comment by tutudelaoba** [comment]
thx, Really effective
