### ISSUE TITLE
List<? extends > show empty list

### ISSUE THREAD

**Issue by gintoki1010** [ContainX/openstack4j#1243]
Hi , I am using openstack4j 3.1.0 and devstack(queens and rocky) in vultr host(VPS) , I did pass the Version 3 Authentication , however , when I try to list user or subnet etc , it return a empty list . is there anyone could help me ? Sorry for my poor english.

**Comment by gintoki1010** [comment]
I try all the authentication way.

**Comment by yangchao313** [comment]
OSClientV3 os = OSFactory.builderV3()
                .endpoint("http://192.168.4.211:5000/v3")
                .credentials("admin","123456", Identifier.byName("Default"))
                .scopeToProject(Identifier.byName("admin"),Identifier.byName("Default"))
                .authenticate();
