### ISSUE TITLE
Hi everyone, I wonder know how to add a user into a project with openstack4j

### ISSUE THREAD

**Issue by gintoki1010** [ContainX/openstack4j#1244]
Hi everyone, I wonder know how to add a user into a project with openstack4j.
I have tried the code but faild
        User user = os.identity().users().create(Builders.user()
                .name("test")
                .description("A new user.")
                .password("test")
                .email("foobar@example.org")
                .defaultProjectId("851b4c876535493ab962af0d4d8e74af")
                .domainId("default")
                .build());
I checked the user list and it did success create the user  , however , the new user account can not login into dashboard and it show  the account is not authorized for any projects or domains.

**Comment by yangchao313** [comment]
//Grant a role to a user in a project
ActionResponse grantProjectRole = os.identity().roles().grantProjectUserRole("projectId", "userId", "roleId");
