### ISSUE TITLE
I created a new user and granted the role to the user in the project, but prompted 401 when I logged in.,

### ISSUE THREAD

**Issue by yangchao313** [ContainX/openstack4j#1258]
I created a new user and granted the role to the user in the project, but prompted 401 when I logged in.
User openstackUser = os.identity().users().create(Builders.user()
                    .name(user.getUsername())
                    .password(user.getPassword())
                    .email(user.getEmail())
                    .defaultProjectId(user.getOpenstackProjectId())
                    .domainId("default")
                    .build());

ActionResponse grantProjectRole = os.identity().roles().grantProjectUserRole(user.getOpenstackProjectId(), openstackUser.getId(), "roleId");

OSClientV3 os = OSFactory.builderV3()
                .endpoint(endpoint)
                .credentials(sysUser.getUsername(),sysUser.getOpenstackPwd(), Identifier.byName(domain))
                .scopeToProject(Identifier.byName(sysUser.getOpenstackProject()),Identifier.byName(domain))
                .authenticate();

Return results Unauthorized

**Comment by RandyWithZero** [comment]
did you resolve this problem.i met the same one。
