### ISSUE TITLE
Untrusted certificates support

### ISSUE THREAD

**Issue by RPallas92** [ContainX/openstack4j#13]
Hello, we are trying to connect to an untrusted certificate Openstack server, but it seems the API doesn't allow untrusted certs. 
Anybody knows a solution? Thanks

**Comment by redixin** [comment]
useNonStrictSSLClient looks like unsafe workaround, because in this case client will connect to any server with any https cert.

OpenStack clients has option like "cacert" and OpenStack deployments are often using self signed certificates, so it would be great to have such option in openstack4j.

**Comment by vinodborole** [comment]
@redixin would like to contribute a fix for this?

**Comment by redixin** [comment]
@vinodborole I just found a solution. This can be done by applying Config with custom SSLContext. Something like this:
```java
InputStream is = new FileInputStream("/tmp/ca.pem");
CertificateFactory cf = CertificateFactory.getInstance("X.509");
X509Certificate caCert = (X509Certificate) cf.generateCertificate(is);
TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
ks.load(null);
ks.setCertificateEntry("caCert", caCert);
tmf.init(ks);
sslContext = SSLContext.getInstance("TLS");
sslContext.init(null, tmf.getTrustManagers(), null);
Config config = Config.newConfig();
config.withSSLContext(sslContext);
OSClient os = OSFactory.builderV3().withConfig(config)....

```

**Comment by vinodborole** [comment]
@redixin great, thanks for the code snippet.
