### ISSUE TITLE
Vulnerable dependency: resteasy-jaxrs-3.1.4.Final.jar

### ISSUE THREAD

**Issue by ylcstarseeker** [ContainX/openstack4j#1309]
resteasy-jaxrs-3.1.4.Final.jar depended by openstack4j 3.1.0 has a known vulnerability:
https://issues.redhat.com/browse/RESTEASY-1704?_sscc=t

**Comment by cosnina** [comment]
Hello, any update on this issue? 
Thanks

**Comment by olivergondza** [comment]
@cosnina, this is addressed in fork https://github.com/openstack4j/openstack4j/pull/63 and will be part of the next release.
