### ISSUE TITLE
How to get the flavor metadata ? I can't open "http://www.openstack4j.com/"

### ISSUE THREAD

**Issue by fighterhit** [ContainX/openstack4j#1317]
Sorry, I can't open the [http://www.openstack4j.com/](http://www.openstack4j.com/) website and I didn't find how to get the flavor metadata.

**Comment by olivergondza** [comment]
@fighterhit, I would like you to invite to use openstack4j/openstack4j with its website up and up-to-date: https://openstack4j.github.io/

**Comment by fighterhit** [comment]
Thank you @olivergondza . But I am confused whether there is a difference between the two projects?

**Comment by olivergondza** [comment]
The difference is that ContainX/openstack4j is dead and development continues in https://github.com/openstack4j/openstack4j/. There are no differences apart from [continued development](https://github.com/openstack4j/openstack4j/releases).

**Comment by fighterhit** [comment]
> The difference is that ContainX/openstack4j is dead and development continues in https://github.com/openstack4j/openstack4j/. There are no differences apart from [continued development](https://github.com/openstack4j/openstack4j/releases).

Ok, I get it. Thanks for your reply.
