### ISSUE TITLE
Unable to invoke request - connection still allocated.

### ISSUE THREAD

**Issue by adisan82** [ContainX/openstack4j#133]
Hi,

here is error:
ConnectionException{message=Unable to invoke request, status=0}
Caused by: javax.ws.rs.ProcessingException: Unable to invoke request
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.

Connection method:

private static OSClient os = null;

    public OpenStackCompute connect(String urlName, String userName, String password, String tenantName) throws API2COpenStackException {
        try {
            if (os == null) {
                os = OSFactory.builder().endpoint(urlName).credentials(userName, password).tenantName(tenantName).authenticate();
            } else {
                Access access = os.getAccess();
                os = OSFactory.clientFromAccess(access);
            }
        } catch (AuthenticationException e) {
            throw new API2COpenStackException("Can not authenticate!");
        } catch (Exception e) {
            throw new API2COpenStackException("Can not connect!");
        }
        return this;
    }

I'm using connection method many times in code, and sometimes when I call connection method I'm getting error: "connection still allocated". How can I avoid this situation ? I'm making many 5 or 6 connection because creating virtal machine is made asynchronous. After one task we go out from adapter and after 30 sec check result and made another task etc.

**Comment by vinodborole** [comment]
@adisan82 closing this for now, please reopen it if the issue persist
