### ISSUE TITLE
openstack4j how to handle https

### ISSUE THREAD

**Issue by Baby-Anran** [ContainX/openstack4j#1332]
openstack4j throw Exception: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

**Comment by olivergondza** [comment]
Your JVM does not seem to trust the SSL certificate of some of the OpenStack endpoints. See this guide for details: https://javarevisited.blogspot.com/2012/03/add-list-certficates-java-keystore.html.

This is not related to the library.
