### ISSUE TITLE
Issue with retrieving correct value for Max Floating IP

### ISSUE THREAD

**Issue by antoniaczica** [ContainX/openstack4j#144]
I've been trying to use the QuotaSet API to find the max total and total used values for floating IPs, but it seems that the max total value will not change from 100, regardless of what I set the max total floating IP value to inside the Openstack UI. Is there something I'm missing or any other way I can retrieve the max total floating IP value?

**Comment by Zakariyya** [comment]
I also encountered this problem, depressed
