### ISSUE TITLE
got error 409

### ISSUE THREAD

**Issue by chechuironman** [ContainX/openstack4j#194]
hey guys,

When I try to resume or reboot a server I got error 409:

[org.openstack4j.openstack.compute.functions.ToActionResponseFunction] ERROR: 409,Conflict

Funny thing, stop works fine.

My code

os = OSFactory.builder()
	 		                .endpoint("https://192.168.101.10:5000/v2.0")
	 		                .credentials("xxxx","xxxx")
	 		                .tenantName("xxxx")
	 		                .authenticate();
	            	 os.compute().servers().action(valueNode.toString(),Action.RESUME);

Thanks in advance

**Comment by gondor** [comment]
So the 409 is coming from OpenStack.  Typically it means the server is in a state that is not valid for your action.  When you do a reboot is it right after another action or fresh startup of a server?

**Comment by chechuironman** [comment]
I tried the resume ... I got the error 409... And later the reboot and get
the same error...

Sent from my iPhone

On 6 Jan 2015, at 20:46, Jeremy Unruh <notifications@github.com> wrote:

So the 409 is coming from OpenStack. Typically it means the server is in a
state that is not valid for your action. When you do a reboot is it right
after another action or fresh startup of a server?

—
Reply to this email directly or view it on GitHub
<https://github.com/gondor/openstack4j/issues/194#issuecomment-68921888>.

**Comment by gondor** [comment]
1.  Could you post a toString() of the Server object.  I'd like to see what state it's in.  
2.  What deployment are you using?  i.e. (if in house then what release Juno, Havanna, etc, or if Cloud Provider is it Rackspace, HPCloud) etc.

Thanks

**Comment by chechuironman** [comment]
1. what do you mean with the server object? I just grab the server ID and
sent to the method:
os.compute().servers().action(valueNode.toString(),Action.RESUME);

valueNode is an objet with the id of the server

2.-I'm running an IceHouse version

Thanks Jeremy :)

2015-01-06 21:30 GMT+01:00 Jeremy Unruh <notifications@github.com>:

>
>    1. Could you post a toString() of the Server object. I'd like to see
>    what state it's in.
>     2. What deployment are you using? i.e. (if in house then what release
>    Juno, Havanna, etc, or if Cloud Provider is it Rackspace, HPCloud) etc.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gondor/openstack4j/issues/194#issuecomment-68928446>.
>



-- 
Chechu
Web: www.notesfromchechu.com
Twitter: http://twitter.com/chechuironman
LinkdIn: http://es.linkedin.com/in/jesusarteche

**Comment by chechuironman** [comment]
this is the output from the line you sent me:

NovaServer{id=80320993-40fc-40dc-a8c8-7684271584d7, name=Ubuntu 2,
image={id=9f275ee9-4006-48eb-b2a8-9569008bf1d1, links=[{href=
https://xx.xx.xx.xx:8774/9c3c5b7588304ef8ac0820738a6e1429/images/9f275ee9-4006-48eb-b2a8-9569008bf1d1,
rel=bookmark}]}, flavor=NovaFlavor{id=11, ephemeral=0, swap=0,
rxtx_factor=1.0, is_public=true,
links=[GenericLink{href=https://xx.xx.xx.xx::8774/9c3c5b7588304ef8ac0820738a6e1429/flavors/11,
rel=bookmark}],
}, status=ACTIVE, diskconfig=MANUAL,
userId=182f6de9223f4f8c9bd5fb165c101723, created=Tue Jan 06 19:04:54 CET
2015, updated=Tue Jan 06 22:33:53 CET 2015, launched at=Tue Jan 06 19:05:09
CET 2015, tenantId=9c3c5b7588304ef8ac0820738a6e1429,
hostId=1e149119ee5b2afa3aa477b16775dfaa9273f03ffbedfddd6641deaf,
addresses=NovaAddresses{addresses={Shared-Flat-Network2=[NovaAddress{address=192.168.0.13,
type=fixed, version=4, macaddr=fa:16:3e:77:9a:72,
}]},
}, hypervisor host=tor01kvm001ccz050, powerstate=1,
instanceName=instance-0000006d, vmState=active, metadata={}}

2015-01-06 23:43 GMT+01:00 Jeremy Unruh <notifications@github.com>:

> Ok, then this should work. I meant fetching the server and toString().
>
> Example:
>
> System.out.println(os.compute().servers().get(serverID));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gondor/openstack4j/issues/194#issuecomment-68948323>.
>



-- 
Chechu
Web: www.notesfromchechu.com
Twitter: http://twitter.com/chechuironman
LinkdIn: http://es.linkedin.com/in/jesusarteche

**Comment by chechuironman** [comment]
Hey Jeremy, I managed to fix it...

Thanks a million :)

2015-01-07 10:10 GMT+01:00 Chechu <chechuironman@gmail.com>:

> this is the output from the line you sent me:
>
> NovaServer{id=80320993-40fc-40dc-a8c8-7684271584d7, name=Ubuntu 2,
> image={id=9f275ee9-4006-48eb-b2a8-9569008bf1d1, links=[{href=
> https://xx.xx.xx.xx:8774/9c3c5b7588304ef8ac0820738a6e1429/images/9f275ee9-4006-48eb-b2a8-9569008bf1d1,
> rel=bookmark}]}, flavor=NovaFlavor{id=11, ephemeral=0, swap=0,
> rxtx_factor=1.0, is_public=true,
> links=[GenericLink{href=https://xx.xx.xx.xx::8774/9c3c5b7588304ef8ac0820738a6e1429/flavors/11,
> rel=bookmark}],
> }, status=ACTIVE, diskconfig=MANUAL,
> userId=182f6de9223f4f8c9bd5fb165c101723, created=Tue Jan 06 19:04:54 CET
> 2015, updated=Tue Jan 06 22:33:53 CET 2015, launched at=Tue Jan 06 19:05:09
> CET 2015, tenantId=9c3c5b7588304ef8ac0820738a6e1429,
> hostId=1e149119ee5b2afa3aa477b16775dfaa9273f03ffbedfddd6641deaf,
> addresses=NovaAddresses{addresses={Shared-Flat-Network2=[NovaAddress{address=192.168.0.13,
> type=fixed, version=4, macaddr=fa:16:3e:77:9a:72,
> }]},
> }, hypervisor host=tor01kvm001ccz050, powerstate=1,
> instanceName=instance-0000006d, vmState=active, metadata={}}
>
> 2015-01-06 23:43 GMT+01:00 Jeremy Unruh <notifications@github.com>:
>
>> Ok, then this should work. I meant fetching the server and toString().
>>
>> Example:
>>
>> System.out.println(os.compute().servers().get(serverID));
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gondor/openstack4j/issues/194#issuecomment-68948323>.
>>
>
>
>
> --
> Chechu
> Web: www.notesfromchechu.com
> Twitter: http://twitter.com/chechuironman
> LinkdIn: http://es.linkedin.com/in/jesusarteche
>



-- 
Chechu
Web: www.notesfromchechu.com
Twitter: http://twitter.com/chechuironman
LinkdIn: http://es.linkedin.com/in/jesusarteche

**Comment by chechuironman** [comment]
ups...nop...the conflict still there :(

2015-01-07 19:47 GMT+01:00 Chechu <chechuironman@gmail.com>:

> Hey Jeremy, I managed to fix it...
>
> Thanks a million :)
>
> 2015-01-07 10:10 GMT+01:00 Chechu <chechuironman@gmail.com>:
>
>> this is the output from the line you sent me:
>>
>> NovaServer{id=80320993-40fc-40dc-a8c8-7684271584d7, name=Ubuntu 2,
>> image={id=9f275ee9-4006-48eb-b2a8-9569008bf1d1, links=[{href=
>> https://xx.xx.xx.xx:8774/9c3c5b7588304ef8ac0820738a6e1429/images/9f275ee9-4006-48eb-b2a8-9569008bf1d1,
>> rel=bookmark}]}, flavor=NovaFlavor{id=11, ephemeral=0, swap=0,
>> rxtx_factor=1.0, is_public=true,
>> links=[GenericLink{href=https://xx.xx.xx.xx::8774/9c3c5b7588304ef8ac0820738a6e1429/flavors/11,
>> rel=bookmark}],
>> }, status=ACTIVE, diskconfig=MANUAL,
>> userId=182f6de9223f4f8c9bd5fb165c101723, created=Tue Jan 06 19:04:54 CET
>> 2015, updated=Tue Jan 06 22:33:53 CET 2015, launched at=Tue Jan 06 19:05:09
>> CET 2015, tenantId=9c3c5b7588304ef8ac0820738a6e1429,
>> hostId=1e149119ee5b2afa3aa477b16775dfaa9273f03ffbedfddd6641deaf,
>> addresses=NovaAddresses{addresses={Shared-Flat-Network2=[NovaAddress{address=192.168.0.13,
>> type=fixed, version=4, macaddr=fa:16:3e:77:9a:72,
>> }]},
>> }, hypervisor host=tor01kvm001ccz050, powerstate=1,
>> instanceName=instance-0000006d, vmState=active, metadata={}}
>>
>> 2015-01-06 23:43 GMT+01:00 Jeremy Unruh <notifications@github.com>:
>>
>>> Ok, then this should work. I meant fetching the server and toString().
>>>
>>> Example:
>>>
>>> System.out.println(os.compute().servers().get(serverID));
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gondor/openstack4j/issues/194#issuecomment-68948323>
>>> .
>>>
>>
>>
>>
>> --
>> Chechu
>> Web: www.notesfromchechu.com
>> Twitter: http://twitter.com/chechuironman
>> LinkdIn: http://es.linkedin.com/in/jesusarteche
>>
>
>
>
> --
> Chechu
> Web: www.notesfromchechu.com
> Twitter: http://twitter.com/chechuironman
> LinkdIn: http://es.linkedin.com/in/jesusarteche
>



-- 
Chechu
Web: www.notesfromchechu.com
Twitter: http://twitter.com/chechuironman
LinkdIn: http://es.linkedin.com/in/jesusarteche

**Comment by gondor** [comment]
So, have you tried this via the Python CLI client?  I have a feeling this will fail as well since under the covers is invoking the same REST calls to OpenStack.  I really don't believe this is an OpenStack4j issue since the 409, Conflict is common and documented when a resource is in a state thats not supported by the requested action.   I also read that IceHouse had issues with Resume, etc if a server was "rescued" and a 409 would be returned. This was fixed in Juno.  Thats one scenario I found.

**Comment by chechuironman** [comment]
mmm it is working with Jclouds... :(

2015-01-07 20:28 GMT+01:00 Jeremy Unruh <notifications@github.com>:

> So, have you tried this via the Python CLI client? I have a feeling this
> will fail as well since under the covers is invoking the same REST calls to
> OpenStack. I really don't believe this is an OpenStack4j issue since the
> 409, Conflict is common and documented when a resource is in a state thats
> not supported by the requested action. I also read that IceHouse had issues
> with Resume, etc if a server was "rescued" and a 409 would be returned.
> This was fixed in Juno. Thats one scenario I found.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gondor/openstack4j/issues/194#issuecomment-69076801>.
>



-- 
Chechu
Web: www.notesfromchechu.com
Twitter: http://twitter.com/chechuironman
LinkdIn: http://es.linkedin.com/in/jesusarteche

**Comment by gondor** [comment]
Ok, so this is confusing since it works for me.  However when you sent me the output of your server in a previously comment it shows a status=ACTIVE.  According to the docs on OpenStack RESUME only works if the server is currently in a SUSPENDED state.   We may be propagating the error vs ignoring it. 

Doesn't explain reboot though.  Could you send me the HTTP wire output after the server call.  To turn this on you just need to add the following before your RESUME call:

```java
        OSFactory.enableHttpLoggingFilter(true);
```

**Comment by vinodborole** [comment]
@chechuironman closing this for now, please reopen it if the issue persist
