### ISSUE TITLE
how to use addSchedulerHint method when boot a server

### ISSUE THREAD

**Issue by frank-zera** [ContainX/openstack4j#228]
Hi，
my openstack use differentHostFilter as my default filter. but i don't know how to use addSchedulerHint method when boot a server.

in openstack api, like this:
{
'server': {
    'name': 'server-1',
    'imageRef': 'cedef40a-ed67-4d10-800e-17455edce175',
    'flavorRef': '1'
},
'os:scheduler_hints': {
    'different_host': ['a0cf03a5-d921-4877-bb5c-86d26cf818e1',
                       '8c19174f-4220-44f0-824a-cd1eeef10287'],
}

the different_host is a list, but how to set it a list in addSchedulerHint.

Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", "d22fbb80-c366-48c4-8dec-71a23f86a9d2").build();
this is ok. but when i have many vm id tos deliver, i don't know how.

**Comment by gondor** [comment]
Not sure I completely understand but the addSchedulerHint is 0..N.  You can keep going:

```java
Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", "d22fbb80-c366-48c4-8dec-71a23f86a9d2").addSchedulerHint("different_host2", "23232-c366-48c4-8dec-71a23f86a9d2") // etc
```

Does that answer your question?

**Comment by frank-zera** [comment]
Hi， gondor，
thank you for your reply.
your reply can not solve my problem.
i do this:
Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", "d22fbb80-c366-48c4-8dec-71a23f86a9d2").addSchedulerHint("different_host", "23232-c366-48c4-8dec-71a23f86a9d2") 

but in openstack, it only get one different_host, other different_host may be droped.

so i think it may be a bug.

**Comment by gondor** [comment]
Are both "different_host" the same value and the UUID is different?  The underlying schema is a Map and "different_host" is a key in the map so duplicates would automatically be dropped.

**Comment by frank-zera** [comment]
different_host is a key and unique， the uuids is a list.
my test case is:
Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", "d22fbb80-c366-48c4-8dec-71a23f86a9d2,23232-c366-48c4-8dec-71a23f86a9d2").build();

Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", "d22fbb80-c366-48c4-8dec-71a23f86a9d2 23232-c366-48c4-8dec-71a23f86a9d2").build();

List<String> list1 = new ArrayList<String>();
list1.add（"d22fbb80-c366-48c4-8dec-71a23f86a9d2"）;
list1.add（"23232-c366-48c4-8dec-71a23f86a9d2"）;
Builders.server().name(name).flavor(flavorId).image(imageId).addSchedulerHint("different_host", list1.toString()).build();

they are all incorrect.

i know the key is "different_host", but how to construct the value?

**Comment by gondor** [comment]
Ok I just checked in a fix and you now can pass through a list or even an array to the scheduler hints.

Couple examples:
```java
Builders.server().name(name).flavor(flavorId).addSchedulerHint("different_host", new String[] { "2232-3232", "23455-232-342", "etc" }).build();

// or
Builders.server().name(name).flavor(flavorId).addSchedulerHint("different_host", myList).build();
// .... etc
```

Code checked in and SNAPSHOT deployed. Let me know

**Comment by frank-zera** [comment]
ok， when i use the new sdk， i will reply this issue

**Comment by frank-zera** [comment]
Hi, gondor
how can i contribute my code to this project.
when i use os4j, i found it miss some functions. so i add some, and test them ok.

**Comment by vinodborole** [comment]
@frank-zera closing this for now, please reopen it if the issue persist
