### ISSUE TITLE
Is there any plan for trove support?

### ISSUE THREAD

**Issue by octupszhang** [ContainX/openstack4j#299]
Dear gondor:
  We plan to use trove recently, do you have any plan for trove support? If not ,we shall do it, do you have any suggestion for us? Thank you.

**Comment by cp16net** [comment]
I was looking at this project and did not see Trove support. Has there been any progress on adding some trove support?

**Comment by cp16net** [comment]
If there is no work done on adding Trove I'd like to work on adding this. Thanks.

**Comment by gondor** [comment]
Nobody has contributed support to date.  If you want to tackle this awesome!  Appreciate it.

**Comment by octupszhang** [comment]
I didn't use trove at last,so I have no work for trove support. Thanks.

**Comment by cp16net** [comment]
@octupszhang ok thanks for the info and @gondor i'll work on a patch set for this in my spare time. I'm a contributor to Trove looking to get more API support across different languages. Thanks!

**Comment by auhlig** [comment]
Closing as trove is supported since https://github.com/ContainX/openstack4j/pull/801
