### ISSUE TITLE
Exception not caught while creating floating-ip.

### ISSUE THREAD

**Issue by vishvesh** [ContainX/openstack4j#302]
```
1 > POST http://10.xx.xx.xx:8774/v2/98e5c3f334e348eeb59c13291d72dc12/os-floating-ips
{
  "pool" : "313d69fc-004a-4b80-a88a-ff21b94feb88"
}

Mar 26, 2015 6:00:49 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread http-bio-80-exec-9
2 < 500
2 < Connection: keep-alive
2 < Content-Length: 128
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Fri, 27 Mar 2015 01:00:09 GMT
2 < X-Compute-Request-Id: req-740b154c-8dd8-47e8-86d8-0b0f0487503f
{"computeFault": {"message": "The server has either erred or is incapable of performing the requested operation.", "code": 500}}
```

Could you please catch/propagate this error??

**Comment by gondor** [comment]
Looking above it appears your getting a 500 response code.  This should be propagated already.  Can you try catching a ServerResponseException around the call your making just to make sure.

Thanks

**Comment by vishvesh** [comment]
I am having hard-time reproducing the same error :( I have put a catch block for `ServerResponseException ` now.. if it triggers I'll notice it and will let you know..

In the mean time.. 
```
POST http://10.xx.xx.xx:8774/v2/84dee99320ad423e9e6ae7601ae27541/os-floating-ips
{
  "pool" : "7e35701f-ac02-4a67-8f72-6733df1568ac"
}
INFO: 2 * Client response received on thread http-bio-80-exec-10
2 < 404
2 < Connection: keep-alive
2 < Content-Length: 112
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Tue, 31 Mar 2015 21:45:22 GMT
2 < X-Compute-Request-Id: req-60fa0e25-4401-4cee-992c-31b86c51c09c
{"itemNotFound": {"message": "No more floating ips in pool 7e35701f-ac02-4a67-8f72-6733df1568ac.", "code": 404}}
```
This guy isn't caught..

**Comment by gondor** [comment]
Ok the above I can fix, since it's a 404. It's the original 500 I was more interested in.

**Comment by gondor** [comment]
I fixed the 404 and re-deploy maven.  If you ever find more info on the 500 not being propagated you may want to open a new issue so we can eventually close this one.

**Comment by vishvesh** [comment]
Thanks @gondor : I'll figure out a way to reproduce it & will let you know :+1:

**Comment by symcssn** [comment]
Hello @gondor !

I am curious if this issue is related to a similar bug I found yesterday: https://github.com/gondor/openstack4j/issues/314.

Is the 404 fix in 2.0.2 or a 2.0.3 snapshot?

Thanks!

**Comment by vinodborole** [comment]
@vishvesh closing this issue for now, please reopen this if you think its still an issue.

**Comment by vishvesh** [comment]
@vinodborole : Sure.. :+1:
