### ISSUE TITLE
how can I get all tenants volumes by admin role?

### ISSUE THREAD

**Issue by houyu533** [ContainX/openstack4j#303]
like servers api  “listAll()”.

**Comment by iviireczech** [comment]
In order to retrieve volumes across all tenants, parameter "all_tenants" must be set to "1". 

Solution:
```java
final Map<String, String> filteringParams = new HashMap<>();
filteringParams.put("all_tenants", "1");
final List<? extends Volume> volumes = osClient.blockStorage().volumes().list(filteringParams);

**Comment by vinodborole** [comment]
@houyu533 closing this issue for now, please reopen this if you think its still an issue.
