### ISSUE TITLE
os.heat().resources().show() return an object with null attributes

### ISSUE THREAD

**Issue by dreadbird** [ContainX/openstack4j#304]
Hi,gondor
I need u help.
when I want to get the resource's detail.the api os.heat().resources().show()  return an object,
but the atrributes are all null value.
def asg = os.heat().resources().show("asg-servers-2", "563aae6d-2456-43a1-bf43-6fea3a8eb4d4", "asg")
asg.getResourceName() and asg.getResourceStatus() are null

is there any problem?or is this a bug?

I use other api,they are ok.for example,
os.heat().stacks().getDetails("asg-servers-2", "563aae6d-2456-43a1-bf43-6fea3a8eb4d4")
will return the object with values.

can u help me?
tks

**Comment by gondor** [comment]
@dreadbird  I currently don't have any stacks deployed to test this.  Are you using the Jersey2 (default) connector?  Could you enable http logging and send me the output of the request and response for the API call thats returning nulls.

To turn on logging add this line before the API call:
```java
OSFactory.enableHttpLoggingFilter(true);
```

**Comment by dreadbird** [comment]
@gondor ,thanks for your answer.
I have debug into the heat source.The request and the response are right.
the request is:
http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0/resources/asg
and the response:
{"resource": {"resource_name": "asg", "links": [{"href": "http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0/resources/asg", "rel": "self"}, {"href": "http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0", "rel": "stack"}], "resource_data": {}, "logical_resource_id": "asg", "resource_status": "CREATE_COMPLETE", "updated_time": "2015-04-01T09:55:56Z", "required_by": ["web_server_scaleup_policy", "web_server_scaledown_policy"], "resource_status_reason": "state changed", "physical_resource_id": "a462a855-f4a1-4579-a7e4-f4b18eff6a5d", "resource_type": "OS::Heat::AutoScalingGroup", "description": ""}}


as you say ,the log as follow:
四月 02, 2015 9:41:31 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Sending client request on thread main
1 > GET http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0/resources/asg
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Key: 123456a?
1 > X-Auth-Token: MIIN8QYJKoZIhvcNAQcCoIIN4jCCDd4CAQExCTAHBgUrDgMCGjCCDEcGCSqGSIb3DQEHAaCCDDgEggw0eyJhY2Nlc3MiOiB7InRva2VuIjogeyJpc3N1ZWRfYXQiOiAiMjAxNS0wNC0wMlQwMTo0MDowOS4wOTMxOTMiLCAiZXhwaXJlcyI6ICIyMDE1LTA0LTAyVDAyOjQwOjA5WiIsICJpZCI6ICJwbGFjZWhvbGRlciIsICJ0ZW5hbnQiOiB7ImRlc2NyaXB0aW9uIjogIkFkbWluIFRlbmFudCIsICJlbmFibGVkIjogdHJ1ZSwgImlkIjogImU4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3IiwgIm5hbWUiOiAiYWRtaW4ifX0sICJzZXJ2aWNlQ2F0YWxvZyI6IFt7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo4Nzc0L3YyL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3IiwgInJlZ2lvbiI6ICJyZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjg3NzQvdjIvZThjYWFiOWYwZjg0NGFmZGJmZThmNWZhZmNhYjFkZTciLCAiaWQiOiAiMGMzMjE1OGI5YzEzNDIyMGJkNDRjZDA1NWNmMGMxYTEiLCAicHVibGljVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo4Nzc0L3YyL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3In1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogImNvbXB1dGUiLCAibmFtZSI6ICJub3ZhIn0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovL2NvbnRyb2xsZXI6ODc3Ni92Mi9lOGNhYWI5ZjBmODQ0YWZkYmZlOGY1ZmFmY2FiMWRlNyIsICJyZWdpb24iOiAicmVnaW9uT25lIiwgImludGVybmFsVVJMIjogImh0dHA6Ly9jb250cm9sbGVyOjg3NzYvdjIvZThjYWFiOWYwZjg0NGFmZGJmZThmNWZhZmNhYjFkZTciLCAiaWQiOiAiNTU5Y2M5MGM5YjAzNDE3NTgyNWRiZjRiMjk4YTM2YmMiLCAicHVibGljVVJMIjogImh0dHA6Ly9jb250cm9sbGVyOjg3NzYvdjIvZThjYWFiOWYwZjg0NGFmZGJmZThmNWZhZmNhYjFkZTcifV0sICJlbmRwb2ludHNfbGlua3MiOiBbXSwgInR5cGUiOiAidm9sdW1ldjIiLCAibmFtZSI6ICJjaW5kZXJ2MiJ9LCB7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo5MjkyIiwgInJlZ2lvbiI6ICJyZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjkyOTIiLCAiaWQiOiAiNzY4Y2Y2ZDIzZjNhNDQzYjhkMTQ3NDY0OTc4ZmMwMzEiLCAicHVibGljVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo5MjkyIn1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogImltYWdlIiwgIm5hbWUiOiAiZ2xhbmNlIn0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjg3NzciLCAicmVnaW9uIjogInJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTAuMTAuMS4xMTE6ODc3NyIsICJpZCI6ICI1ZDhkMjg0ZDZkNWU0ZWJjOThiMWI5ZGVhYjVkYTRiYyIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjg3NzcifV0sICJlbmRwb2ludHNfbGlua3MiOiBbXSwgInR5cGUiOiAibWV0ZXJpbmciLCAibmFtZSI6ICJjZWlsb21ldGVyIn0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjgwMDAvdjEiLCAicmVnaW9uIjogInJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTAuMTAuMS4xMTE6ODAwMC92MSIsICJpZCI6ICI3ZDAzNjBmZDdlY2Q0ZWQ3ODI4YWFjZjVmOTIxZjljOSIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjgwMDAvdjEifV0sICJlbmRwb2ludHNfbGlua3MiOiBbXSwgInR5cGUiOiAiY2xvdWRmb3JtYXRpb24iLCAibmFtZSI6ICJoZWF0LWNmbiJ9LCB7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly9jb250cm9sbGVyOjg3NzYvdjEvZThjYWFiOWYwZjg0NGFmZGJmZThmNWZhZmNhYjFkZTciLCAicmVnaW9uIjogInJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vY29udHJvbGxlcjo4Nzc2L3YxL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3IiwgImlkIjogIjBkMjdjNGFjZGI5NzRjZGM5MTNmNjUwNTgyYjUwN2UzIiwgInB1YmxpY1VSTCI6ICJodHRwOi8vY29udHJvbGxlcjo4Nzc2L3YxL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3In1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogInZvbHVtZSIsICJuYW1lIjogImNpbmRlciJ9LCB7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo4MDA0L3YxL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3IiwgInJlZ2lvbiI6ICJyZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjgwMDQvdjEvZThjYWFiOWYwZjg0NGFmZGJmZThmNWZhZmNhYjFkZTciLCAiaWQiOiAiM2Q5NDc0MzdkYWIzNDhiNTk5NDNiMmFjMWUwMzZiZDUiLCAicHVibGljVVJMIjogImh0dHA6Ly8xMC4xMC4xLjExMTo4MDA0L3YxL2U4Y2FhYjlmMGY4NDRhZmRiZmU4ZjVmYWZjYWIxZGU3In1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogIm9yY2hlc3RyYXRpb24iLCAibmFtZSI6ICJoZWF0In0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzEwLjEwLjEuMTExOjM1MzU3L3YyLjAiLCAicmVnaW9uIjogInJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTAuMTAuMS4xMTE6NTAwMC92Mi4wIiwgImlkIjogIjFjNzMxNzE2NWZmZDQ2MDY5M2ZkYjQwZDJlYWU5Mjg3IiwgInB1YmxpY1VSTCI6ICJodHRwOi8vMTAuMTAuMS4xMTE6NTAwMC92Mi4wIn1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogImlkZW50aXR5IiwgIm5hbWUiOiAia2V5c3RvbmUifV0sICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJhZG1pbiIsICJyb2xlc19saW5rcyI6IFtdLCAiaWQiOiAiYjliYWJkZDJhZTU0NDk5ZDliY2I1NTM5ZjJmMjRhYzUiLCAicm9sZXMiOiBbeyJuYW1lIjogIl9tZW1iZXJfIn0sIHsibmFtZSI6ICJhZG1pbiJ9XSwgIm5hbWUiOiAiYWRtaW4ifSwgIm1ldGFkYXRhIjogeyJpc19hZG1pbiI6IDAsICJyb2xlcyI6IFsiOWZlMmZmOWVlNDM4NGIxODk0YTkwODc4ZDNlOTJiYWIiLCAiMWJjMmZiYjY5ODI4NDQ4NWE2OTgzNDYyNTQ4NTU2NzgiXX19fTGCAYEwggF9AgEBMFwwVzELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVuc2V0MQ4wDAYDVQQHDAVVbnNldDEOMAwGA1UECgwFVW5zZXQxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbQIBATAHBgUrDgMCGjANBgkqhkiG9w0BAQEFAASCAQBJrYE0s2KmE22a48xmJEc+loX+3M1qLDPPHWmdOsIKhYq+G3Kj+Zh6wEFL9xq0RW06p24M06uKklV+zQHUQcER98sHkW6iwVxUZbzHx3RsRhYZtf9RgXUclKJ7mWtYtN3sxaPPLKP44he5Tf9qEujj93yBlvGuodhVvJ1tQVJWsUdmZd6gDtbHklCPe2zQBGidWINlzVEy9owbdlsRLAYdFw9XOEaCJOUaPtSAl3aHap9pfCJ5T5AGvJkSAzgUzEmd4xPUUJmzO-nXJWA3hqZ7nCudVzID3hcW08vqNNRB+HvVXkKhUBNiG+bBalbQdT0uI7yYlHWxHJ+4Dl+56Azq
1 > X-Auth-User: admin

四月 02, 2015 9:41:32 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 2 * Client response received on thread main
2 < 200
2 < Connection: keep-alive
2 < Content-Length: 733
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Thu, 02 Apr 2015 01:40:09 GMT
{"resource": {"resource_name": "asg", "links": [{"href": "http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0/resources/asg", "rel": "self"}, {"href": "http://10.10.1.111:8004/v1/e8caab9f0f844afdbfe8f5fafcab1de7/stacks/sdk-asg-wg-1/501dbac9-d07a-414c-9502-e1457ee4e7f0", "rel": "stack"}], "resource_data": {}, "logical_resource_id": "asg", "resource_status": "CREATE_COMPLETE", "updated_time": "2015-04-01T09:55:56Z", "required_by": ["web_server_scaleup_policy", "web_server_scaledown_policy"], "resource_status_reason": "state changed", "physical_resource_id": "a462a855-f4a1-4579-a7e4-f4b18eff6a5d", "resource_type": "OS::Heat::AutoScalingGroup", "description": ""}}

**Comment by vinodborole** [comment]
@dreadbird closing this issue for now, please reopen this if you think its still an issue.
