### ISSUE TITLE
Obtaining Usage Data Per Instance

### ISSUE THREAD

**Issue by Shaileshwar551** [ContainX/openstack4j#305]
Hi,
   My requirement is as follows: I have two projects say project1 and project2: project1 has 3 VMs say VM1, VM2 and VM3 and project2 has 3 VMs say VM4, VM5 and VM6. I want to know how much disk space has been utilized in a particular instance (e.g., VM2) by a user (e.g., in a month) under a particular project (project1 here).

Does disk.write.bytes metric suit my use case? Here is my code to obtain the volume of writes for a period of 1 month (say):

List<? extends Sample> samples = os.telemetry().meters()
                                          .samples("disk.write.bytes", SampleCriteria.create()
                                          .project("cad0b1a2e0b848a0a1604fe60c9358c7")  //projectID
                                          .timestamp(SampleCriteria.Oper.GTE, startDate)
                                          .timestamp(SampleCriteria.Oper.LTE, endDate)
                                          .resource("6bf26c4d-5993-48ec-8cde-b7fd944e88b8")); //instanceID

I don't think the output obtained here represents the disk space utilized. How can I achieve the same? Correct me if I am wrong. Looking forward to some help.

Thanks,
Shaileshwar

**Comment by vinodborole** [comment]
@Shaileshwar551  please close this if its not an issue anymore.
