### ISSUE TITLE
get the cpu-usage and memory-usage of the vm instance by vm's id.

### ISSUE THREAD

**Issue by AkBao** [ContainX/openstack4j#324]
can you tell me how to do it? give me some key code.

**Comment by gondor** [comment]
If you have Telemetry (metering) installed on your OpenStack deployment you can query for samples using OpenStack4j for the cpu or cpu_util or mem metric using the ResourceId param of the instance identifier.

**Comment by vinodborole** [comment]
@AkBao  please close this if you are satisfied with the answer.
