### ISSUE TITLE
how to use compute extensions?

### ISSUE THREAD

**Issue by tealover** [ContainX/openstack4j#371]
I want to operate OSTenantNetworks which is described  in compute extensions. so how can I use the extension? 
Thank you.

**Comment by gondor** [comment]
Can you send me the link that points to this in OpenStack's API documentation?  It will help me determine if we support this or scope it to support it as an enhancement.

**Comment by tealover** [comment]
Because I  use nova-network instead of neutron, but I need to control the network creating, deleting, showing. As I know Openstack4J does not support this.
http://developer.openstack.org/api-ref-compute-v2-ext.html

**Comment by vinodborole** [comment]
@tealover closing this issue for now, please reopen it if you feel its still an issue
