### ISSUE TITLE
Is there any plan for Compute API v2.1 support?

### ISSUE THREAD

**Issue by zizhongwei** [ContainX/openstack4j#374]
Now the OpenStack team  described the Kilo release,Is there any plan for Compute API v2.1 support?

**Comment by bsemp** [comment]
Question seems related to discussion about [service endpoint selection](https://groups.google.com/forum/?hl=fr#!topic/openstack4j/zoRJ34favg8)

**Comment by vinodborole** [comment]
closing this as its supported now.
