### ISSUE TITLE
Reference to Issue: Connect openstack server remotely using ssh tunnel time out due to endpoint changes #192 

### ISSUE THREAD

**Issue by ghost** [ContainX/openstack4j#384]
Hi Gondor,
We are facing similar scenario over here. We are trying to access the openstack from one domain (Domain A) to another domain (Domain B), both are accessible from each other.

We tried with the solution suggested by you but still its giving ConnectionTimeout Exception. Let me know if you need any specific details to resolve this.

**Comment by vinodborole** [comment]
closing this issue for now, please reopen it if you feel its still an issue
