### ISSUE TITLE
How to create a tenant in a domain?

### ISSUE THREAD

**Issue by batdesso** [ContainX/openstack4j#408]
Hi,

We want to create a project within a domain via OpenStack4j and Keystone V3.
We have a domain my_domain and the project that we want to create is my_project.
The user we are using is the domain admin user for the domain my_domain.
We are using the following code:

OSClient os = OSFactory.builderV3()
           .endpoint(endpoint)
           .credentials(username, password)
           .perspective(Facing.ADMIN) // at least we are using this successfully with Keystone V2
           .useNonStrictSSLClient(true)
           .scopeToDomain(Identifier.byName("my_domain")) 
           .authenticate();
Tenant tenant = os.identity().tenants().create(Builders.tenant().name("my_domain").description("my_domain_descr").enabled(true).build());

The result of this is tenant is null.

1 > POST https://identity.mylab.net:5000/v3/auth/tokens
1 > Accept: application/json
1 > Content-Type: application/json
1 > OS4J-Auth-Command: Tokens
{
  "auth" : {
    "identity" : {
      "password" : {
        "user" : {
          "id" : "my_domain_admin",
          "password" : "password"
        }
      },
      "methods" : [ "password" ]
    },
    "scope" : {
      "domain" : {
        "name" : "my_domain"
      }
    }
  }
}

Create tenant:

1 > POST https://identity.mylab.net:5000/v3/tenants
1 > Accept: application/json
1 > Content-Type: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: ea0ef649c566435a9f8cadfaa00daa1c
{
  "tenant" : {
    "name" : "my_tenant",
    "description" : "my_tenant_descr",
    "enabled" : true
  }
}

INFO: 2 * Client response received on thread main
2 < 404
2 < Connection: keep-alive
2 < Content-Length: 36
2 < Content-Type: application/json; charset=utf-8
2 < Date: Mon, 15 Jun 2015 08:40:37 GMT
2 < Server: nginx/1.4.4
2 < Status: 404 Not Found
2 < Strict-Transport-Security: max-age=31536000
2 < X-Powered-By: Phusion Passenger 4.0.33
2 < X-Request-Id: 08a358c4-0bb4-4166-b466-ee0b1da41b61
2 < X-Runtime: 0.004498
{"status":"404","error":"Not Found"}

tenant:null

Do you have an idea what is wrong with our attempt to create a tenant?
We noticed that the request for creating a tenant is not a scoped in our domain, but in default one.
What else need to  be done in order to create a tenant in particular domain?

Best regards - bat Desso

**Comment by batdesso** [comment]
Hi,

Further looking in the https calls the TenantServiceImpl performs I found that it actually calls the /tenants which is V2 way to do this, instead to call /v3/projects. It seems like the the latest released Openstack4j version 2.0.3 uses Keystone V3 only for authentication, but doesn't performs V3 calls for create/list projects. Is this correct?

Best regards - Desso

**Comment by gondor** [comment]
That is correct.  We are moving towards the newer API's in the upcoming releases.  Intact the current 2.0.4-SNAPSHOT allows you to specify which API versions per service you prefer which is a start.  See Issue #390 which is the baseline to open up support to the newer APIs in upcoming releases.

**Comment by vishvesh** [comment]
I see there is no `ProjectService` in `IdentityService` currently. With OpenStack's newer versions (especially Keystone V3), all `/v2.0/tenants` will be converted to `/v3/projects`, and all `/v2.0 as you know are converted to /v3` Eventually they will deprecate `V2`. @gondor : Is anyone currently implementing the `Keystone V3 Services : Domain/Group/Project/etc`? I can start looking into it keeping backwards compatibility? Is there a current thread dedicated to `V3` I could follow up on?

**Comment by mazimo** [comment]
Is there any more news? (see questions above)
What is the current level of support for keystone v3? 

I'm using OpenStack kilo with keystone v3. I have applied a policy.json file with rules/policies, a couple of domains, and would like to use OpenStack4J to list roles, create projects within domains, and other use cases. So far I am only able to authenticate.

**Comment by vinodborole** [comment]
enhancement has been added in #390 hence closing this issue for now
