### ISSUE TITLE
Add floating IP to the server

### ISSUE THREAD

**Issue by mqh123456** [ContainX/openstack4j#421]
OSClient os = OSFactory.builder()
                .endpoint("http://control.openstack.test:5000/v2.0")
                .credentials("admin","admin")
                .tenantName("admin")
                .perspective(Facing.ADMIN)
                .authenticate();
String serverId="d616b51a-d389-466c-8317-27466f73990c";
Server server = os.compute().servers().get(serverId);
os.compute().floatingIps().addFloatingIP(server,"172.16.40.127");
Floating IP can not bind the server.
AddFloatingIP the use of these 2 methods do not understand.
please help me, thank you!

**Comment by evanstoner** [comment]
Have you allocated the floating IP yet?

```
FloatingIP ip = os.compute().floatingIps().allocateIP(poolName);
ActionResponse r = os.compute().floatingIps().addFloatingIP(server, ip.getFloatingIpAddress());
```

**Comment by vinodborole** [comment]
@mqh123456  closing this issue for now, please reopen if the issue still exists
