### ISSUE TITLE
how to extends the size of a specified volume to a new size 

### ISSUE THREAD

**Issue by CyrusKang** [ContainX/openstack4j#435]

**Comment by pompinis** [comment]
Current implementation not supporting volume extension. For extending volume we need new commands:
https://github.com/gondor/openstack4j/pull/436

Whit these new comands volume extension is easy:
shut-down machine
set volume status to "Available"
change volume size to new bigger size, reducing size is not allowed
set volume status to "In-Use"
run machine

**Comment by vinodborole** [comment]
fixed in #436
