### ISSUE TITLE
How to add Script  to an instance when creating it?

### ISSUE THREAD

**Issue by 694982827** [ContainX/openstack4j#442]
for example I want to create an instance with an admin password "mypassword";
and there are the scripts:
#!/bin/sh
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
service ssh restart

ServerCreate sc = Builders.server()
                .name("instanceName")
                .flavor("3")
                .image("6c575333-527c-483b-b449-c496be26d368")//centos
                .addAdminPass("mypassword")
                .networks(networks)
                .build();
Server server = os.compute().servers().boot(sc);

How to use it when creating?

**Comment by abareghi** [comment]
You can convert the content of your bash script to Base64 encoding and pass it to instance when creating it:
 **String bashScriptContent = Base64(your-bash-script-content);**
 ServerCreate sc = Builders.server()
.name("instanceName")
.flavor("3")
.image("6c575333-527c-483b-b449-c496be26d368")//centos
.addAdminPass("mypassword")
**.userData(bashScriptContent)**
.networks(networks)
.build();
Server server = os.compute().servers().boot(sc);

This works with metadata server AFAIK.

FYI, You can directly inject you ssh key to the created machine. You don't need to pass a default password.

**Comment by 694982827** [comment]
Are  these scripts  able to use in windows imgae?

**Comment by abareghi** [comment]
I never don't have experience with windows images.
But for linux images with cloud-init installed, this userData is fetched from openstack metadata server (this is the configuration I used). 
I assume that windows also has a tool similar to cloud-init. But make sure your windows image includes it.

**Comment by doronbl** [comment]
I'm failing to perform the same operation. Few questions:
1) Does the user data should be a valid script, i.e. #!/bin/bash ..... or only the command lines within the script, for example /bin/bash -c '...'? To be more clear, does userdata is executed as an executable script?
2) In the above comment you mentioned 'openstack metadata server' is it a server that needs to be up and running in order for the userdata to work? How do I validate I have the required userdata prerequests?
3) Well, it is not working for me now. Where do i find logs that can tell me what went wrong?

Thank you

**Comment by vinodborole** [comment]
please reopen if this issue still exists
