### ISSUE TITLE
Accessing NovaServer clild Objects (Image, Flavor, etc.)

### ISSUE THREAD

**Issue by dcolcott76** [ContainX/openstack4j#443]
Hi There,
I am having problems accessing child objects such as Image, Flavor, etc from a NovaServer object.
I have a class specific for making calls to the openstack server with methods like getServers(), getFlavors(), etc. All seems to work but when I get the array of NovaServers to one of the UI components to display in a list with a onClick action they should use server.getImage() or server.getFlavor to list the details of the clicked server object but I get the Exception at the bottom.

From a bit of Googling I found: http://www.openstack4j.com/learn/threads/
Which explains that I need to pass the Access object of the client which I suspect is my problem. 
That is, the getImage() method actually calls the Openstack server, its not cached or provided with the NovaServer object itself. 

The problem is when I call server.getImage() there is no option to pass the Access object. 

Any one able to shed some light on how to access server.getImage() when the original server object has been passed between classes itself?

 java.lang.NullPointerException
    at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:84)
    at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:79)
    at org.openstack4j.openstack.internal.BaseOpenStackService.get(BaseOpenStackService.java:46)
    at org.openstack4j.openstack.compute.internal.ComputeImageServiceImpl.get(ComputeImageServiceImpl.java:45)
    at org.openstack4j.openstack.compute.domain.NovaServer.getImage(NovaServer.java:121)

**Comment by gondor** [comment]
Have you tried using the "detailed" flag on getting a list of servers?  This should pull in the extra info into each server object.

```
List<? extends Servers> servers = os.compute().servers().list(true);
```

**Comment by vinodborole** [comment]
@dcolcott76  please close this issue if u are satisfied with the answer
