### ISSUE TITLE
Quotaset folating ip number is not correct

### ISSUE THREAD

**Issue by riscopenstack** [ContainX/openstack4j#449]
Hi,
I get the floating ip quota of a project by QuotaSet quota =  fc.compute().quotaSets().get(projectId);
When I print out the number of quota.getFloatingIps(),the number is not the same with the number on Horizon.
The number of floating ip quota is 250 on Horizon, but the number got by openstack4j  is 10.
Does anyone encounter the same problem?

**Comment by abareghi** [comment]
Hi,
   AFAIK, floatingIp quota is managed by Neutron and that's what Horizon shows.
   Use fc.networking().quotas().get(projectId) instead.

**Comment by vinodborole** [comment]
@riscopenstack closing this for now, please reopen if this issue still exists
