### ISSUE TITLE
Setting resource limits for a flavor

### ISSUE THREAD

**Issue by krishnaprasad-narayanan** [ContainX/openstack4j#456]
Hello all,

I am new to OpenStack4j. I have a requirement where I have to specify the resource limits during the creation of a VM. For example: CPU limit, CPU period, disk I/O options and etc. I am looking for an interface that looks similar to the one in the URL: http://docs.openstack.org/admin-guide-cloud/compute-flavors.html. I searched the OpenStack4j especially the interfaces related to "Flavor" and "FlavorService" but could not find one. 

I am currently using the following library: openstack4j-2.0.3-withdeps.jar. May I know does this version support this requirement? If yes, can I know the suitable interfaces that I have to use in order to use this feature?

Regards,
Krishnaprasad

**Comment by iviireczech** [comment]
Hello,
this can be achieved by creating extra specs on flavor. 

Nova client example:
```bash
$ nova flavor-key m1.low_cpu set quota:cpu_quota=10000
$ nova flavor-key m1.low_cpu set quota:cpu_period=20000 
```
OpenStack4j equivalent:
```java
final Map<String, String> spec = new HashMap<>();
spec.put("quota:cpu_quota", "10000");
spec.put("quota:cpu_period", "20000");

osClient
             .compute()
             .flavors()
             .createAndUpdateExtraSpecs("m1.low_cpu_id", spec);
```

**Comment by vinodborole** [comment]
@krishnaprasad-narayanan please reopen if this issue still exists
