### ISSUE TITLE
Instance password on Windows from .pem

### ISSUE THREAD

**Issue by elenamarkoska** [ContainX/openstack4j#465]
I've launched a Windows VM in OpenStack, however I'm having troubles connecting to it.
The security rules for my security group are set so that RDP is enabled. I realise my username is Administrator and I have the .pem key for my keypair name.

However, how would I go about extracting a password for a windows instance from a .pem using the openstack4j API?

**Comment by 694982827** [comment]
Look at this:http://liuxin.lxliu.cn/blog/articles/2015/10/14/1444832092835.html#b3_solo_h4_1
use the passeord whitch openstack4j gets and decode it with your pem.

**Comment by vinodborole** [comment]
@elenamarkoska please reopen if this issue still exists for u
