### ISSUE TITLE
JSON is deserialized haphazardly

### ISSUE THREAD

**Issue by rski** [ContainX/openstack4j#478]
For example in  ```core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneTokenV3.java```:

```
public class KeystoneTokenV3 implements TokenV3 {

    private static final long serialVersionUID = 1L; 

    @JsonProperty("id")
    public String id; 
    @JsonProperty("expires_at")
    private Date expires;
    @JsonProperty("issued_at")
    private Date issued;
    @JsonProperty("methods")
    private List<String> methods;

    @JsonProperty("roles")
    List<KeystoneRoleV3> roles;
    @JsonProperty("project")
    private KeystoneProjectV3 project;
    @JsonProperty("user")
    private KeystoneUserV3 user;

    @JsonProperty
    private List<KeystoneCatalog> catalog;

```

*catalog* is deserialized, but there are no checks whether it is null or not. Openstack might respond with json that does not include "catalog", leaving it null. As a result, some things fail with a completely unhelpful message. For example, having this somewhere in the code:

```
os.getSupportedServices()
```

will result in:

```
Exception in thread "main" java.lang.NullPointerException
at org.openstack4j.openstack.identity.domain.v3.AccessWrapper.getServiceCatalog(AccessWrapper.java:61)
at org.openstack4j.openstack.internal.OSClientSession.getSupportedServices(OSClientSession.java:109)
[etc]
````

This specific example happens because in AccessWrappers this code exists:

```
List<? extends Catalog> catalogs = this.token.getCatalog();
List<Service> services = new ArrayList<Service>(catalogs.size());
```

which calls .size() on a null catalog list.

Ideally some kind null checking should happen and respond with a helpful message instead of a nullPointerException being thrown. 

Also, I am not sure, but null pointer crashes due to unexpected json input will probably affect more than TokenV3

**Comment by vinodborole** [comment]
@rski please reopen if this issue still exists for u
