### ISSUE TITLE
os.identity().users().list() return a empty list

### ISSUE THREAD

**Issue by yingwail** [ContainX/openstack4j#484]
My openstack version is kilo and there are a few users created using the Web GUI. However, I can only get a empty users list with the following code. Is there any problem with openstack? My openstack version is 2.0.6.

		OSClient os = OSFactory.builderV3()                       .endpoint("http://172.20.4.195:5000/v3").credentials("bb50ab5d331c4f4aa307e0fc6f4f8e8c","redhat")
		                       .authenticate();
		
// Find all Users
UserService userService = os.identity().users();
List<? extends User> users = userService.list();

**Comment by auhlig** [comment]
Hi @yingwail,
Sorry for the late response. Maybe in the meantime you figured out how to do it yourself.

**Comment by vinodborole** [comment]
@yingwail plesae reopen if this issue still exists for u
