### ISSUE TITLE
Cannot add ephemeral disk with os.compute().flavors().create();

### ISSUE THREAD

**Issue by yingwail** [ContainX/openstack4j#514]
Hi Gondor,

I tried to use the os.compute().flavors().create("name", ram, vcpus, disk, ephemeral, swap, rxtxFactor, isPublic) method to create a flavor. But seems the ephemeral parameter is not functioning.

The HTTP log shows "OS-FLV-EXT-DATA:ephemeral" : 0 no matter what the ephemeral parameter is.
Would you please help to check it out?

Regards,
Ray

**Comment by vinodborole** [comment]
@yingwail please reopen if this issue still exists
