### ISSUE TITLE
os-quota-sets URI has the project id twice. (v3_collaboration)

### ISSUE THREAD

**Issue by kareez** [ContainX/openstack4j#519]
The generated URI for "os-quota-sets" in **v3_collaboration** brnach is having the project id twice:
```
http://<host>:<port>/v2/<project id>/os-quota-sets/<project id>
```
**icehouse** and **kilo** are ignoring the second project id but I am not sure if it is the same for other releases. 

to reproduce:
```java
os.compute().quotaSets().updateForTenant(<project id>, <quota set>)
```

**Comment by vinodborole** [comment]
@kareez please reopen if this issue still exists, v3 branch has been merged to master now.
