### ISSUE TITLE
domain user list

### ISSUE THREAD

**Issue by CyrusKang** [ContainX/openstack4j#520]
get user list use identityService.users().list()
These users are domain default，

but Authentication is the domain xxx.com
Identifier domainIdentifier = Identifier.byName("xxx.com");
		Identifier projectIdentifier = Identifier.byName("xxx");
		OSClient os = OSFactory.builderV3()
		                       .endpoint("http://192.168.21.11:5000/v3")
		                       .credentials("xxxx","123456", domainIdentifier)
		                       .scopeToProject(projectIdentifier, domainIdentifier)	
		                       //.scopeToDomain(domainIdentifier)
		                       .perspective(Facing.ADMIN)
		                       .authenticate(); 

how to list the domain ‘xxx.com’ users

**Comment by auhlig** [comment]
Hi @CyrusKang,
For now OpenStack4j's Identity V3 support is limited to authentication.

As you can see in the issues and on our development branch we're currently working on adding more support.

**Comment by babyachievement** [comment]
@auhlig ,I also have a problem. When I try "os.identity().users().list().size(), it returns 0.
here is my code
```
OSClient os = OSFactory.builder()
                .endpoint("http://10.0.0.69:5000/v2.0")
                .credentials("admin","openstack")
                .tenantName("admin")
                .authenticate();

		System.out.println(os.identity().users().list().size());
```
Openstack: liberty
Java:1.7
OpenStack4j:2.0.9

**Comment by vinodborole** [comment]
Same for me with openstack4j 2.10; here is the log in debug mode for the above code from @babyachievement 

         Mar 18, 2016 2:59:23 PM org.glassfish.jersey.filter.LoggingFilter log
         INFO: 1 * Sending client request on thread main
         1 > GET https://10.30.20.32:5000/v2.0/users
         1 > Accept: application/json
         1 > User-Agent: OpenStack4j / OpenStack Client
         1 > X-Auth-Token: 2fb032f1c4ad4fb694b07bd415612605

          Mar 18, 2016 2:59:24 PM org.glassfish.jersey.filter.LoggingFilter log
          INFO: 2 * Client response received on thread main
          2 < 404
          2 < Content-Length: 93
          2 < Content-Type: application/json
          2 < Date: Fri, 18 Mar 2016 09:29:24 GMT,Fri, 18 Mar 2016 09:29:24 GMT
          2 < Server: Jetty(9.2.z-SNAPSHOT)
          2 < Vary: X-Auth-Token
          2 < Via: 1.1 Repose (Repose/7.1.4.0)
          2 < x-trans-id: 8c6210ef-d35d-4f9c-81d0-8e1183a25084
          {"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

**Comment by vinodborole** [comment]
please reopen if this issue still exists for anyone else
