### ISSUE TITLE
Upgrades of 3rd party dependencies

### ISSUE THREAD

**Issue by jhiemer** [ContainX/openstack4j#523]
Are there any plans to upgrade to Jackson 2.6 and Jersey 2.11+?

Explicitly Jersey seems to be a problem regarding a shift from 2.10 to 2.11:

http://stackoverflow.com/questions/18574145/nosuchmethoderror-multivaluedmap-addall-in-jersey-client

**Comment by vinodborole** [comment]
this is there in latest release
