### ISSUE TITLE
Listing regions for Service endpoints throws 404 error

### ISSUE THREAD

**Issue by vinodborole** [ContainX/openstack4j#526]
Listing regions with non-admin user gives below error. 

Code:  

              final OSClient os = OSFactory.builder().endpoint(serverUrl).credentials(username1, credential).tenantName(tenant).useNonStrictSSLClient(true).authenticate();
           System.out.println("listing endpoints");
            List<? extends ServiceEndpoint> ls1=sms.listEndpoints();
            for(ServiceEndpoint s : ls1){
            System.out.println(s.getRegion()+","+ s.getId());
           }

Error:

       "{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}"

**Comment by dhague** [comment]
Could you capture a trace of the HTTP calls made, for example using a logging proxy such as Charles? (www.charlesproxy.com)
My immediate suspicion is that the request from OpenStack4J is OK, and the 404 is the response from your OpenStack deployment for an unauthorised call, but a trace of the HTTP traffic would help to confirm or deny this.

**Comment by vinodborole** [comment]
Here is the debug output





        2015/12/03 15:02:51:849 IST [DEBUG] RequestAddCookies - CookieSpec selected: best-match
        2015/12/03 15:02:51:849 IST [DEBUG] RequestAuthCache - Auth cache not set in the context
        2015/12/03 15:02:51:849 IST [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://10.10.1.1:5000][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
        2015/12/03 15:02:51:849 IST [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {s}->https://10.10.1.1:5000][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
         2015/12/03 15:02:51:849 IST [DEBUG] MainClientExec - Opening connection {s}->https://10.10.1.1:5000
         2015/12/03 15:02:51:850 IST [DEBUG] HttpClientConnectionOperator - Connecting to 10.10.1.1/128.107.7.5:5000
             2015/12/03 15:02:52:457 IST [DEBUG] HttpClientConnectionOperator - Connection established 10.107.19.249:58430<->128.107.7.5:5000
           2015/12/03 15:02:52:457 IST [DEBUG] MainClientExec - Executing request GET /v2.0/endpoints HTTP/1.1
            2015/12/03 15:02:52:457 IST [DEBUG] MainClientExec - Target auth state: UNCHALLENGED
              2015/12/03 15:02:52:457 IST [DEBUG] MainClientExec - Proxy auth state: UNCHALLENGED
           2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> GET /v2.0/endpoints HTTP/1.1
            2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> Accept: application/json; charset=utf-8
         2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> User-Agent: OpenStack4j / OpenStack Client
                2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> X-Auth-Token: b1f5fa3c8e654c958883e7a6746d29b1
               2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> Host: 10.10.1.1:5000
            2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> Connection: Keep-Alive
              2015/12/03 15:02:52:457 IST [DEBUG] headers - http-outgoing-1 >> Accept-Encoding: gzip,deflate
            2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "GET /v2.0/endpoints HTTP/1.1[\r][\n]"
          2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "Accept: application/json; charset=utf-8[\r][\n]"
            2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "User-Agent: OpenStack4j / OpenStack Client[\r][\n]"
             2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "X-Auth-Token: b1f5fa3c8e654c958883e7a6746d29b1[\r][\n]"
           2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "Host: 10.10.1.1:5000[\r][\n]"
            2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
               2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
             2015/12/03 15:02:52:457 IST [DEBUG] wire - http-outgoing-1 >> "[\r][\n]"
             2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "HTTP/1.1 404 Not Found[\r][\n]"
               2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Date: Thu, 03 Dec 2015 09:32:52 GMT[\r][\n]"
               2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Via: 1.1 Repose (Repose/7.1.4.0)[\r][\n]"
               2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Vary: X-Auth-Token[\r][\n]"
                2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Date: Thu, 03 Dec 2015 09:32:52 GMT[\r][\n]"
                2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "x-trans-id: 8b45e3b8-8c85-4600-9155-b3dbb235d3be[\r][\n]"
                 2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Content-Type: application/json[\r][\n]"
                 2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Content-Length: 93[\r][\n]"
                 2015/12/03 15:02:52:763 IST [DEBUG] wire - http-outgoing-1 << "Server: Jetty(9.2.z-SNAPSHOT)[\r][\n]"
           2015/12/03 15:02:52:764 IST [DEBUG] wire - http-outgoing-1 << "[\r][\n]"
           2015/12/03 15:02:52:764 IST [DEBUG] wire - http-outgoing-1 << "{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}"
           2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << HTTP/1.1 404 Not Found
           2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Date: Thu, 03 Dec 2015 09:32:52 GMT
              2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Via: 1.1 Repose (Repose/7.1.4.0)
              2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Vary: X-Auth-Token
               2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Date: Thu, 03 Dec  2015 09:32:52 GMT
             2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << x-trans-id: 8b45e3b8-8c85-4600-9155-b3dbb235d3be
             2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Content-Type: application/json
           2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Content-Length: 93
            2015/12/03 15:02:52:764 IST [DEBUG] headers - http-outgoing-1 << Server: Jetty(9.2.z-SNAPSHOT)
           2015/12/03 15:02:52:764 IST [DEBUG] MainClientExec - Connection can be kept alive indefinitely
            2015/12/03 15:02:52:764 IST [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-1: Shutdown connection
            2015/12/03 15:02:52:765 IST [DEBUG] MainClientExec - Connection discarded
                2015/12/03 15:02:52:765 IST [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-1: Close connection
              2015/12/03 15:02:52:765 IST [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {s}->https://10.10.1.1:5000][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]

**Comment by dhague** [comment]
OK, the 404 results from a call to GET /v2.0/endpoints

According to http://developer.openstack.org/api-ref-identity-v2-ext.html#os-kscatalog-ext, the call should be to /v2.0/tenants/​{tenantId}​/OS-KSCATALOG/endpoints

So it looks like the tenant part is somehow being lost.

In the code above, you have ```final OSClient os = ...``` followed by ```List<? extends ServiceEndpoint> ls1=sms.listEndpoints();```

Where is ```sms``` coming from?

**Comment by vinodborole** [comment]
sms is coming from

     ServiceManagerService sms=os.identity().services();
