### ISSUE TITLE
SwiftClient for Ceph

### ISSUE THREAD

**Issue by erivni** [ContainX/openstack4j#542]
Hi,

We have an Openstack environment where Swift is based on Ceph.
We're trying to upload a file with objectStorage API but nothing happens.
The container was created successfully, but the file wasn't uploaded.

We're using the following code:

os.objectStorage().containers().create("myContainer",
		CreateUpdateContainerOptions.create().accessAnybodyRead().accessWrite("Public"));
	
String etag = os.objectStorage().objects().put("myContainer", "myObject", Payloads.create(new File("myFile.xml")));

We had an old environment which wasn't based on Ceph and this code worked fine.
Please advise.

Thanks,
Einav

**Comment by gschukin** [comment]
Your code looks fine.

You should take a look at server response. If you are using httpclient connector you can set org.apache.http.headers and org.apache.http.wire logging to debug level to see server output.

**Comment by vinodborole** [comment]
@erivni please reopen if this issue still exists for u
