### ISSUE TITLE
Create new server with specified volume type in block device mapping

### ISSUE THREAD

**Issue by eveknow** [ContainX/openstack4j#552]
Hi all.

I try to use openstack4j to create new server with volume type.
<code>
OSClient osClient = getOpsClient(projectId);
        BlockDeviceMappingBuilder blockDeviceMappingBuilder = Builders
                .blockDeviceMapping().destinationType(BDMDestType.VOLUME)
                .sourceType(BDMSourceType.IMAGE)
                .uuid("ce759d31-c4eb-480c-ad8a-a36c555faae4")
                .deviceName("/dev/vda")
                .volumeSize(2)
                .deleteOnTermination(true)
                .bootIndex(0);
        List<String> networks = Arrays.asList("e9c20543-7f3d-4639-a053-aa6fdcd1fcad");
        ServerCreateBuilder scBuilder = Builders.server()
                .name("thanhtkhostname")
                .availabilityZone("nova")
                .flavor("5")
                .networks(networks)
                .blockDevice(blockDeviceMappingBuilder.build());
        ServerCreate sc = scBuilder.build();
        Server server = osClient.compute().servers().boot(sc);
</code>

But i can't find any option to choose volume type when creating block device mapping volume from image. Is this option not implemented in this 2.0.9 version?
Thanks for all.

**Comment by tangguochang** [comment]
hi eveknow ,
I hava the same question.
how do you solve this?

**Comment by eveknow** [comment]
> hi @eveknow ,
> I hava the same question.
> how do you solve this?

I have to change our workflow. We create volume first, then Server.

**Comment by berlinsaint** [comment]
i think we should reopen this issue,  bdm already  support  volumetype https://docs.openstack.org/nova/latest/user/block-device-mapping.html

**Comment by berlinsaint** [comment]
> > hi @eveknow ,
> > I hava the same question.
> > how do you solve this?
> 
> I have to change our workflow. We create volume first, then Server.

this workflow is indeed ok， but we should control on clientside， you first should make the volume avaliable thn boot from it， not very elegant
