### ISSUE TITLE
Switch to slf4j as only logging implementation

### ISSUE THREAD

**Issue by gschukin** [ContainX/openstack4j#556]
Slf4j is now a de-facto logging facade. Allowing users to choose logging implementation on their own.

Also log4j reach EOL and there will be no more updates, making log4j plugin obsolete.

@gondor let me know if these looks reasonable to you and I'll submit PR.

**Comment by gondor** [comment]
I'm ok with this change.  Feel free to submit a PR.

**Comment by auhlig** [comment]
Closing issue as this was done in #632
