### ISSUE TITLE
Problem with getting specific tenant by ID

### ISSUE THREAD

**Issue by koztom** [ContainX/openstack4j#578]
Hi,
It looks like, that get() method from TenantService (org.openstack4j.api.identity package) doesn't work.
I get null object every time - I'm sure I'm passing correct id. In other hand getting tenant by name works fine, I don't have problem with list() method also.
Library version I have is 2.0.9.

**Comment by vinodborole** [comment]
@koztom please reopen if this issue still exists for u

**Comment by evgenyfedoruk** [comment]
Have the same problem.
Here is my code:
`List<Tenant> tenants = os.identity().tenants().list();
// Returns list of tenants as I expect.
Iterator<Tenant> tenant_iter = tenants.iterator()
KeystoneTenant tenant
					while(tenant_iter.hasNext()) {
						tenant = (tenant_iter.next())
                                      Tenant t = os.identity().tenants().get(tenant.getId());
// returns null for all tenants in the list
`
