### ISSUE TITLE
how to get securitygroups of a server?

### ISSUE THREAD

**Issue by ustbxyls** [ContainX/openstack4j#633]
hi,
in the class, org.openstack4j.openstack.compute.domain.NovaServer
i found that code about securitygroups  is not in-use, 
like  
//	@JsonProperty("security_groups")
//	private List<SecurityGroup> securityGroups;
i want to know why?

**Comment by vinodborole** [comment]
@ustbxyls you can use the branch shared which has the fix

**Comment by ustbxyls** [comment]
@vinodborole your code have not been merged into the latest 2.20-SNAPSHOT, which branch i should use??

**Comment by vinodborole** [comment]
https://github.com/vinodborole/openstack4j/tree/%23633

**Comment by vinodborole** [comment]
@gondor do u think the pull request is valid to be merged in?

**Comment by gondor** [comment]
Same comment applies as PR #644
