### ISSUE TITLE
Keystone V3 API endpoints not supported

### ISSUE THREAD

**Issue by bogiva** [ContainX/openstack4j#634]
Hi,

We have a setup with both Keystone V2 and V3 API enabled.
When trying to connect with V3 authentication - the connection is successful but we cannot get access to the V3 API endpoint.

What is the rationale behind this code in the resolveV3 method?

`    private String resolveV3(URLResolverParams p) {
        Token token = p.access.unwrap();
        if (p.perspective == null)
            p.perspective = Facing.PUBLIC;

        for (Catalog catalog : token.getCatalog()) {
            if (p.type == ServiceType.forName(catalog.getType())) 
            {
                for (org.openstack4j.model.identity.v3.Endpoint ep : catalog.getEndpoints()) {
                    // Since we only support V3 authentication - skip a V3 URL
                    if (matches(ep, p) && !isEndpointV3(ep.getUrl())) {
                        return ep.getUrl().toString();
                    }
                }
            }
        }
        return null;
    }
`
Why would the V3 endpoint be skipped? This prevents us from using V3 endpoint in environments with both V2 and V3 enabled APIs.

Thanks in advance!

**Comment by gschukin** [comment]
Yep. You have to wait for V3 implementation. Or build library from v3 branch yourself.

**Comment by vinodborole** [comment]
v3 implementation is part of the latest release now, hence closing this issue
