### ISSUE TITLE
Get/set project (tenant) properties

### ISSUE THREAD

**Issue by sambenz** [ContainX/openstack4j#639]
Newer versions of OpenStack support an additional field (properties) for a tenant.

$ openstack project show abc
+-------------+--------------------------------------------+
| Field       | Value                                      |
+-------------+--------------------------------------------+
| description | ABC  |
| enabled     | True                                       |
| id          | 23xxxxxxxca7           |
| name        | abc                        |
| properties  |                                            |
+-------------+--------------------------------------------+

It would be nice if this library could set and get this field.

**Comment by vinodborole** [comment]
@sambenz  the documentation does not have that yet; may be that is the reason why the library does not support it

http://developer.openstack.org/api-ref-identity-v2.html#GET_listTenants_v2.0_tenants_Tenant_Operations-Response

**Comment by sambenz** [comment]
@vinodborole Thanks for clarifying this. In fact, seems to be an undocumented feature.

**Comment by vinodborole** [comment]
@sambenz  Let me know if you want to have this feature, i can write it and share the branch

**Comment by sambenz** [comment]
@vinodborole Thanks a lot for your offer. But let our code depend on undocumented features is maybe not a good advice.

**Comment by auhlig** [comment]
Closing since the it's undocumented and Identity V2 is deprecated anyway
