### ISSUE TITLE
Why getEndpoints function in ServiceWrapper class just return an empty list?

### ISSUE THREAD

**Issue by bonyz** [ContainX/openstack4j#641]
I found that getEndpoints() in ServiceWrapper.class, this funciton just return an empty list.
Is that should be return return this.catalog's Endpoints ? 
can anyone tell me ?

**Comment by bonyz** [comment]
AccessWrapper$ServiceWrapper

**Comment by vinodborole** [comment]
@bonyz wait for v3 implementation; or you can refer to this branch https://github.com/gondor/openstack4j/blob/v3_collaboration

**Comment by bonyz** [comment]
tks

**Comment by vinodborole** [comment]
v3 is in the latest release now
