### ISSUE TITLE
Back-end storage pools api implemetation in openstack4j

### ISSUE THREAD

**Issue by kushalagrawal** [ContainX/openstack4j#646]
How can i access below api provided in openstack documentation using openstack4j. 

http://developer.openstack.org/api-ref-blockstorage-v2.html#listPools

![image](https://cloud.githubusercontent.com/assets/2899513/14952644/a4c88ef0-107f-11e6-9137-15fe3e7caad8.png)

**Comment by vinodborole** [comment]
@kushalagrawal 

      List<? extends BackendStoragePool> pools = os().share().schedulerStats().pools();

**Comment by kushalagrawal** [comment]
Thanks @vinodborole I tried using this api but i am not getting any data from openstack with this.
probably the reason is if we see implemetation url for the api is different from what openstack has defined. 

`get(ManilaBackendStoragePool.BackendStoragePools.class, uri("/pools" +  (detail ? "/detail" : "")))`

> while api url in openstack is "/v2/​{tenant_id}​/scheduler-stats/get_pools"

**Comment by gf-chen40** [comment]
_List<? extends BackendStoragePool> pools = os().share().schedulerStats().pools();_
This is a manila interface, but @kushalagrawal need a cinder interface of get_pools.
#762 here I write the code and waiting for reply. After that you can use cinder get_pools interface.

**Comment by easyit** [comment]
os.blockStorage().schedulerStatsPools().pools()

**Comment by vinodborole** [comment]
@gf-chen40 Thnx, can you help us with a short documentation around this

**Comment by kushalagrawal** [comment]
Thanks @gf-chen40. I am closing this bug. based on [#762](https://github.com/ContainX/openstack4j/issues/762)
