### ISSUE TITLE
cannot get server's image info when server's status is error

### ISSUE THREAD

**Issue by guluglu** [ContainX/openstack4j#652]
when server's status is error, I test server.getImage() but got null.And I test openstack native api, return image field is null:
{
    "server":{
        "OS-EXT-STS:task_state":null,
        "addresses":Object{...},
        "links":Array[2],
        "image":"",
but it store image info in system_metadata section like:

"system_metadata":{
            "image_architecture":"x86_64",
            "instance_type_name":"1C1G0G",
            "snapshot_id":null,
            "image_min_ram":"0",
            "image_os_distro":"cirros",

but it seems that openstack4j does not store this field in server infomation

**Comment by vinodborole** [comment]
@guluglu  Use server.getMetadata()

**Comment by vinodborole** [comment]
@guluglu please reopen if its still valid for u
