### ISSUE TITLE
cannot get Tenants , or project 

### ISSUE THREAD

**Issue by huytt1992** [ContainX/openstack4j#653]
I test Creating Tenant but got null.And I test Querying for Tenants return image is null:

Tenant tenant = os.identity().tenants()
                  .create(Builders().tenant().name("ABC Corp").description("ABC Corporation Tenant").build());

List<? extends Tenant> tenants = os.identity().tenants().list();.

 when I'm on server i see is the Project.
i know project as Tenant.
i want to get Projectid and information project.

how to get Object Project. or tenant?

Please , help me, thank you so much

**Comment by vinodborole** [comment]
@huytt1992  please close this if its no longer valid
