### ISSUE TITLE
The server's host is null which is return by the api"ServerServiceImpl.get(id)"

### ISSUE THREAD

**Issue by dreadbird** [ContainX/openstack4j#656]
I want to get the server's host info,but when I use the api "ServerServiceImpl.get(id)" to get the server object as fllow:
`org.openstack4j.model.compute.Server server = getOsClient().compute().servers().get(serverId);`
the attribute [host] is null.
I request the openstack rest api "http://10.110.17.19:8774/v2/4abdea8658364e2097a4a7917196c14a/servers/53c3bbc2-2b2d-47f0-8613-2c1eb355cad5" directly,can get the value as fllow:
`"OS-EXT-SRV-ATTR:host": "allInOne19"`

**Comment by vinodborole** [comment]
It works for me, below is the code


    private static void listServers(OSClient client) {
        List<? extends Server> servers=client.compute().servers().list();        
        if(servers!=null && !servers.isEmpty()){
            for(Server s : servers){
                System.out.println(s.getHost());
            }
        }
    }

**Comment by dreadbird** [comment]
Thanks for you replay.I will pull the new code to try again.

**Comment by dreadbird** [comment]
I have find the problem.I use a tenant which is not a administrator.
But the server's host info can be get by the administrator only.
In the openstack api site,the description is 

> This query parameter is typically available to only administrative users. If you are a non-administrative user, the API ignores this parameter.
