### ISSUE TITLE
cannot create server 

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#660]
OSClient os = oSClientService.getV2OSClientAdmin(token, tenant);//auth
List<? extends Server> serverList = os.compute().servers().list();
//org.openstack4j.api.exceptions.ClientResponseException: Server name is not defined

//request
{
    "name": "wumingcheng-server",
    "imageRef": "3937832b-f780-4181-a9ee-8615bfe3e358",
    "flavorRef": "337fe28b-5505-4f0d-8042-117f0c2af186",
    "networks": [
        {
            "uuid": "828dad7c-ece5-42b0-9ac1-18393cbe3c73",
            "port": "6045009a-9b25-470b-b685-a9e763ce0f77",
            "fixed_ip": "192.168.0.2"
        }
    ]
}

Why the server name need to define, I just create a server?

**Comment by vinodborole** [comment]
Name is required to create a server

http://developer.openstack.org/api-ref-compute-v2.1.html
