### ISSUE TITLE
Search API Access?

### ISSUE THREAD

**Issue by huytt1992** [ContainX/openstack4j#665]
I tried searching on http://openstack4j.com/learn and http://developer.openstack.org/api-ref-compute-v2.1.html
but I did not find API this.

![capture](https://cloud.githubusercontent.com/assets/19186519/15236170/67bf2a08-18ec-11e6-907f-c02e504854e1.PNG)

please help me, thank you so much!

**Comment by vinodborole** [comment]
@huytt1992 closing this for now, please reopen if it still exists
