### ISSUE TITLE
3.0.0 version cannot create V2 tenant

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#666]
when I want to create a v2 tenant ,the "Builders.tenant()" was missing.

**Comment by auhlig** [comment]
@wumingcheng Thanks for pointing that out.
I'll fix that and add some integration-tests next week.
As a workaround for the meantime you could use the KeystoneTenant.builder()  directly.

**Comment by gondor** [comment]
New 3.0.1-SNAPSHOT has been pushed

**Comment by auhlig** [comment]
Looking at the Builders I think it makes sense to also divide by Identity version. So it would be clear which Role, User, etc. is being built or that a Group is not available when using v2.
So I would create a BuilderV2  for identity v2 and a BuilderV3 for id v3 which extends the current Builder-implementation.
That would follow the pattern used in the OSClient, OSClientSession, .. .

Does this make sense @gondor, @dhague ?

**Comment by gondor** [comment]
I like that idea, will make things cleaner and allow for expansion

**Comment by dhague** [comment]
Sounds good. Technically this could introduce a breaking change in 3.0, but if we do it quickly then I think that's OK - it's not like we have a big installed base of OS4J 3.0 users yet :-)
My feeling is that if we get it out quickly as 3.0.2 (maybe even 3.1) then we should be fine.
