### ISSUE TITLE
Does openstack4j-jersey2-jdk16 version 3.0.0 exist?

### ISSUE THREAD

**Issue by seand9** [ContainX/openstack4j#667]
<dependency>
			<groupId>org.pacesys.openstack4j.connectors</groupId>
			<artifactId>openstack4j-jersey2-jdk16</artifactId>
			<version>3.0.0</version>
		</dependency>

[ERROR] Failure to find org.pacesys.openstack4j.connectors:openstack4j-jersey2-jdk16:jar:3.0.0 in http://nexus ...

**Comment by gondor** [comment]
No, version 3.0.0 has dropped support for JDK6.  You can see the release summary at : https://github.com/ContainX/openstack4j/releases/tag/3.0.0

**Comment by seand9** [comment]
Ok, thanks. FYI openstack4j-jersey2-jdk16  is still listed on http://www.openstack4j.com/learn/getting-started under
Valid artifactId's.
