### ISSUE TITLE
3.0.0 version get tenants return null.

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#668]
OSClientV2 os = OSFactory.builderV2().endpoint(configuration.getEndpoint()).token(token).tenantId(tenant)
          .perspective(Facing.ADMIN).authenticate();
Tenant tenant = os.identity().tenants().get(tenantId);

get tenants return null?

**Comment by gondor** [comment]
New 3.0.1-SNAPSHOT has been pushed

**Comment by wumingcheng** [comment]
3.0.1-SNAPSHOT also has this bug！
