### ISSUE TITLE
JKD1.7 

### ISSUE THREAD

**Issue by liu2972505** [ContainX/openstack4j#673]
my project is JDK1.7，How can i use openstack4j 3.0.0?

**Comment by auhlig** [comment]
Well, maybe that's the right place to mention @olivergondza's comment in https://groups.google.com/d/msg/openstack4j/NW22p6-XRro/J991Cm5VBwAJ .

There were particular reason to upgrade to java 8:
- Java 7 is no longer supported with updates according to https://java.com/en/download/faq/java_7.xml
- The HTTP PATCH -method used for example in Os4j's new identity v3 part when updating attributes for an already existing user, group, project, .. is known to be buggy in jdk 1.7 (at least with jersey-connector).

**Comment by olivergondza** [comment]
@auhlig, thanks for the explanation! For now, I do not need any 3.0 features and 2.0 seems maintained and still works for me so I do not feel that strongly. Though, provided there are no other reasons I would prefer I project staid with version 7 not to split the efforts between development and maintenance branch.

I rarely agree with point #1. Even it if ware supported, would oracle/openjdk project fix the problem you are referring to in #2? I personally doubt so. #2 sounds valid but how about applying the restriction only to those connectors that are affected?

**Comment by auhlig** [comment]
@olivergondza: Great idea to apply the restriction only to affected connectors! Could you investigate and submit a PR?

**Comment by olivergondza** [comment]
@auhlig, I would love to. Can you point me to the bug you have talked about?

> The HTTP PATCH -method used for example in Os4j's new identity v3 part when updating attributes for an already existing user, group, project, .. is known to be buggy in jdk 1.7 (at least with jersey-connector).

**Comment by auhlig** [comment]
Cool.

Quick summary of the problem:
https://travis-ci.org/gondor/openstack4j/jobs/129662607 shows
```
org.openstack4j.api.exceptions.ConnectionException:
java.net.ProtocolException: HTTP method PATCH doesn't support output
```
which led us to http://stackoverflow.com/questions/22355235/patch-request-using-jersey-client#22412032 and to the jdk issue https://bugs.openjdk.java.net/browse/JDK-7157360, which is not fixed in jdk1.7 but in 1.8 .

**Comment by olivergondza** [comment]
Fix proposed here: https://github.com/ContainX/openstack4j/pull/693
