### ISSUE TITLE
3.0.0 version tenants uri bug

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#677]
package org.openstack4j.core.transport.ClientConstants;
public static final String PATH_TENANTS = "/auth/tenants";

to remove the "/auth":
public static final String PATH_TENANTS = "/tenants";

**Comment by vinodborole** [comment]
@wumingcheng  this is been done; please use the snapshot version 3.0.1-SNAPSHOT

https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/core/transport/ClientConstants.java

**Comment by wumingcheng** [comment]
@vinodborole were you updated the 3.0.1-SNAPSHOT，the remote repository also has "/auth".

**Comment by vinodborole** [comment]
![clientconstant](https://cloud.githubusercontent.com/assets/3897901/15419675/65d90b34-1e85-11e6-9d58-e42e44eb2000.png)
