### ISSUE TITLE
3.0.0 version DefaultAPIProvider bug

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#679]
DefaultAPIProvider is not bind "BlockQuotaSetService"

**Comment by vinodborole** [comment]
You can access it from
`client.blockStorage().quotaSets()`

**Comment by wumingcheng** [comment]
@vinodborole I know that method,but the
DefaultAPIProvider.java is’t bind(BlockQuotaSetService.class, BlockQuotaSetServiceImpl.class);
I just got an  exception: API not found for: org.openstack4j.api.storage.BlockQuotaSetService.

**Comment by vinodborole** [comment]
@wumingcheng please share the code you are trying

**Comment by wumingcheng** [comment]
@vinodborole you can check DefaultAPIProvider.java with 3.0.0 version of os4j, it doesn't **"bind(BlockQuotaSetService.class, BlockQuotaSetServiceImpl.class)"** in **initialize()** method on DefaultAPIProvider.java ,so I just got an **ApiNotFoundException**: API not found for: org.openstack4j.api.storage.BlockQuotaSetService.

**Comment by vinodborole** [comment]
#685

**Comment by wumingcheng** [comment]
To see the CinderBlockQuotaSet.java,include snapshots,volumes and gigabytes.Why BlockQuotaSets support V2, but volume just support V1?
