### ISSUE TITLE
Creating flavor omits json with extra null fields

### ISSUE THREAD

**Issue by menihillel** [ContainX/openstack4j#682]
I'm creating a flavor and the json omitted by Openstack4J contains extra fields which are not valid for creation (see below). As a result creation fails. It seems that the POJO contains non-null values for the extra fields for some reason but they should be set to null on creation.

ClientResponseException{message=Invalid input for field/attribute flavor. Value: {u'name': u'os-chassis_TCP_1', u'ram': 4, u'OS-FLV-DISABLED:disabled': False, u'vcpus': 4, u'swap': 0, u'os-flavor-access:is_public': True, u'rxtx_factor': 1.0, u'OS-FLV-EXT-DATA:ephemeral': 0, u'disk': 50, u'public': True}. Additional properties are not allowed (u'OS-FLV-DISABLED:disabled', u'public' were unexpected), status=400, status-code=BAD_REQUEST}

**Comment by vinodborole** [comment]
#573

**Comment by menihillel** [comment]
What's the plan on fixing this? Kind of blocked when using Mitaka. Seems
like an easy fix nulling out these fields on creation. Is there a
workaround we can gain access to the POJO before submission?

**Comment by vinodborole** [comment]
@menihillel for now, you can use these changes in my branch

https://github.com/ContainX/openstack4j/compare/master...vinodborole:%23573

**Comment by vinodborole** [comment]
#686

**Comment by vinodborole** [comment]
merged
