### ISSUE TITLE
Connection timeout with openstack4j Identity Query

### ISSUE THREAD

**Issue by sendaun** [ContainX/openstack4j#691]
I am using openstack4j-3.0.0 to fetch the tenants list in my application. The authentication to the openstack goes fine, but it failes with java.connectexception "connection timed out" while trying to retrieve the tenant list using **osClient.identity().tenants().list();**

Here is how i am authenticating: 

```
			osClientInstance  = OSFactory
					.builderV2()
					.endpoint(http://xx.xx.xx.xx:5000/v2.0)
					.credentials(algorithm.decryptString(***,
							***))
					.tenantName(***)
					.authenticate();
```
Authentication goes fine.

Now while attempting to fetch tenant list, getting connection time out:

`osClient.identity().tenants().list();`

Error log:

> ConnectionException{message=Connection timed out, status=0}
>         at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
>         at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
>         at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
>         at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:193)
>         at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187)
>         at org.openstack4j.openstack.identity.v2.internal.TenantServiceImpl.list(TenantServiceImpl.java:23)
> 

**SOME ADDITIONAL INFO:**

(1) Tried with two versions of Openstack4j that i had - openstack4j-2.0.5 & openstack4j-3.0.0, but both fails with same error.

(2) Tried with two connectors - openstack4j-jersey2 & openstack4j-resteasy, both fails with same error.

(3) I am able to culr from my server to the openstack endpoint and get the response perfectly.

(4) Firewall is turned off at both the ends.

(5) I am not behind any proxy

(6) I am using SUSE OpenStack Cloud 6

Please suggest how to fix this. Thank in advance.

**Comment by wildcherrycandy** [comment]
+1. I have the same problem.

**Comment by wildcherrycandy** [comment]
I think i know what is it.
When u authenticate u have one endPoint.
After authentication successful u have another endPoint the same of "host_ip" in openstack.

**Comment by wildcherrycandy** [comment]
In my case .withConfig(org.openstack4j.core.transport.Config.newConfig().withEndpointNATResolution("XXX.XXX.XXX.XX")) solved my problem.

**Comment by vinodborole** [comment]
@sendaun please reopen if this issue still exists for u
