### ISSUE TITLE
System Test/Unit Test

### ISSUE THREAD

**Issue by paula810** [ContainX/openstack4j#692]
Hello,

I was going through your test files and it seems that mostly all the UT's created are basically related to your functionality and not much about the interaction with the cloud. Have you considered and it may happen that your functionality is correct but the cloud response is incorrect , since cloud has a number of vulnerabilities. 
Do you think a set number of Test Cases related to cloud interaction is important in this scenario

**Comment by auhlig** [comment]
duplicate of #709
