### ISSUE TITLE
3.0.1-SNAPSHOT DefaultAPIProvider bug

### ISSUE THREAD

**Issue by wumingcheng** [ContainX/openstack4j#698]
DefaultAPIProvider.java with 3.0.1-snapshot of os4j doesn't
"**bind(FirewallAsService.class, FirewallAsServiceImpl.class)
,bind(FirewallService.class, FirewallServiceImpl.class)
,bind(FirewallRuleService.class, FirewallRuleServiceImpl.class)
,bind(FirewallPolicyService.class, FirewallPolicyServiceImpl.class)**" 
in initialize() method.
Please solve it as soon as possible, thanks!

**Comment by vinodborole** [comment]
@wumingcheng  Thanks i have created a PR

#702
