### ISSUE TITLE
openstack4j.com no longer points to OpenStack4j web page

### ISSUE THREAD

**Issue by llarsson** [ContainX/openstack4j#699]
http://www.openstack4j.com/ points to the correct web page, but http://openstack4j.com/ does not (points to Netshare web page).

**Comment by westenb** [comment]
I noticed the same thing. Furthermore, when the GitHub org has been changed to ContainX, I also tried to visit the linked URL http://containx.io but I cannot resolve it. Is there some more about information about ContainX? E.g. is it a legal entity?

**Comment by vinodborole** [comment]
it does now
