### ISSUE TITLE
Fully support v2 of Telemetry API

### ISSUE THREAD

**Issue by llarsson** [ContainX/openstack4j#701]
While trying to create an obvious fix to #700, I stumbled upon further errors. It seems as if the support in OpenStack4j for [Telemetry API v2](http://developer.openstack.org/api-ref-telemetry-v2.html) is incomplete. Aside from the previously mentioned issue, the [data model](http://developer.openstack.org/api-ref-telemetry-v2.html#showSample) has changed rather significantly, referring e.g. to "meter" as opposed to "counter name".

**Comment by vinodborole** [comment]
@gondor do we want to update the existing data model with modified properties?

**Comment by gondor** [comment]
@vinodborole Yes, telemetry was probably modelled around the Havana release timeframe.  Many versions back.  As a rule we've tried to maintain support for 2-3 versions back max.

**Comment by sjpatil** [comment]
I will soon send PR for this
