### ISSUE TITLE
Warning when creating a bucket

### ISSUE THREAD

**Issue by luciasarni** [ContainX/openstack4j#703]
I´m using v2.20.0 of openstack4j and I get a warning when I create a container, it does create the container but I have no way of avoiding the warning from being printed.

I separated the line for creating a container as much as possible to find the place where the warning appears:
```

ObjectStorageService o =client.objectStorage();
ObjectStorageContainerService o1=o.containers();
CreateUpdateContainerOptions c= CreateUpdateContainerOptions.create().accessAnybodyRead();
ActionResponse r =o1.create(bucketName, c); //this is the line that prints the warning
```

client was build by doing: `client = OSFactory.builderV3()`

Is there anyway I could avoid this warning?
Thank you

**Comment by vinodborole** [comment]
@luciasarni is this the warning you are talking about

`WARNING: Entity must not be null for http method PUT.`

**Comment by luciasarni** [comment]
Yes (I totally forgot to put the warning in the message):

```
jun 01, 2016 11:10:47 AM org.glassfish.jersey.client.JerseyInvocation validateHttpMethodAndEntity
WARNING: Entity must not be null for http method PUT.
```

**Comment by vinodborole** [comment]
@luciasarni just add below line before running your code
`LogManager.getLogManager().reset();`

**Comment by luciasarni** [comment]
Thank you, it worked just fine!
