### ISSUE TITLE
openstack host information???

### ISSUE THREAD

**Issue by zeyuphoenix** [ContainX/openstack4j#716]
How should I get openstack host information, for example: the installation of openstack server IP, memory, CPU, etc.

host information is physical resources.

**Comment by sjpatil** [comment]
Your use case is not very clear but to some extent you can get information related to hosts for cpus and memory through hypervisor APIs which you can use with admin access.

**Comment by zeyuphoenix** [comment]
Thank you, I used the `os.compute().hypervisors().list() `to get a part of the host information, but not all
