### ISSUE TITLE
Reusing Openstack4J Infrastructure

### ISSUE THREAD

**Issue by menihillel** [ContainX/openstack4j#723]
I'd like to leverage Openstack4J infra to access APIs of other projects. For example, TaaS, Neutron extension for Port binding, or anything else not covered by current implementation. Short of introducing a full fledged implementation, I'd like to leverage the goodness of encapsulation, authentication, REST infrastructure. Is this doable? What's the best way to go about this?

**Comment by menihillel** [comment]
Edit title.

**Comment by vinodborole** [comment]
https://github.com/gondor/openstack4j/blob/master/CONTRIBUTING.md

**Comment by menihillel** [comment]
Aware of this. Does not help with the steep learning curve on how to add new APIs...
