### ISSUE TITLE
How can I create Instance that boot from volume?

### ISSUE THREAD

**Issue by anhdenday** [ContainX/openstack4j#73]
Dear Gondor,
Last time I've created and boot instance successfully by the way like this
ServerCreate sc = Builders.server().name("Ubuntu 2").flavor("flavorId").image("imageId").build();
Server server = os.compute().servers().boot(sc);
Now I dont want to boot from Image, I want to boot from a bootable Volume. How can I do like below?
ServerCreate sc = Builders.server().name("Ubuntu 2").flavor("flavorId"). volumes("volumeId").build();
Server server = os.compute().servers().boot(sc);
You can check in the dashboard, whenever create  an instance, at the "Instance Boot Source:" combobox you can choose "Boot from volume" :+1: 
Thanks in advanced :)

**Comment by fenggeyeyin** [comment]
How to attach 2 or 3 volumes on boot ?
