### ISSUE TITLE
Exception in thread "main" AuthenticationException{message=Unauthorized, status=401}

### ISSUE THREAD

**Issue by jianke221** [ContainX/openstack4j#741]
i,please help me,I'm new to openstack and face a question and i don't know how to solve it.

program as below 

public class Openstack4J {
	public static void main(String agrs[]){
		String domainIdentifier = "821bc14bee664077897ab4f54f029106";
		OSClientV3 os = OSFactory.builderV3()
                .endpoint("http://192.168.252.1:5000/v3")
                .credentials("admin", "secret", Identifier.byName("admin"))
                .scopeToProject(Identifier.byId(domainIdentifier))
                .authenticate();
		List<? extends SwiftContainer> containers = os.objectStorage().containers().list();
		for (SwiftContainer currentContainer : containers) {
            System.out.println(currentContainer.getName());
        }
	}
}

and i use Identity Service (Keystone) V3 ,

**Comment by auhlig** [comment]
.scopeToProject(Identifier.byId(domainIdentifier))

Simple typo: Scope to project by domain identifier?
You either want to use the projectId or scope to a domain.

**Comment by jianke221** [comment]
if i use the projectid ,what should i do?   thank you    @auhlig

**Comment by auhlig** [comment]
Take a look at the examples in the 'Authenticating' section https://github.com/ContainX/openstack4j/blob/master/README.md

**Comment by auhlig** [comment]
@jianke221: Please close if this issue is no longer valid. Thank.

**Comment by aniketpol** [comment]
What is  domainIdentifier  where can i find it?
