### ISSUE TITLE
os.identity().users().list()      return empty list

### ISSUE THREAD

**Issue by liuxiwen** [ContainX/openstack4j#742]
OSClientV3 os = OSFactory.builderV3()
				.endpoint("http://10.0.0.11:5000/v3")
				.credentials("admin", "openstack", Identifier.byId("default"))
				.scopeToProject(Identifier.byName("admin"), Identifier.byName("default"))
				.authenticate();
System.out.println(os.identity().users().list());

OpenStack: kilo
Java: 1.8
OpenStack4j: 3.0.0

**Comment by auhlig** [comment]
You're sure you want `os.objectStorage().users().list()` instead of `os.identity().users().list()` ?

**Comment by liuxiwen** [comment]
@auhlig my fault, it is os.identity().users().list()

**Comment by auhlig** [comment]
Okay. 
Did you try other identity v3 functions? Are they successful?

Might be worth to enable debug log by ```OSFactory.enableHttpLoggingFilter(true);```

**Comment by liuxiwen** [comment]
@auhlig 
I set OSFactory.enableHttpLoggingFilter(true), it still returns a empty list, and when sending request it became http://controller:5000/v2.0/users, I userd v3.
七月 11, 2016 10:39:01 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Sending client request on thread main
1 > POST http://10.0.0.11:5000/v3/auth/tokens
1 > Accept: application/json
1 > Content-Type: application/json
1 > OS4J-Auth-Command: Tokens
{
  "auth" : {
    "identity" : {
      "password" : {
        "user" : {
          "name" : "swift",
          "domain" : {
            "id" : "default"
          },
          "password" : "openstack"
        }
      },
      "methods" : [ "password" ]
    },
    "scope" : {
      "project" : {
        "name" : "service",
        "domain" : {
          "name" : "default"
        }
      }
    }
  }
}

七月 11, 2016 10:39:01 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Client response received on thread main
1 < 201
1 < Connection: Keep-Alive
1 < Content-Length: 4740
1 < Content-Type: application/json
1 < Date: Mon, 11 Jul 2016 02:41:44 GMT
1 < Keep-Alive: timeout=5, max=100
1 < Server: Apache/2.4.7 (Ubuntu)
1 < Vary: X-Auth-Token
1 < X-Distribution: Ubuntu
1 < x-openstack-request-id: req-a4394372-3343-4de2-925c-c8328b1f1470
1 < X-Subject-Token: ad37f335ddd94e2ea5a92e0b37f355b4
{"token": {"methods": ["password"], "roles": [{"id": "4cc2ecc87e504e808ddac9f3623aa5f7", "name": "admin"}], "expires_at": "2016-07-11T03:41:44.503199Z", "project": {"domain": {"id": "default", "name": "Default"}, "id": "d32de0b11aa948bf97d54e7139f5201e", "name": "service"}, "catalog": [{"endpoints": [{"region_id": "RegionOne", "url": "http://controller:9696", "region": "RegionOne", "interface": "internal", "id": "41d61d5197f746b3a65cb312d7c0d4c7"}, {"region_id": "RegionOne", "url": "http://controller:9696", "region": "RegionOne", "interface": "public", "id": "63be5baa0385405d90d959c0a4739a3a"}, {"region_id": "RegionOne", "url": "http://controller:9696", "region": "RegionOne", "interface": "admin", "id": "9e589791d9b9489eb4bd31485a826a9f"}], "type": "network", "id": "15003054978145e380253bc533610195", "name": "neutron"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:8080/v1/AUTH_d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "public", "id": "1c8fbadaeee7487086895100381e9519"}, {"region_id": "RegionOne", "url": "http://controller:8080/v1/AUTH_d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "internal", "id": "6e2e8d6fb27f479e9f5b5174d1af1ac7"}, {"region_id": "RegionOne", "url": "http://controller:8080", "region": "RegionOne", "interface": "admin", "id": "d074b2bc0280491daefeb4d7abdb3373"}], "type": "object-store", "id": "35520e7f6a5d41dcadb18ed9ed47c0a2", "name": "swift"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:9292", "region": "RegionOne", "interface": "public", "id": "03d9a69592704371a8bc13b6a2f3114a"}, {"region_id": "RegionOne", "url": "http://controller:9292", "region": "RegionOne", "interface": "internal", "id": "5a8874f7310b4728afe4e9d028a5570c"}, {"region_id": "RegionOne", "url": "http://controller:9292", "region": "RegionOne", "interface": "admin", "id": "6a0d0c25a9a7425eb24d8e9cddf34631"}], "type": "image", "id": "523cc45c31f54db3b6065d6b8e49f826", "name": "glance"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "public", "id": "2d75d9834aee4af8b5fdec895d6de806"}, {"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "internal", "id": "896b97b9e7fb46b7b61d42de7cacaead"}, {"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "admin", "id": "8c62a844363343e4ac767903c0e924df"}], "type": "volume", "id": "6cf1ceebe4a34f22a0105712bea9daa9", "name": "cinder"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:5000/v2.0", "region": "RegionOne", "interface": "public", "id": "294e094503e34a8c9c7479f5fbea5c33"}, {"region_id": "RegionOne", "url": "http://controller:5000/v2.0", "region": "RegionOne", "interface": "internal", "id": "827daacff56c475c9440f64c5967deb2"}, {"region_id": "RegionOne", "url": "http://controller:35357/v2.0", "region": "RegionOne", "interface": "admin", "id": "e6cf685d5446499199ad97348797a255"}], "type": "identity", "id": "8289cf3ca10d4fc8a74591977b54efa6", "name": "keystone"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "admin", "id": "45415f9638ee4d40a4e664ded0d8142c"}, {"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "public", "id": "8f5ebb02bc1e4ee882dc3b9b9dc6d789"}, {"region_id": "RegionOne", "url": "http://controller:8776/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "internal", "id": "996ba07671a243c09139c3395a9449cf"}], "type": "volumev2", "id": "e4d33565ed90489ab01b6cc5e1d125f4", "name": "cinderv2"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://controller:8774/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "internal", "id": "73cf148163f04d65ade667e75f558e59"}, {"region_id": "RegionOne", "url": "http://controller:8774/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "admin", "id": "bba36a70e6a247ecbf1408b485284ac0"}, {"region_id": "RegionOne", "url": "http://controller:8774/v2/d32de0b11aa948bf97d54e7139f5201e", "region": "RegionOne", "interface": "public", "id": "f2640b514f3f427db97205b3f6061a42"}], "type": "compute", "id": "f0a43724d2b041309c4f57ff8f62284a", "name": "nova"}], "extras": {}, "user": {"domain": {"id": "default", "name": "Default"}, "id": "71429664e052483aa8cd47737d3efe5c", "name": "swift"}, "audit_ids": ["NL7wesNbRWeV4QYqb3BCXQ"], "issued_at": "2016-07-11T02:41:44.503230Z"}}

七月 11, 2016 10:39:02 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Sending client request on thread main
1 > GET http://controller:5000/v2.0/users
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: ad37f335ddd94e2ea5a92e0b37f355b4

七月 11, 2016 10:39:02 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Client response received on thread main
1 < 404
1 < Connection: Keep-Alive
1 < Content-Length: 93
1 < Content-Type: application/json
1 < Date: Mon, 11 Jul 2016 02:41:44 GMT
1 < Keep-Alive: timeout=5, max=100
1 < Server: Apache/2.4.7 (Ubuntu)
1 < Vary: X-Auth-Token
1 < X-Distribution: Ubuntu
1 < x-openstack-request-id: req-9473ad70-8375-42e6-a0ec-e0b797d49314
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

[]

**Comment by auhlig** [comment]
@liuxiwen. You're using the v3 endpoint in the authentication request. But the town's catalog does only contain the identity v2 endpoint. So there's no v3 available. You need to configure that beforehand

**Comment by liuxiwen** [comment]
@auhlig Sorry, I don't know how to configure the town's catalog to make it contain the identity v3 endpoint, can you tell me how to do it specifically, thank you!
And I have another question, I changed the code into this:

OSFactory.enableHttpLoggingFilter(true);
Identifier domain = Identifier.byId("default");
Identifier project = Identifier.byName("admin");
OSClientV3 os = OSFactory.builderV3()
.endpoint("http://10.0.0.11:5000/v3")
.credentials("admin", "openstack", domain)
.scopeToProject(project, domain)
.perspective(Facing.ADMIN)
.authenticate();

I can get the users through os.identity().users().list(), but os.identity().domains().list() os.identity().projects().list() and os.identity().roles().list() still return a empty list.
If it is convenient to you, please help me, thank you!

**Comment by easyit** [comment]
Any update? I face the same issue.

**Comment by auhlig** [comment]
@easyit The last update was that it's not a fault found in os4j but in the OpenStack instance itself. You can see that there's no identity v3 service in the catalog posted above.
To be able to use it you need to configure OpenStack properly.
But I guess that's rather something fore stackoverflow than for a bug issue.
