### ISSUE TITLE
Cinder: Missing a Feature of getting backend storage info

### ISSUE THREAD

**Issue by gf-chen40** [ContainX/openstack4j#762]
Hi，
We are using openstack4j in our platform BUT I found missing a feature(interface) of getting a Cinder Volume backend storage informations .Especially our platform need to get total_capacity and free_capacity of a certain backend.

[See the openstack cinder restapi documentation](http://developer.openstack.org/api-ref-blockstorage-v2.html#listPools)
I got
**GET/v2/​{tenant_id}​/scheduler-stats/get_pools
GET/v2/​{tenant_id}​/scheduler-stats/get_pools?detail=True**
to get the backend info.

After all I just implemented the interface. I wonder why openstack4j don't have the interface for such a long time. Please let me know if openstack4j needed this interface or not. I can submit the code and make a Pull request for it

**Comment by vinodborole** [comment]
@gf-chen40 Yes please send a PR. Thanks again for your contribution :+1:

**Comment by gf-chen40** [comment]
One more question:
I compile the project failed in the master branch&3.0 release. I don't know why. So my code is written based on the 2.0-maintenance.
So should I PR to 2.0-maintenance or can you tell me why the master failed to compile~
Thanks~

**Comment by gf-chen40** [comment]
Oh, the master code seems good now.

**Comment by auhlig** [comment]
@gf-chen40 I guess the feature has been implemented and we can close the issue, right?
