### ISSUE TITLE
try to connect to openStack from webserver and get ClientResponseException{message=Target service not allowed, status=403, status-code=FORBIDDEN}

### ISSUE THREAD

**Issue by eitanElmalam** [ContainX/openstack4j#769]
we are try to connect from cloud java application to openstack environment and get error:
ClientResponseException{message=Target service not allowed, status=403, status-code=FORBIDDEN}
The code is :
OSClientV3 os = OSFactory.builderV3().endpoint(OPEN_STACK_URL)
				.credentials("admin", "devstack", domainIdentifier)
				.scopeToProject( projectIdentifier,domainIdentifier)

				.authenticate();

**Comment by vinodborole** [comment]
@eitanElmalam it seems the permissions are not enabled, check without scopeToProject

**Comment by eitanElmalam** [comment]
I check with out scopeToProject get same error.

**Comment by vinodborole** [comment]
can you check with V2 authentication?

**Comment by eitanElmalam** [comment]
I check with V2 same error.
Maybe is certificate issue or ssl certificate ??

**Comment by eitanElmalam** [comment]
Hello,

we are call with openstack4j from cloud environment so there a problem of security ..
The missing in your clode is : 
we need to secure the protocol and the port ...
Can you add it to your code to support secure schems and port 
SSLSocketFactory sslsf = null;
 		try {
 			sslsf = new SSLSocketFactory(new TrustStrategy() {

 			    public boolean isTrusted(
 			            final X509Certificate[] chain, String authType) throws CertificateException {
 			        return true;
 			    }

 			});
 		} catch (KeyManagementException | UnrecoverableKeyException
 				| NoSuchAlgorithmException | KeyStoreException e) {
 			e.printStackTrace();
 		}

 		Scheme httpsScheme = new Scheme("http", 5000, sslsf);
 		SchemeRegistry schemeRegistry = new SchemeRegistry();
 		schemeRegistry.register(httpsScheme);

 		ClientConnectionManager cm = new BasicClientConnectionManager(schemeRegistry);
 		this.httpClient = new DefaultHttpClient(cm);

**Comment by auhlig** [comment]
@eitanElmalam I guess it's easier if you do and test the change on your side and follow up with a PR.

**Comment by eitanElmalam** [comment]
Hi,

Ok no problem , but how I do it ? I see your sources in the git , I do not know how to bring it to eclipse.
Can you help me ?? please explain how I imlement the change.

**Comment by eitanElmalam** [comment]
I bring it to eclipse I got a few error like 
Description	Resource	Path	Location	Type
Project 'it-httpclient' is missing required Java project: 'openstack4j-core-integration-test'	it-httpclient		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	it-httpclient		Unknown	Java Problem
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-jar-plugin:2.6:test-jar (execution: default, phase: test-compile)	pom.xml	/it-httpclient	line 4	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-jar-plugin:2.6:test-jar (execution: default, phase: test-compile)	pom.xml	/it-jersey2	line 4	Maven Project Build Lifecycle Mapping Problem

Where I can write unit test in which package ?

**Comment by eitanElmalam** [comment]
I investigate the code , I do not know how to add the change , please help it is urgent.

**Comment by vinodborole** [comment]
@eitanElmalam  please try this approach
[TestConfigAuthenticate.txt](https://github.com/ContainX/openstack4j/files/424366/TestConfigAuthenticate.txt)

**Comment by eitanElmalam** [comment]
I try, it did not help.
The Aoutentication need to be on the HttpClient not sslContext.

**Comment by auhlig** [comment]
Hey @eitanElmalam,
If the solution discussed via IM worked please close the issue.
Else feel free to reach out to me.

**Comment by eitanElmalam** [comment]
Hi,

I did the fix and it solve the issue .
---------------------------------------------------------------------------
The fix in file - HttpClienFactory:
 private CloseableHttpClient buildClient(Config config) {
        HttpClientBuilder cb = HttpClientBuilder.create().setUserAgent(USER_AGENT);

        SSLSocketFactory sslsf = null;
 		try {
 			sslsf = new SSLSocketFactory(new TrustStrategy() {

 			    public boolean isTrusted(
 			            final X509Certificate[] chain, String authType) throws CertificateException {
 			        return true;
 			    }

 			});
 		} catch (KeyManagementException | UnrecoverableKeyException
 				| NoSuchAlgorithmException | KeyStoreException e) {
 			e.printStackTrace();
 		}
 		
 		cb.setSSLSocketFactory(sslsf);


-------------------------------------------------------------------------------------
Can you add the fix to next realese ?
Thanks
