### ISSUE TITLE
<classifier>withdeps</classifier> cause conflict between jars

### ISSUE THREAD

**Issue by eitanElmalam** [ContainX/openstack4j#770]
I have maven project, with dependancy that load the openstack4j jar with dependency.
When I deploy my application war file I egt the error :

2016 08 10 08:44:20#+00#ERROR#org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/MonsoonScheduler]##anonymous#localhost-startStop-1#na#xedac3f1e#schedularos#web##Error configuring application listener of class scheduler.QuartzListenerjava.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader 'org.apache.catalina.loader.WebappClassLoader@ 1837041 (urls: ['], parents: [)'java.net.URLClassLoader@5ecddf8f']) of the current class, org/slf4j/LoggerFactory, and the class loader 'System (urls: [''file:/usr/lib/jvm/sapjvm_8/sapjvm_8/lib/jvmx.jar', 'file:/usr/lib/jvm/sapjvm_8/sapjvm_8/lib/tools.jar', 'file:/usr/sap/ljs/bin/jul-to-slf4j.jar', 'file:/usr/sap/ljs/bin/slf4j-api.jar', 'file:/usr/sap/ljs/bin/logback-classic.jar', 'file:/usr/sap/ljs/bin/logback-core.jar', 'file:/usr/sap/ljs/bin/logback-config/', 'file:/usr/sap/ljs/bin/com.sap.core.js.logging.jar', 'file:/usr/sap/ljs/bin/bootstrap.jar', 'file:/usr/sap/ljs/bin/tomcat-juli.jar'], parents: [)'Extension']) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418) at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357) at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)

It's look like a conflict, what I need to do ?

**Comment by vinodborole** [comment]
@eitanElmalam can you share you maven config?

**Comment by eitanElmalam** [comment]
Attached the pom xml.

**Comment by eitanElmalam** [comment]
Hello,

Which information you need ??
This is a maven project I sent you the pom.xml.
When I added the openstak4j -withdeps  , the war file not started , and I get the exception I sent you.
It's a tomcat server on cloud .
There is a conflict between slf4j classes, how can I resolved it ?

Thanks

**Comment by vinodborole** [comment]
if your project already uses sl4j then you can exclude them; check maven exclude for more info

**Comment by eitanElmalam** [comment]
I did : 
<dependency>
   <groupId>org.pacesys</groupId>
  <artifactId>openstack4j</artifactId>
  <version>3.0.0</version>
 <classifier>withdeps</classifier> 
 <exclusions>
     <exclusion>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
     </exclusion>
   </exclusions>
    
</dependency>

It's did not help ..

**Comment by eitanElmalam** [comment]
I did : 

//<dependency>
 //  <groupId>org.pacesys</groupId>
 // <artifactId>openstack4j</artifactId>
 // <version>3.0.0</version>
// <classifier>withdeps</classifier> 
// <exclusions>
  //   <exclusion>
    //    <groupId>org.slf4j</groupId>
     //   <artifactId>slf4j-api</artifactId>
    // </exclusion>
  // </exclusions>
    
//</dependency>

**Comment by eitanElmalam** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20268444/17554725/fb98cbf8-5f14-11e6-877d-3de0eaad96e3.png)

**Comment by vinodborole** [comment]
@eitanElmalam does ur maven xml contain only this, or there are any other dependencies?

**Comment by eitanElmalam** [comment]
[pom.txt](https://github.com/ContainX/openstack4j/files/412720/pom.txt)

**Comment by vinodborole** [comment]
@eitanElmalam it looks like quartz and openstack4j use the same version of slf4j; can you not exclude from os4j and do it for quartz like this

            <dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>2.2.1</version>
			<exclusions>
				<exclusion>
					<artifactId>slf4j-api</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by eitanElmalam** [comment]
yes, it"s solve it ..

**Comment by eitanElmalam** [comment]
My mistake , I got the same error ...

**Comment by vinodborole** [comment]
@eitanElmalam can u verify whether the slf4j jar is removed from quartz; you can check that in eclipse dependency hierarchy view if at all u are using eclipse
