### ISSUE TITLE
Identity v3 with scopeToProject(Identifier.byName(projectName))

### ISSUE THREAD

**Issue by draoullig** [ContainX/openstack4j#776]
Hi,

When you use the method scopeToProject with just Identifier.byName(projectName), the identification fails.
If you use scopeToProject with Identifier.byName(projectName) and Identifier.byName(domainName), the identification is good.
By comparing the methods ScopeProject create... from the class  openstack4j/core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneAuth.java, it seems that lack the clause: 
else {
    scope.name = project.getId();
}
in the method public static ScopeProject create(Identifier project).

Best regards.

Frédéric.

**Comment by auhlig** [comment]
Hi @draoullig,

Scoping to a project just by name isn't possible as the project name is only unique within a domain. 
You can either use the 
```
scopeToProject(Identifier.byId(projectId))
``` 
as the id of the project is unique across domains or alternatively
```
.scopeToProject(Identifier.byName(projectName))
.scopeToDomain(Identifier.byName(domainName)) // domain id or name
``` 
a combination of project name and domain.

Although I admit the code you found looks suspicious the test and the recorded client-openstack interactions looks good.

**Comment by draoullig** [comment]
Hi,

Thanks for the explanation, now I understand the implementation.

Bests regards.

Frederic.

2016-08-16 22:44 GMT+02:00 Arno Uhlig <notifications@github.com>:

**Comment by ScottMaclure** [comment]
@auhlig perhaps add an example of scoping by project name + domain name in the getting started guide, this tripped me up because I was previously scoping by project id. It makes sense now after reading this page.

**Comment by auhlig** [comment]
Thanks @vinodborole

**Comment by vinodborole** [comment]
@auhlig  i have made committed the change but i do not see the changes on the page..can u check my latest commit.

**Comment by auhlig** [comment]
Your commit looks fine. It was just not deployed. Is that only triggered on PR merge?

**Comment by vinodborole** [comment]
not sure, i did a direct commit to master... @gondor can you check.

**Comment by auhlig** [comment]
yeah. i can see it. i don't think you did anything wrong. that should have worked. 
can deployment be triggered manually?

**Comment by auhlig** [comment]
log looks good https://travis-ci.org/ContainX/openstack4j.com/builds/164855887. Image pushed successfully.

**Comment by gondor** [comment]
There was an error on deploy.  I need to look into it but the change did make it into the container :)

**Comment by gondor** [comment]
Should be fixed. Build 34 from travis was deployed

**Comment by vinodborole** [comment]
Thanks @gondor :+1:
