### ISSUE TITLE
Support for Tacker - NFV Orchestration - Version 1.0 Implementation

### ISSUE THREAD

**Issue by vishvesh** [ContainX/openstack4j#786]
#### Tacker - NFV Orchestration - Version 1.0 Implementation

I have created the below Pull Request in order to track `Tacker` Related Implementation
* `Tacker Initial Implementation PR`: https://github.com/ContainX/openstack4j/pull/785

**Comment by auhlig** [comment]
Hi @vishvesh,
Can We Close this issue since the PR is merged?

**Comment by vishvesh** [comment]
@auhlig : Sure, closing it !!
