### ISSUE TITLE
oSClientV2 .identity().users().list() oSClientV2 .identity().tenants().list()  return empty list

### ISSUE THREAD

**Issue by liucj111926** [ContainX/openstack4j#788]
OSClientV2 oSClientV2 = OSFactory.builderV2()
                .endpoint("http://10.0.0.11:35357/v2.0")
                .credentials("admin", "openstack")
                .tenantName("admin")
                .authenticate();

oSClientV2 .identity().users().list() oSClientV2 .identity().tenants().list()  return empty list

**Comment by liuxiwen** [comment]
oSClientV2.perspective(Facing.ADMIN).identity().users().list()
do like this, you can print result

**Comment by liucj111926** [comment]
@liuxiwen thanks a lot,I try to get the user list was successful but get the tenant list return empty

**Comment by vinodborole** [comment]
Likely same root cause as in the other issue you raised? #742

**Comment by liucj111926** [comment]
@vinodborole That issue is not me

**Comment by liucj111926** [comment]
@liuxiwen @vinodborole use 3.0.2version there is no problem
