### ISSUE TITLE
404 - Path /org/pacesys/openstack4j/3.0.2-SNAPSHOT/ not found

### ISSUE THREAD

**Issue by AMontanana** [ContainX/openstack4j#792]
I'm trying to download the 3.0.1-withdeps jar file from the Getting Started page:
http://www.openstack4j.com/learn/getting-started

but get a 404 error when I click on the button:
404 - Path /org/pacesys/openstack4j/3.0.2-SNAPSHOT/ not found in local storage of repository "Snapshots" [id=snapshots]
Path /org/pacesys/openstack4j/3.0.2-SNAPSHOT/ not found in local storage of repository "Snapshots" [id=snapshots]

Thanks

Antonio

**Comment by vinodborole** [comment]
@AMontanana it works for me, please try again

**Comment by auhlig** [comment]
@AMontanana I guess you want to grab either 3.0.**3**-SNAPSHOT or the latest stable 3.0.**2**.

**Comment by auhlig** [comment]
@AMontanana I assume it's no longer valid? Closing this.
