### ISSUE TITLE
KeystoneRole in Identity V3 lacked the "domain_id" property

### ISSUE THREAD

**Issue by zizhongwei** [ContainX/openstack4j#796]
KeystoneRole in Identity V3 lacked the "domain_id" property：
![image](https://cloud.githubusercontent.com/assets/12456254/18259056/8fbe2b36-7412-11e6-9bdd-302b0ae215c1.png)
"domain_id" property in the OpenStack API：
![image](https://cloud.githubusercontent.com/assets/12456254/18259081/c0221486-7412-11e6-9071-d4400ef9e364.png)

**Comment by auhlig** [comment]
Just had a look at the test an saw that this attribute wasn't included at the time I wrote os4j's Identity V3 implementation.
Unless you want to submit the enhancement I could do it during the week

**Comment by zizhongwei** [comment]
I want to submit this enhancement, 3ks.

**Comment by auhlig** [comment]
Closing this as enhancement has been done in #800
