### ISSUE TITLE
Can't create flavor with isPublic attribute in version 3.0.2

### ISSUE THREAD

**Issue by eveknow** [ContainX/openstack4j#809]
In version 3.0.2.

I can't create new flavor with is Public param.
File FlavorService.class in org.openstack4j.api.compute:
Flavor create(String name, int ram, int vcpus, int disk, int ephemeral, int swap, float rxtxFactor);

There no api to call create flavor with isPublic param.

Thanks all.

**Comment by auhlig** [comment]
@eveknow Right. I saw the isPublic-attribute in the Flavor. But it's missing in the method above and in the respective builder interface. Should be easy to fix.
Would you like to contribute and enhance os4j? 

Feel free to reach out in case you need help.

**Comment by biogerm** [comment]
@auhlig @eveknow I am working on a PR related to Flavor, I will include this.

**Comment by eveknow** [comment]
@auhlig  
Thanks for your reply. I like to contribute whenever i'm free.

**Comment by auhlig** [comment]
Cool. @eveknow Maybe worth syncing with @biogerm to avoid work duplication.

**Comment by biogerm** [comment]
@eveknow please wait a bit. Let's see if my new PR solves your problem. It should come today.

**Comment by auhlig** [comment]
https://github.com/ContainX/openstack4j/pull/813

**Comment by auhlig** [comment]
@eveknow Can we close the issue since #813 is merged?

**Comment by eveknow** [comment]
Everything seem good when create flavor in this release.
Thanks @auhlig, @biogerm
