### ISSUE TITLE
Listing projects with OSClientV3 resolves to "/v2.0/projects" GET request

### ISSUE THREAD

**Issue by ScottMaclure** [ContainX/openstack4j#811]
As per the docs here:
http://www.openstack4j.com/learn/identity/identity-v3/#projects

Using OSClientV3 (scoped to domain):
```
OSClientV3 os = OSFactory.builderV3()... etc.

List<? extends Project> projectList = os.identity().projects().list();
```

Debugging now, but have confirmed this locally with v3.0.2.

If I change the endpoint in the debugger to "v3/projects", I get back a project list. Otherwise, an empty collection is returned.

Will update when I dig further.

Edit1: KeystoneEndpoints configured for v3 service with v2.0 URLs?

![example-openstack4j-projects-v2 1](https://cloud.githubusercontent.com/assets/962320/18536631/1811fcde-7b42-11e6-80d5-add630099f93.png)

![example-openstack4j-projects-resolvev3](https://cloud.githubusercontent.com/assets/962320/18536881/517761d8-7b44-11e6-998f-8ea26e3e47bd.png)

**Comment by auhlig** [comment]
I guess the error's cause can be found in the token catalog. Can you check you configured identity v3 properly and the endpoint, found in the catalog, is correct and ending with /v3 ?

**Comment by ScottMaclure** [comment]
For configuration, currently I do:

```
OSClientV3 os = OSFactory.builderV3()
    .endpoint(someUrl)
    .credentials(username, password, domainIdentifier)
    .scopeToProject(projectIdentifier)
    .authenticate();
```

Can see the endpoint with v3 and the catalog with v2:

![demo-v2-v3](https://cloud.githubusercontent.com/assets/962320/18571918/9cf0c7c0-7bf9-11e6-969d-3525a1e6315a.png)

Am I missing a configuration step somewhere?

**Comment by auhlig** [comment]
Short: That screenshot confirms my suspicion. You only have one keystone available in the catalog which points to the wrong keystone v2 endpoints. You have to configure the OpenStack instance properly and setup a Keystone V3 service. But that is more about OpenStack itself than it is for OpenStack4j.

**Comment by ScottMaclure** [comment]
Thanks - I will chase it up with the vendor - I will close the issue for now, and re-open if needed.
