### ISSUE TITLE
Class AuthIdentity doesnot implements the Serializable interface

### ISSUE THREAD

**Issue by whaon** [ContainX/openstack4j#817]
when I use ehcache to cache the Token,the following Exception occured
```
java.io.NotSerializableException: org.openstack4j.openstack.identity.v3.domain.KeystoneAuth$AuthIdentity
```

**Comment by auhlig** [comment]
I missed this issue. Do you want to submit a PR fixing this @whaon ?

**Comment by auhlig** [comment]
Merged the PR. Can we close this issue?
