### ISSUE TITLE
NovaFlavor have a wrong get : Boolean isPublic()

### ISSUE THREAD

**Issue by zizhongwei** [ContainX/openstack4j#818]
NovaFlavor have a wrong get : Boolean isPublic()
when the NovaFlavor object convert to JSON ,the JSON text have a  unexpected  property  'public' ,like this : 
![image](https://cloud.githubusercontent.com/assets/12456254/18656595/086dcefc-7f25-11e6-96dd-331e8b676f68.png)

so the create API retunt BAD_REQUEST : 
![image](https://cloud.githubusercontent.com/assets/12456254/18656483/ffe6947c-7f23-11e6-8d31-6566af35377b.png)

**Comment by zizhongwei** [comment]
I will fix this during the week

**Comment by auhlig** [comment]
@zizhongwei Can we close this issue?

**Comment by zizhongwei** [comment]
@auhlig yes,we should close this issue.
