### ISSUE TITLE
Use 3.0.0 openstack4j version OSClientV2 to get tenant for null

### ISSUE THREAD

**Issue by llw5266** [ContainX/openstack4j#828]
this is my code:
  OSClientV2 os = OSFactory.builderV2()
                  .endpoint("http://192.168.9.3:5000/v2.0")
                  .credentials("admin","admin")
                  .perspective(Facing.ADMIN)
                  .tenantName("admin")
                  .authenticate();

  List<? extends Tenant> tenants = os.identity().tenants().list();
  System.out.println(tenants.size());

**Comment by mikeagarza** [comment]
I have a similar issue.  Looking at the http log I see that it seems to be generating a v3 url for the list even though I am using the OSClientV2.  Here is the log:

Sending request http://10.0.50.1:5000/v2.0/tokens on null
OS4J-Auth-Command: Tokens

Received response for http://<IP>:5000/v2.0/tokens in 124.2ms
Date: Mon, 10 Oct 2016 21:46:31 GMT
Server: Apache/2.4.6 (CentOS)
Vary: X-Auth-Token,Accept-Encoding
x-openstack-request-id: req-38c38dc4-a0a3-47b1-9002-c72421e067cd
Connection: close
Content-Type: application/json
OkHttp-Sent-Millis: 1476135991896
OkHttp-Received-Millis: 1476135992017

Sending request http://<IP>:35357/v3/tenants on null
X-Auth-Token: <Token>
User-Agent: OpenStack4j / OpenStack Client

Received response for http://<IP>:35357/v3/tenants in 406.5ms
Date: Mon, 10 Oct 2016 21:49:49 GMT
Server: Apache/2.4.6 (CentOS)
Vary: X-Auth-Token
x-openstack-request-id: req-7c8f04d9-404e-4acf-acde-4eb41c5f973d
Content-Length: 93
Connection: close
Content-Type: application/json
OkHttp-Sent-Millis: 1476136189962
OkHttp-Received-Millis: 1476136190358

**Comment by orzech256** [comment]
I have the same issue, i did some investigation here, and here are my findings. 
To get the Tenant list openstack4j internally creates request for it **/auth/tenants**, but the OpenStack API v2 documentation specifies path without **/auth/**.
In this situation the response for such request it is "Not Found". The status 404 is not propagated to the client and we have empty tenant list without any warning about malformed URL (please see the attached screenshots) 
![openstack4j-request](https://cloud.githubusercontent.com/assets/6146623/20478985/adccf41c-afdc-11e6-97e0-1d96c4da93d3.png)
![openstack4j-response](https://cloud.githubusercontent.com/assets/6146623/20478986/adcdf3b2-afdc-11e6-8d3d-ad1f3983c283.png)

Can it be fixed smoothly?

**Comment by orzech256** [comment]
I can see now it was fixed already
see revision: https://github.com/ContainX/openstack4j/pull/670/commits/ee4bf2a2d6746e2bc171c999d188d27f3dff47af

https://github.com/ContainX/openstack4j/pull/670

**Comment by auhlig** [comment]
@llw5266 @orzech256 Can we close since the issues is fixed in a newer version?
