### ISSUE TITLE
Change some endponints of the services

### ISSUE THREAD

**Issue by romoreira** [ContainX/openstack4j#842]
Hi community, 

I want to change endpoint URL of the telemetry service. When I do authenticate, I receive some URLs (endpoints) of the available services. But, I need to change the URL string of the Telemetry service, because I have the URL <IP:Port>/v2/meters works (available), and the API considers just <IP:Port>/meters (404 not found - obviously). Can anyone help me? I can change that in the code? How I can do this?

Best Regards.

**Comment by vinodborole** [comment]
@romoreira that is not the right way of doing, you need to fix your openstack to get the right url's
