### ISSUE TITLE
The okhttp HttpResponseImpl do not implement the close method

### ISSUE THREAD

**Issue by tangxiaodon89** [ContainX/openstack4j#855]
I want know why the okhttp HttpResponseImpl close method do nothing.
In my project show this log.
okhttp3.internal.platform.Platform log
warn: A connection to http://10.110.20.131:8774/ was leaked. Did you forget to close a response body?
Shoud I call this.response.body().close(); in the close method

**Comment by auhlig** [comment]
Hi @tangxiaodon89,
Thanks for filing this issue. Would you like to contribute and submit a PR to fix this?
