### ISSUE TITLE
param 'sessionPersistence' of NeutronLbPoolV2 requires @JsonProperty

### ISSUE THREAD

**Issue by JerryShi** [ContainX/openstack4j#856]
Hi Community，
     Param 'sessionPersistence' in class 'NeutronLbPoolV2' requires @JsonProperty or an error will be thrown.

ClientResponseException{message=Unrecognized attribute（s） 'sessionPersistence',，status=400， status-code=BAD_REQUEST}

**Comment by vinodborole** [comment]
@emjburns can you please address this?

**Comment by emjburns** [comment]
@vinodborole sure. Can you assign it to me?

**Comment by vinodborole** [comment]
@emjburns i don't see you in the assignees list, can you check if you can assign it to yourself?

**Comment by auhlig** [comment]
Merged fix.

**Comment by JerryShi** [comment]
@emjburns can you fix the same problem in 'NeutronLbPoolV2Update.class' ？thx

**Comment by JerryShi** [comment]
FYI @vinodborole @auhlig

**Comment by auhlig** [comment]
Hi @emjburns, Please address this if you get the chance. Thanks.
