### ISSUE TITLE
router_ids is missing from NeutronFirewall

### ISSUE THREAD

**Issue by liranyogev** [ContainX/openstack4j#857]
`router_ids` is an optional field that was introduced in [Kilo](https://github.com/openstack/neutron-fwaas/commit/d0704f056021b235caba1f906b1733f422ce68c1).

It is missing in [org.openstack4j.openstack.networking.domain.ext.NeutronFirewall](http://www.openstack4j.com/javadoc/org/openstack4j/openstack/networking/domain/ext/class-use/NeutronFirewall.Firewalls.html).

Can you please add it?

Thanks

**Comment by auhlig** [comment]
Hi @liranyogev,
Thanks for finding this issue.
Sounds good. Looking forward to your PR.

**Comment by liranyogev** [comment]
Thanks for merging :)
Any expected release date for 3.0.3?
