### ISSUE TITLE
the server api does not support tag?

### ISSUE THREAD

**Issue by whaon** [ContainX/openstack4j#859]

**Comment by whaon** [comment]
> Server tags (servers, tags)¶
> 
> Lists tags, creates, replaces or deletes one or more tags for a server, checks the existence of a tag for a server.
> 
> Available since version 2.26
> 
> Tags have the following restrictions:
> 
> Tag is a Unicode bytestring no longer than 60 characters.
> Tags are case sensitive.
> ‘/’ is not allowed to be in a tag name
> Comma is not allowed to be in a tag name in order to simplify requests that specify lists of tags
> All other characters are allowed to be in a tag name
> Each server can have up to 50 tags.

I get the content above from the openstack official website:[http://developer.openstack.org/api-ref/compute/](http://developer.openstack.org/api-ref/compute/)
but it seems that openstack4j doesn't support it.

**Comment by auhlig** [comment]
Looks like it's indeed missing. Would you like to add this?

**Comment by auhlig** [comment]
Same here. Can this be closed now?
