### ISSUE TITLE
List Flavors doesn't support query parameters

### ISSUE THREAD

**Issue by whaon** [ContainX/openstack4j#867]
such as sort_key,sort_dir,limit and etc
pls refer to the api doc:[http://developer.openstack.org/api-ref/compute/?expanded=list-flavors-detail,list-flavors-with-details-detail](http://developer.openstack.org/api-ref/compute/?expanded=list-flavors-detail,list-flavors-with-details-detail)

**Comment by auhlig** [comment]
Feel free to submit a PR.
