### ISSUE TITLE
add two more function in ComputeFloatingIPService

### ISSUE THREAD

**Issue by easyit** [ContainX/openstack4j#880]
The existing API addFloatingIP requires Server as parameter, which is heavy. I would like to request for two similar functions which take the server id as input: 

Interface added in ComputeFloatingIPService.java
`ActionResponse addFloatingIP(String serverId, String fixedIpAddress, String ipAddress);
ActionResponse addFloatingIP(String serverId, String ipAddress);`

Implementation in the ComputeFloatingIPServiceImpl.java: 

`ActionResponse addFloatingIP(String serverId, String fixedIpAddress, String ipAddress){
 return invokeAction(serverId, FloatingIpActions.Add.create(ipAddress, fixedIpAddress));
}
`
`ActionResponse addFloatingIP(String serverId, String ipAddress){
    return addFloatingIP(serverId, null,  ipAddress);
}`

**Comment by auhlig** [comment]
Sounds good. Looking forward to your PR.

**Comment by easyit** [comment]
ok, I will add the code.
