### ISSUE TITLE
new API request -  List network with filtering parameters

### ISSUE THREAD

**Issue by easyit** [ContainX/openstack4j#882]
I would like to request a new API in NetworkService to filter the networks retrieved, please refer to [https://wiki.openstack.org/wiki/Neutron/APIv2-specification#Filtering_and_Column_Selection](url).
 The API could be similar to 
`  List<? extends Network> list(Map<String, String> filteringParams);`

**Comment by auhlig** [comment]
Hey @easyit,
Thanks for creating the issue.
Sounds good. Please go ahead and submit a PR incl. some short tests.
