### ISSUE TITLE
Identity functionality doesn't work - Returning empty lists and sending the request to the wrong endpoint.

### ISSUE THREAD

**Issue by pstoyanov91** [ContainX/openstack4j#885]
The library doesn't seem to make the calls to the right endpoint so the whole identity functionality doesn't work. I want to point out the the networking functionality is working properly.

Openstack4j version: 3.0.0
Openstack version: Newton
Java 1.8

This is my code for the v3 client: 
OSClientV3 osV3 = OSFactory.builderV3()
                    .endpoint(OPENSTACK_IP_ADDRESS)
                    .credentials(OPENSTACK_USER, OPENSTACK_IP_PASSWORD, Identifier.byId("default"))
                    .scopeToProject(Identifier.byName("admin"), Identifier.byName("Default"))
                    .authenticate();

After that I try to list the users:
System.out.println(osV3.identity().users().list());

I have enabled Http Logging Filter (Which by the way doesn't work on versions 3.0.1 and 3.0.2, so I had to use version 3.0.0 in order to get the output of the logger).

The authentication is passing successful and I get the following output:
`{"token": {"is_domain": false, "methods": ["password"], "roles": [{"id": "e340895602ee4bd2922d93c02ca578a2", "name": "admin"}], "is_admin_project": true, "project": {"domain": {"id": "default", "name": "Default"}, "id": "18769f023ad4467c808176f11ad39959", "name": "admin"}, "catalog": [{"endpoints": [{"url": "http://10.129.3.97:8776/v2/18769f023ad4467c808176f11ad39959", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "27bb8f62e13848fb8aa876b307af197f"}, {"url": "http://10.129.3.97:8776/v2/18769f023ad4467c808176f11ad39959", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "5cac92d77388456d95e155aed1d7e5d8"}, {"url": "http://10.129.3.97:8776/v2/18769f023ad4467c808176f11ad39959", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "8cd077f93a8a4925b0c26bc76aae9fa3"}], "type": "volumev2", "id": "4f538b75f32748e7aa3b9600cf5b5066", "name": "cinderv2"}, {"endpoints": [{"url": "http://10.129.3.97:8774/v2/18769f023ad4467c808176f11ad39959", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "695cd2ec96e84a0db8d4ab709f64829b"}, {"url": "http://10.129.3.97:8774/v2/18769f023ad4467c808176f11ad39959", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "7ef174fcf57b48be96454f7e88108778"}, {"url": "http://10.129.3.97:8774/v2/18769f023ad4467c808176f11ad39959", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "914a0f39595e4266a7d97fb2c60b8037"}], "type": "compute_legacy", "id": "57fb21878e294be69b5bf20c0abdbc08", "name": "nova_legacy"}, {"endpoints": [{"url": "http://10.129.3.97:8774/v2.1", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "b22cd0ffe8624deb8b074a0a68a20694"}, {"url": "http://10.129.3.97:8774/v2.1", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "d80dec657e9a40b2ae9229fccf1fd20c"}, {"url": "http://10.129.3.97:8774/v2.1", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "f0f9772b98ad471c9c9340c796c3fb53"}], "type": "compute", "id": "69a5e35ebbf7481eb95715e52542fdc2", "name": "nova"}, {"endpoints": [{"url": "http://10.129.3.97:8776/v3/18769f023ad4467c808176f11ad39959", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "80fd82075d6a41dfbfa6a53450d6395e"}, {"url": "http://10.129.3.97:8776/v3/18769f023ad4467c808176f11ad39959", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "ab3414c41f504771be58cf695a2903e9"}, {"url": "http://10.129.3.97:8776/v3/18769f023ad4467c808176f11ad39959", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "b0d7f8d3cfff46b2b772241b60be2bba"}], "type": "volumev3", "id": "796e21e44fbc4d298d99523ecb8f9d2d", "name": "cinderv3"}, {"endpoints": [{"url": "http://10.129.3.97:8004/v1/18769f023ad4467c808176f11ad39959", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "16ca587c347e423da0c4a653cb75baba"}, {"url": "http://10.129.3.97:8004/v1/18769f023ad4467c808176f11ad39959", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "3c0de009015449d3aa4ef4ab2ee75363"}, {"url": "http://10.129.3.97:8004/v1/18769f023ad4467c808176f11ad39959", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "3dfca194c6844b8f971140f5448e8b9e"}], "type": "orchestration", "id": "b6bf1e0f72ea4951aa9b13ad9fadd795", "name": "heat"}, {"endpoints": [{"url": "http://10.129.3.97:8000/v1", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "b54e3f0d9af54600a8c01a71765c2e25"}, {"url": "http://10.129.3.97:8000/v1", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "bde41bbfb24d4bd3968642bc12844204"}, {"url": "http://10.129.3.97:8000/v1", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "c768a803d2e94ebb91da76ca51ea5934"}], "type": "cloudformation", "id": "c25fd27e6daf4b0bafa148c4fe8032f6", "name": "heat-cfn"}, {"endpoints": [{"url": "http://10.129.3.97:9696/", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "32664a2c7cb644649bdb6b1d04523879"}, {"url": "http://10.129.3.97:9696/", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "462ec36a4d4a404cad4a173d12cc246c"}, {"url": "http://10.129.3.97:9696/", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "9fce850be5164149ab92a6ae616c8042"}], "type": "network", "id": "c57c4669b10e4017a32f521a878baf5b", "name": "neutron"}, {"endpoints": [{"url": "http://10.129.3.97:9292", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "a81a069d166e43bf9464cdf9229adfaa"}, {"url": "http://10.129.3.97:9292", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "a91173d687b9464b8728a673670713e9"}, {"url": "http://10.129.3.97:9292", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "f6d3a35a69f9492484a73eb1ffdb4467"}], "type": "image", "id": "d291e0dd7f2f4fd0a6e2d2ace780db1f", "name": "glance"}, {"endpoints": [{"url": "http://10.129.3.97:8776/v1/18769f023ad4467c808176f11ad39959", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "35222c5a41ca40caa8a6a3cc7888b7ff"}, {"url": "http://10.129.3.97:8776/v1/18769f023ad4467c808176f11ad39959", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "8600c36b3f4b41fc89a06e29200603d3"}, {"url": "http://10.129.3.97:8776/v1/18769f023ad4467c808176f11ad39959", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "fb8e5cf43b4d4dcb9eec4c9a523e221d"}], "type": "volume", "id": "eb2cf3942adc4d4f945263b2160a743c", "name": "cinder"}, {"endpoints": [{"url": "http://10.129.3.97/identity", "interface": "public", "region": "RegionOne", "region_id": "RegionOne", "id": "777bab1ab19445139beb83ac9c2e0c95"}, {"url": "http://10.129.3.97/identity", "interface": "internal", "region": "RegionOne", "region_id": "RegionOne", "id": "d4a4b93bdbe343e1b9d97e4af57d980f"}, {"url": "http://10.129.3.97/identity_admin", "interface": "admin", "region": "RegionOne", "region_id": "RegionOne", "id": "fdff4aedb5ea472e8034a17bb02ba44f"}], "type": "identity", "id": "f028662e016e4ecba05273717683e50f", "name": "keystone"}], "expires_at": "2016-11-10T12:01:08.000000Z", "user": {"password_expires_at": null, "domain": {"id": "default", "name": "Default"}, "id": "4fc619533a2147f994f227a3c4fa9c93", "name": "admin"}, "audit_ids": ["fQRVwg2UQuChpk3JofWJRw"], "issued_at": "2016-11-10T11:01:08.000000Z"}}`

After that I'm trying tho list the users:

Nov 10, 2016 1:01:08 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
**1 > GET http://10.129.3.97/identity/users**
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: 15390cbe45a4422ea15413ee616028c7

Nov 10, 2016 1:01:08 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 404
1 < Connection: Keep-Alive
1 < Content-Length: 93
1 < Content-Type: application/json
1 < Date: Thu, 10 Nov 2016 11:01:08 GMT
1 < Keep-Alive: timeout=5, max=100
1 < Server: Apache/2.4.18 (Ubuntu)
1 < Vary: X-Auth-Token
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

**As you can see the GET request is sent to /identity/users instead of /v3/users**

What I've found out is, that when **I log in Openstack UI and go to Admin -> System Information** i have this endpoint:
![openstack endpoints](https://cloud.githubusercontent.com/assets/7808089/20174739/1a66602e-a748-11e6-8afc-93ac8298eb52.png)

**Comment by auhlig** [comment]
Hi @pstoyanov91,
Your keystone v3 endpoint is incorrect. It is defined as http://<fqdn>:5000/v3.

**Comment by pstoyanov91** [comment]
Hi auhlig,
Thanks! The problem really was with the endpoints. 

For those having the same issue: I have changed the **http://ip_addr/identity** to **http://ip_addr:5000/v3** directly in the keystone database. That broke the UI, but the requests with the library are now working. I haven't figured out how to safely change the keystone endpoints after the OpenStack installation, so the best option is to be configured on installation.

Best Regards.

**Comment by mathiasbrito** [comment]
Hi Guys, to avoid this just add the variable ENABLE_HTTPD_MOD_WSGI_SERVICES and set it to false in the local.conf if you are using Devstack, it will avoid using the mod_wsgi and expose the APIs in the same port, 80. The piece of code responsible for creating the /identity thing can be found in the file that can be found in lib/keystone in devstack:

```{r, engine='bash', count_lines}
if [ "$KEYSTONE_DEPLOY" == "mod_wsgi" ]; then
    # If running in Apache, use path access rather than port.
    KEYSTONE_AUTH_URI=${KEYSTONE_AUTH_PROTOCOL}://${KEYSTONE_AUTH_HOST}/identity_admin
    KEYSTONE_SERVICE_URI=${KEYSTONE_SERVICE_PROTOCOL}://${KEYSTONE_SERVICE_HOST}/identity
else
    KEYSTONE_AUTH_URI=${KEYSTONE_AUTH_PROTOCOL}://${KEYSTONE_AUTH_HOST}:${KEYSTONE_AUTH_PORT}
    KEYSTONE_SERVICE_URI=${KEYSTONE_SERVICE_PROTOCOL}://${KEYSTONE_SERVICE_HOST}:${KEYSTONE_SERVICE_PORT}
fi
```

Not sure if this should be considered a problem or a configuration issue. Looks like that this is a configuration option of, at least, Devstack. After using this approach I got:

![bildschirmfoto 2017-04-11 um 20 45 27](https://cloud.githubusercontent.com/assets/16703250/24925249/f3a1034a-1ef7-11e7-9be8-6ea4c9c4e043.png)

Hope it helps...
