### ISSUE TITLE
Openstack4j 3.0.3‘s method :ActionResponse updateTag(String tagkey,String tagvalue) of Glance Image v2  has a bug,it sends the error uri

### ISSUE THREAD

**Issue by zhoutiekui** [ContainX/openstack4j#887]
ActionResponse updateTag(String tagkey,String tagvalue)
sends:  PUT /v2/images/{tag-key}/tags/{tag-value}, but the {tag-key} should be {image_id} insted.

same error with the method "DELETE /v2/images/{image_id}/tags/{tag}":
openstack4 sends as follow:
DELETE /v2/images/{tag-key}/tags/{tag-value} ,the {tag-key} should be {image_id} insted.

**Comment by auhlig** [comment]
The code in question https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/image/v2/internal/ImageServiceImpl.java#L188.

Could you take a look @emjburns? Many thanks.

**Comment by emjburns** [comment]
@auhlig yep I'll take a look.

**Comment by emjburns** [comment]
@zhoutiekui I'm wondering if you're using the methods as intended? Your issues says "Openstack4j 3.0.3‘s method :ActionResponse updateTag(String tagkey,String tagvalue)" but this is not the correct way to call updateTag. You should be calling it using imageId and tagvalue (updateTag(String imageId, String tag)) as documented here: http://www.openstack4j.com/learn/image-v2/#activating-deactivating-and-tagging . The same goes for the delete call. In Glance V2, a tag is just a string, not a key value pair.

Code reference for the interface: https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/api/image/v2/ImageService.java#L147
https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/api/image/v2/ImageService.java#L156

Can you try using updateTag(imageId, tag) and deleteTag(imageId, tag) and let me know if it's working correctly? Thanks!

**Comment by zhoutiekui** [comment]
I have confirmed ,it is my mistake ,thanks @auhlig @emjburns

**Comment by emjburns** [comment]
@zhoutiekui no problem. Happy to help!

**Comment by auhlig** [comment]
Thanks @emjburns
