### ISSUE TITLE
org.openstack4j.model.storage.block.Volume miss bootable property

### ISSUE THREAD

**Issue by easyit** [ContainX/openstack4j#888]
As mentioned in this document [http://developer.openstack.org/api-ref/block-storage/v2/?expanded=list-volumes-with-details-detail,show-volume-details-detail](url) , the response from Show volume details  contains:
bootable  boolean	  Enables or disables the bootable attribute. You can boot an instance from a bootable volume.
However, the bootable property is missed in the model `org.openstack4j.model.storage.block.Volume`

**Comment by auhlig** [comment]
Hey @easyit,
Thanks for filing the issue. 
Would you like to submit another PR to fix this?
