### ISSUE TITLE
Unable to build using Maven version 2.x, assuming version 3.0+ required

### ISSUE THREAD

**Issue by SeanRMunoz** [ContainX/openstack4j#890]
Attempted build using Maven version 2.2.1 and received the following error:
[see attached: [compile-os4j302-maven221-error.txt](https://github.com/ContainX/openstack4j/files/595837/compile-os4j302-maven221-error.txt)]

```
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error installing artifact: File /home/dorado/dev/repos/openstack4j/core/target/features.xml does not exist

```
Subsequent build using Maven version 3.3.9 successful. Suggest using `maven-enforcer-plugin` to stop/fail build if using less than Maven version 3.0? 

Suggested addition to pom.xml:

```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-enforcer-plugin</artifactId>
<version>1.4.1</version>
<executions>
  <execution>
	<id>enforce-maven</id>
	<goals>
	  <goal>enforce</goal>
	</goals>
	<configuration>
	  <rules>
		<requireMavenVersion>
		  <version>3.0</version>
		  <message>Build FAILURE: Maven version 3.0+ REQUIRED!</message>
		</requireMavenVersion>
	  </rules>    
	</configuration>
  </execution>
</executions>
</plugin>

```

**Comment by auhlig** [comment]
Hi @SeanRMunoz,
Good point.
Thanks for filing the issue and submitting the PR.

**Comment by auhlig** [comment]
Merged. Thanks again. Can we close this issue @SeanRMunoz ?

**Comment by SeanRMunoz** [comment]
Yes @auhlig this issue #890 has been resolved. Thank you.
