### ISSUE TITLE
how to manage the CPU core num and memory size when creating server

### ISSUE THREAD

**Issue by mongolkim** [ContainX/openstack4j#897]
ServerCreate sc = Builders.server().name("baater2").networks(list_network).flavor("2").image("3ee9e4d2-356d-4f6d-ac0e-6252d5c6930d").build();
			
			System.out.println(sc.getName());
			
			Server server = os.compute().servers().boot(sc);
			server.getPowerState();

**Comment by vinodborole** [comment]
@mongolkim CPU and memory are part of the flavor, you manage the flavor for a particular size of CPU or memory

**Comment by auhlig** [comment]
Can this be closed @mongolkim?
