### ISSUE TITLE
[Query] identity project list returns no project every time

### ISSUE THREAD

**Issue by bouskaJ** [ContainX/openstack4j#899]
Hi I am struggling with usage of Identity Service (Keystone) V3.

I am not able to execute any operation with identity service.
I have example with projects list.

I am using OS client like this:
```java
OSFactory.builderV3()
	.endpoint(OPENSTACK_URI")
        .credentials("OPENSTACK_USERNAME", "OPENSTACK_PASSWORD"), Identifier.byId"default"))
	.scopeToProject(Identifier.byId("PROJECT"))
.authenticate().identity().projects().list().size()
```
and the result is 0 every time but when I execute command 
```
openstack project list
```

I will get:
+----------------------------------+--------------------+
| ID                               | Name               |
+----------------------------------+--------------------+
| 2c38dda6f2274519b2a55fe558508d59 | admin              |
| 2d59c4e0af524b2c95f526e21f00a3fa | swiftprojecttest2  |
| 62b9b34d496b404eadad571df31dfd98 | swiftprojecttest4  |
| 7227d1d2c9be488d82ec594c70140da5 | swiftprojecttest1  |
| 7dd3f1eda49e42c89579b004578074a4 | alt_demo           |
| 988c848ecefd419cabd39a0e5336b188 | invisible_to_admin |
| bd59dbc3930542508b4c03d248bee867 | demo               |
| d2fdf1850c704baeafcecc3673c82343 | service            |
+----------------------------------+--------------------+

I tried to modifie client configuration in following ways:
1) scopeToDomain("default) => 0
2) remove scope at all => NullPointerException

Did I miss something?

**Comment by auhlig** [comment]
Hi @bouskaJ,
Could you share more details? Logging of requests and responses should help.

**Comment by bouskaJ** [comment]
@auhlig sure.

This is the simple method I run:

```java
OSClient.OSClientV3 client =  OSFactory.builderV3()
                .endpoint("http://172.24.1.69:5000/v3")
                .credentials("demo", "nomoresecret", Identifier.byId("default"))
                .scopeToProject(Identifier.byId("bd59dbc3930542508b4c03d248bee867")).authenticate();

        List<? extends Project> projectList = client.identity().projects().list();
        System.out.println(projectList); // the result is [] every time
```

And I have captured this two packet in wireshark:

1. 
`Hypertext Transfer Protocol
    GET /identity/projects HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET /identity/projects HTTP/1.1\r\n]
            [GET /identity/projects HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: GET
        Request URI: /identity/projects
        Request Version: HTTP/1.1
    Accept: application/json\r\n
    X-Auth-Token: gAAAAABYRFznfJL06HPYpD4CyrStxfzEECfj0zoMQrv3w5CZ4B2NiFtufWay-4BPjVa1b3e86lgxxNdOlgBHb6hQvaSOfHRkWDczPwT45ZITA0ZiDw61h3M5S1aO-M741ZW4krlHA0lEEYgoINCHZ5awm3k5fn9Ib86Z9Avqjp2VitKHFJAN8bY\r\n
    User-Agent: OpenStack4j / OpenStack Client\r\n
    Host: 172.24.1.69\r\n
    Connection: keep-alive\r\n
    \r\n
    [Full request URI: http://172.24.1.69/identity/projects]
    [HTTP request 1/1]
    [Response in frame: 3230]`

2.
`Hypertext Transfer Protocol
    HTTP/1.1 404 Not Found\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 404 Not Found\r\n]
            [HTTP/1.1 404 Not Found\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Version: HTTP/1.1
        Status Code: 404
        Response Phrase: Not Found
    Date: Sun, 04 Dec 2016 18:13:59 GMT\r\n
    Server: Apache/2.4.18 (Ubuntu)\r\n
    Vary: X-Auth-Token\r\n
    Content-Length: 93\r\n
    Keep-Alive: timeout=5, max=100\r\n
    Connection: Keep-Alive\r\n
    Content-Type: application/json\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.001393269 seconds]
    [Request in frame: 3228]
JavaScript Object Notation: application/json
    Object
        Member Key: "error"
            Object
                Member Key: "message"
                    String value: The resource could not be found.
                Member Key: "code"
                    Number value: 404
                Member Key: "title"
                    String value: Not Found`

I have done a little investigation with Wireshark and OpenStack Horizon-dashboard and it seems that Horizon uses different URL to resolve the projects.

Openstack4j uses *http://172.24.1.69/identity/projects* but horizon uses *http://172.24.1.69/identity/v3/users/a56fe39fc0d040ecac74bdd6a9a2c41e/projects*

So I run my project in debug mode, changed request URI to URI which horizon uses and it works.

Could it be a bug or is it only wrong setting?

**Comment by auhlig** [comment]
Check the token's catalog for the identity v3 entry. The endpoint should be something like `http://<fqdn>:5000/v3` .

**Comment by bouskaJ** [comment]
I am not sure if I understand you properly but I try to check token generation in this way:
I debug this method https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/core/transport/HttpRequest.java#L401

It runs twice
- in first run the provider is null (it is the initial authentication)
- In the second run getTokenId () method returns the token as I expect

**Comment by bouskaJ** [comment]
Sorry I have made a little digging in code I understand you now. The token service returns catalog which contains wrong URL (*http://172.24.1.69/identity*) but I need *http://172.24.1.69/identity/v3* so it seems that is the DevStack bug. Am I right?

**Comment by auhlig** [comment]
Yes. You could either stick to the defaults (`http://<fqdn>:5000/v3`) or write a custom resolver in OpenStack4j (see docs/FAQ).

**Comment by auhlig** [comment]
BTW: What was that NPE? Could that be a bug?

**Comment by bouskaJ** [comment]
@auhlig First I want to say thanks for help with my issue.

About the NEP: It seems that in master branch is the bug with NPE fixed. I am using the version 3.0.2. The NPE rises on [this](https://github.com/ContainX/openstack4j/blob/openstack4j-2.0.2/core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java#L101) line and it is fixed by [this](https://github.com/ContainX/openstack4j/commit/1ae0e833dda794044b326cedeee8e653916be5e5) commit.

**Comment by auhlig** [comment]
You're welcome @bouskaJ. Hope you like OS4j :)
Yes. I remembered this NPE. Just wanted to reaffirm it's fixed.

Can we close this issue?

**Comment by bouskaJ** [comment]
I have one more question. I try to use the solution you suggested me but It did not work for me.
I created new config as it is mentioned in FAQ but the resolver still returns me wrong URL. So I take a look to URL resolution and I am not sure that the new config is really used. Can you please verify it?

Look at [this](https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/internal/OSClientSession.java#L469) line in OSClientSession. Here is config properly set in URLResolverParams.

Then the URL is resolved in [this](URLResolverParams) method and I can't see that the p.resolver is somewhere used.

**Comment by auhlig** [comment]
Strange. I cannot see the p.resolver part either. Long time ago when I wrote this.
In Identity V2 (1) https://github.com/ContainX/openstack4j/blob/6c3451d7073282535d5982b6bcc72eba28b7d0ba/core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java#L90 leads to (2) https://github.com/ContainX/openstack4j/blob/6c3451d7073282535d5982b6bcc72eba28b7d0ba/core/src/main/java/org/openstack4j/model/identity/URLResolverParams.java#L63 does the magic. 

After taking a quick look a one-liner, which does something like (1) is missing in the resolveV3() method. 
Would you volunteer to look into that, @bouskaJ ? Would be much appreciated.

**Comment by bouskaJ** [comment]
Hi @auhlig . I don't think that this would be so simple. I have tried something but I hit some problems.
The first of all is that the resolver takes a SortedSet as an argument. I was not able to sort service catalog because the services are compared by version and all services given by V3 API has not set the version (the version is null and it leads to NPE). I think that this is the reason why there is used [for cycle](https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java#L134-L146) to search for the service you want and not the [approach](https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java#L82) used in v2 resolver .

The first priority for me is the project I am working on now (dedline is comming :-D ) so I am very sorry but I have no time to solve this. Maybe If this issue stays opened for next (approximately) 2 months I could look at it.

**Comment by bouskaJ** [comment]
I asked a question about ServiceCatalog on OpenStack forum. You can see the answer https://ask.openstack.org/en/question/99971/should-not-be-version-of-identity-api-included-in-service-catalog/ . I think that the answer on ask.openstack is right (by suggested documentation) and Openstack4J should cope with this behaviour.

**Comment by auhlig** [comment]
At least the time when we added identity v3, the endpoint was version-specific.
Anyway, you're right. If that changed, Os4j should reflect that. 
An easier solution for the identity v3 case could be simply checking if the identity endpoint ends with v3 and append it if not. Not?

**Comment by bouskaJ** [comment]
Yes it could work but I think that it is not the best way. You should follow the REST approach as is described in the documentation mentioned in response to my question on ask.openstack.

> If you were to perform a GET against either of these endpoints, you would be greeted by an HTTP/1.1 300 Multiple Choices response, which newer Keystone clients can use to automatically detect available API versions.

So in opinion the best way is to check the status code and in case it is 300 search for endpoint in the HTTP response.

**Comment by bouskaJ** [comment]
I check the behavior on my OS instance:
```
 GET /identity HTTP/1.1

HTTP/1.1 300 Multiple Choices
{
   "versions":{
      "values":[
         {
            "status":"stable",
            "updated":"2016-10-06T00:00:00Z",
            "media-types":[
               {
                  "base":"application/json",
                  "type":"application/vnd.openstack.identity-v3+json"
               }
            ],
            "id":"v3.7",
            "links":[
               {
                  "href":"http://172.24.1.69/identity/v3/",
                  "rel":"self"
               }
            ]
         },
         {
            "status":"deprecated",
            "updated":"2016-08-04T00:00:00Z",
            "media-types":[
               {
                  "base":"application/json",
                  "type":"application/vnd.openstack.identity-v2.0+json"
               }
            ],
            "id":"v2.0",
            "links":[
               {
                  "href":"http://172.24.1.69/identity/v2.0/",
                  "rel":"self"
               },
               {
                  "href":"http://docs.openstack.org/",
                  "type":"text/html",
                  "rel":"describedby"
               }
            ]
         }
      ]
   }
}
```

So the valid endpoints URLs are really included in HTTP response.

**Comment by auhlig** [comment]
I'm aware of the endpoint discovery, described above. You're right, this should be implemented in Os4j. I'm too busy to do this myself atm, but if your willing to work on this (after your deadline), I'd like to support. Maybe worth getting this into a separate issue so at least we don't forget.

**Comment by auhlig** [comment]
Does it make sense to close this issue in favor of #902 to avoid duplication @bouskaJ ?

**Comment by bouskaJ** [comment]
Sure. You can close it.
