### ISSUE TITLE
Automatically Update Access Token

### ISSUE THREAD

**Issue by ahmetkarakaya** [ContainX/openstack4j#916]
After authenticated I use `access ` until it expires, but when it is expired it does not updated automcatically,
Do I need to check Access() is expired or not manually inside an other thread?

			os = OSFactory.builder().endpoint("http://" + ip + ":5000/v2.0")
				.credentials("testtimsoperator", "123456")
				.tenantName(bipTenantName)
				.perspective(Facing.ADMIN)	//Container oluşturmak için
				//.scopeToProject(projectIdentifier, domainIdentifier)  V3 ile gelen bir özellik.			
				.authenticate();
OSFactory.clientFromAccess(os.getAccess(););

   long delay = os.getAccess().getToken().getExpires().getTime() - System.currentTimeMillis();
    
    sleep(delay+5000);

    User user = findUserByName("user1");
       
    User user2 = findUserByName("user2");

		<dependency>
			<groupId>org.pacesys</groupId>
			<artifactId>openstack4j</artifactId>
			<version>2.20</version>
		</dependency>

		<dependency>
			<groupId>org.pacesys.openstack4j.connectors</groupId>
			<artifactId>openstack4j-jersey2</artifactId>
			<version>2.20</version>
	  </dependency>

**Comment by auhlig** [comment]
Hi @ahmetkarakaya 
Reauthentication should be triggered in case the code of the response is 401. 
Could you check that's the case?

**Comment by ahmetkarakaya** [comment]
@auhlig  yes reauthentication is triggered but newly taken token just used for one request, for other request to be invoked, same steps are repeated, I mean first token is used so having 401 error then taken new token  to retry the request,  I have updated my question by adding sample code portion.  As you can see than I have added a delay to expire the token , after then invoking findUserByName() method , I am getting 401 so getting a new token then retry.  The problem is when I was  invoking findUserByName("user2") I was expecting previous token would be used but I got 401 error then getting a new token .   I have analyzed debug logs,

**Comment by auhlig** [comment]
Understood. Renewed token only used for request. Original token still assigned to session. 

Here https://github.com/ContainX/openstack4j/blob/master/connectors/http-connector/src/main/java/org/openstack4j/connectors/http/HttpExecutorServiceImpl.java#L61 we check if the response code is 401, in which case the we trigger re-authentication in ll. 64 and assign the new token to the current request https://github.com/ContainX/openstack4j/blob/master/connectors/http-connector/src/main/java/org/openstack4j/connectors/http/HttpExecutorServiceImpl.java#L65 .

The authentication-method should also assign the new token to the current session https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java#L149 .
Maybe it fails here somewhere.

**Comment by ahmetkarakaya** [comment]
I have found my faulth which is I am always invoking "OSFactory.clientFromAccess(access);" before calling a request and using the same access token. 
When I have used  OSClient directly  instead of  OSFactory.clientFromAccess(os.getAccess(), Facing.ADMIN),

But I am trying to find a solution to a case that 
How can I use a single os client with different facing, I need such a case that  there many rest requests in a method AllinOneMethod(), some of which must be invoked by ADMIN facing some of which are invokde by null FACING.

**Comment by auhlig** [comment]
No bug then :sweat_smile:
Threading maybe. Can we close the issue, since there seems to be no bug? Maybe the google group or stackoverflow community can be of help.

**Comment by ahmetkarakaya** [comment]
thanks
