### ISSUE TITLE
Check for support about some openstack APIs

### ISSUE THREAD

**Issue by taemin77** [ContainX/openstack4j#929]
Hi,
I'm doing a openstack APIs test by using openstack4j.
But, I could find several APIs on openstack4j document.
One is Compute>Servers - run an action>evacuate.
and Compute>Compute services (os-services)>List Compute Services.
Could I know that you have plan to support above APIs?
thank you in advance.

**Comment by taemin77** [comment]
I checked Compute>Compute services (os-services)>List Compute Services  In lately Snapshot Version.

**Comment by auhlig** [comment]
Hi @taemin77,
I guess it's currently not supported in Os4j, but you're very welcome to submit a PR and fix that.
Feel free to reach out to us in case you need help.
