### ISSUE TITLE
Creating port adds a port_security_enabled parameter when not specified.

### ISSUE THREAD

**Issue by pstoyanov91** [ContainX/openstack4j#940]
Hello,

When I'm trying to create a port openstack4j always adds port_security_enabled which apparently is not supported anymore.

Logs:
**Request**
POST /v2.0/ports HTTP / 1.1
User - Agent: OpenStack4j / OpenStack Client
X - Auth - Token: edac4ac34c1141c5b6af3648d19f416f
Content - Length: 312
Content - Type: application / json
Host: 10.129.3.228: 9696
Connection: Keep - Alive{
	"port": {
		"name": "api_server_port",
		"admin_state_up": true,
		"fixed_ips": [{
				"ip_address": "172.27.3.34",
				"subnet_id": "57ba612b-761b-48d9-9e8b-4bfdb498fd2a"
			}
		],
		"network_id": "57ba612b-761b-48d9-9e8b-4bfdb498fd2a",
		**"port_security_enabled": true**
	}
}

**Response**
HTTP/1.1 400 Bad Request
Content-Length: 122
Content-Type: application/json; charset=UTF-8
X-Openstack-Request-Id: req-feda228a-731f-4394-91f6-31fc21370175
Date: Thu, 16 Feb 2017 13:33:14 GMT
Connection: keep-alive
{
	"NeutronError": {
		"message": "Unrecognized attribute(s) 'port_security_enabled'",
		"type": "HTTPBadRequest",
		"detail": ""
	}
}

Best regards!

**Comment by auhlig** [comment]
What version are you using? Wasn't this fixed via https://github.com/ContainX/openstack4j/commit/055028765cab562ec1555ac8512ddee791da85f, @vinodborole?

**Comment by vinodborole** [comment]
Yes @auhlig this is been fixed

**Comment by pstoyanov91** [comment]
Hi all,
I'm using 3.0.3 and it works now. It seems that I've posted the issue just before it was fixed.
Thank you, I'm closing the issue.
