### ISSUE TITLE
osclient.objectStorage().objects().get(containerName, name) doesn't seem to parse ETag

### ISSUE THREAD

**Issue by gonewest818** [ContainX/openstack4j#944]
Using the version 3.0.3, I am getting different swift objects from `osclient.objectStorage().objects().list(containerName)` versus `osclient.objectStorage().objects().get(containerName, name)` in that the former gives me a list of SwiftObjectImpl containing ETag, wheres the latter gives me a single SwiftObjectImpl with no ETag. In this particular use case I only want the ETag for the individual file I am downloading with `get`, so it's unfortunate that the ETag isn't there.

The SwiftObjectImpl in the `get()` case is being built in an apply method on the ParseObjectFunction:

    @Override
    public SwiftObject apply(HttpResponse resp) {
        return SwiftObjectImpl.builder()
                  .name(location.getObjectName())
                  .containerName(location.getContainerName())
                  .mimeType(resp.header(CONTENT_TYPE))
                  .sizeBytes(asLong(resp.header(CONTENT_LENGTH)))
                  .metadata(MapWithoutMetaPrefixFunction.INSTANCE.apply(resp.headers()))
                  .lastModified(Parser.toRFC822DateParse(resp.header(LAST_MODIFIED)))
                  .build();

which includes explicit handling of content type and content length, but it seems to me it's just not handling etags.

**Comment by auhlig** [comment]
Hi @gonewest818,
Thanks for filing the issue.
You're right. I guess we easily could add the ETag attribute to the `get()` method.
Do you want to contribute and submit a PR for this?
Would be much appreciated.
Feel free to reach out to us in case you need help

**Comment by gonewest818** [comment]
Sure, I'll take a look at that.

**Comment by gonewest818** [comment]
btw I've got the code fixed. I'm now trying to figure out how and where to add a unit test for this.

**Comment by gonewest818** [comment]
closed.  thank you!
