### ISSUE TITLE
Upload files objectStorage Swift

### ISSUE THREAD

**Issue by oredondo** [ContainX/openstack4j#951]
Hello, I have been uploading files with this api and I have noticed that they take much longer compared to other methods like, python apis or openstack dashboad itself any solution?

**Comment by auhlig** [comment]
Hi @oredondo,
Are you reporting a bug?
If that's the case feel free to share details and feel encouraged to contribute :)
Otherwise I'd suggest to ask in our google group or on stackoverflow.
