### ISSUE TITLE
DownloadImage test failure in ImageV2Tests.java

### ISSUE THREAD

**Issue by gonewest818** [ContainX/openstack4j#957]
If I clone from master and "make test", the code builds and runs tests, but the tests stop with an assertion failure in the DownloadImage test. It's expecting a return code 400 but in my tests the result is 200.  Looks like the test case has been there for at least 6 months...  is this unique to me, or is the test actually broken?

**Comment by auhlig** [comment]
Travis CI shows everything is green. Must be related to your environment.

**Comment by gonewest818** [comment]
"make test" is running the pristine environment defined in your Dockerfile, which I can totally imagine must define a different environment than what's in Travis. Especially since the Dockerfile is using the maven:latest image and the contents would be changing over time.

In Travis, I see that particular test is throwing an exception (file not found) and returning 400.

I could rename this issue to be more clearly related to running tests in Docker... ?

**Comment by auhlig** [comment]
Indeed https://travis-ci.org/ContainX/openstack4j/jobs/206935719#L2838.
Looks like the [unit test](https://github.com/ContainX/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/image/v2/ImageV2Tests.java#L236) is covering both the 200 and 400 response.

**Comment by gonewest818** [comment]
I think the unit test is failing in Docker because the default user is root. So when that test case tries to access URL("file:////test.iso") it actually can. It's not failing as expected.

**Comment by gonewest818** [comment]
closed.  thank you!
