### ISSUE TITLE
PortListOptions with port name is not working

### ISSUE THREAD

**Issue by evgenyfedoruk** [ContainX/openstack4j#963]
Listing neutron ports with PortListOptions where displayName() was set - not working properly. All ports are returned instead of ports with the specified name.

Code example:
List<? extends Port> ports = this.osClient.networking().port().list(PortListOptions.create().displayName(portName));

The issue is in class org.openstack4j.model.network.options.PortListOptions
method - public PortListOptions displayName(String displayName)

"name" should be added to the queryParams map instead of "display_name"

**Comment by auhlig** [comment]
Since this was merged, can you close this issue @evgenyfedoruk?

**Comment by evgenyfedoruk** [comment]
The issue was fixed by deprecating the old method and adding a new one which works
