### ISSUE TITLE
Neutron Port implementation does not support port binding extension

### ISSUE THREAD

**Issue by evgenyfedoruk** [ContainX/openstack4j#966]
Neutron Port implementation does not support port binding data extension.
This extension should be supported for allowing users to create Neutron Ports with binding data.

This issue created for adding this extension support.

**Comment by auhlig** [comment]
Since this was merged, can you close this issue @evgenyfedoruk?

**Comment by evgenyfedoruk** [comment]
Port binding data was added to a port
