### ISSUE TITLE
[Question] Port (Tenant)

### ISSUE THREAD

**Issue by Rizwan-Qamar** [ContainX/openstack4j#983]
list method for Ports say "Lists all Ports authorized by the current Tenant"
but 
get method doesn't say anything related to "authorization of current Tenant"
So, does get Method return Port if id is correct but from different Tenant?

**Comment by auhlig** [comment]
Hi @Rizwan-Qamar,
I think the respective [documentation](https://developer.openstack.org/api-ref/networking/v2/?expanded=show-port-details-detail#show-port-details) can help here. There's also the tenant id in the response body.

Please ask support questions in our google group, on stackoverflow or gitter.
