### ISSUE TITLE
null project list

### ISSUE THREAD

**Issue by samanK** [ContainX/openstack4j#993]
I have authenticated by openstack v3 and get a token but I couldn't do any actions, the code not return any errors. for example the list of projects, after running the code for that, the list is null. So, I'm trying to find what is the problem. so, setup a TCPMON on that port and watch the messages are transferred and find out after authentication message nothing send to my openstack server. Is there any idea what it is for?
for more information I put the token in the restclient and create the project list message and it is worked fine.

**Comment by vinodborole** [comment]
@samanK check if you have enough permission - refer #977 for more details.

**Comment by samanK** [comment]
@vinodborole thanks a lot, my problem is solved.
