### ISSUE TITLE
swiftObject.getETag() is null on after calling swiftObject.download()

### ISSUE THREAD

**Issue by cdimascio** [ContainX/openstack4j#994]
However, the eTag is available in the header

```
val download = obj.download()
val eTag = download.getHttpResponse.header("Etag")
```

**Comment by auhlig** [comment]
I remember a PR that fixed this recently, so the eTag is an attribute of the swift obj. Which version of OS4j are you using @cdimascio?

**Comment by cdimascio** [comment]
i'm using 3.0.3. I'm see etag present in the response header, but not in `swiftObject.getETag()`
