### ISSUE TITLE
Any plan for tokenless auth?

### ISSUE THREAD

**Issue by junoyoon** [ContainX/openstack4j#995]
Keystone supports tokenless authentification which allows a client to access keystone without ID/PW and just validate the client cert.

* https://docs.openstack.org/developer/keystone/configure_tokenless_x509.html

To support this with openstack4j, We've made some trial like followings. 

```java
public class Openstack4jToAuthFakeToken {

    /**
     */
    public static void main(String[] args) throws Exception {
        String encrypt =  "12345";
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(new FileInputStream(new File("D:\\client-keystore.p12")), encrypt.toCharArray());
        SSLContext sslContext = SSLContexts.custom()
                //ignore server verify
                .loadTrustMaterial(new TrustStrategy() {
                    @Override
                    public boolean isTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                        return true;
                    }
                })
                .loadKeyMaterial(keyStore,encrypt.toCharArray())
                .build();
        Config config = Config.newConfig();
        config.withSSLContext(sslContext)
                .withConnectionTimeout(10000)
                .withReadTimeout(10000)
                .withSSLVerificationDisabled()
               // .withHostnameVerifier(SSLConnectionSocketFactory.getDefaultHostnameVerifier())
                .withMaxConnections(10);
        try {
            Token tummyToken = new DummyToken("https://test-openstack.andrew.com:5000/v3");
            OSClient.OSClientV3 osClient = OSFactory.clientFromToken(tummyToken, config);
            List<? extends User> list = osClient.identity().users().list();

            System.out.println("=====list.size():" + list.size());
        }catch (Exception e){
            e.printStackTrace();
        }
    }
}
```

Instead of getting the token from keystone, We've configured SSL context for client to use TLS client cert and I've passed DummyToken which always returns  emtpy string for token.getId(). 
Everything was OK.. except that the tokenless auth needs special [HTTP headers](https://docs.openstack.org/developer/keystone/configure_tokenless_x509.html#scope-information) whenever the call is made like following.

```
X-Project-Id - If specified, its the project scope.
X-Project-Name - If specified, its the project scope.
X-Project-Domain-Id - If specified, its the domain of project scope.
X-Project-Domain-Name - If specified, its the domain of project scope.
X-Domain-Id - If specified, its the domain scope.
X-Domain-Name - If specified, its the domain scope.
```

So far, I didn't find the way to inject these headers in openstack4j when the call to keystone is made.
Do u have any plan to support the HTTP Header injection for openstack4j?

**Comment by auhlig** [comment]
Hey @junoyoon,
Cool. @ningyougang brought this up some days ago in #992. 
To avoid duplication could you both comment who wants to take this issue?

You can add headers to the request as shown [here]( https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/identity/v3/internal/TokenServiceImpl.java#L26).

**Comment by junoyoon** [comment]
Thx, I'll write mine in #992
