### ISSUE TITLE
In Guice 21.0  Objects.toStringHelper removed

### ISSUE THREAD

**Issue by anton-tregubov** [ContainX/openstack4j#997]
In Class
org.openstack4j.api.exceptions.ClientResponseException#toString
have code like this

```
public String toString() {
		return Objects.toStringHelper(this).omitNullValues()
				     .add("message", getMessage()).add("status", getStatus()).add("status-code", code)
				     .toString();
	}
```

Guava 21.0 remove this method. And replaced with com.google.common.base.MoreObjects#toStringHelper(java.lang.Object)

**Comment by auhlig** [comment]
Hi @anton-tregubov,
Apologies for the delay.
Would you like to update the dependency and adjust the code? Feel free to submit a PR.

**Comment by auhlig** [comment]
Closing since guava was updated.
